### ISSUE TITLE
Need to get the position (x,y coordinate) of the ego vehicle car.

### ISSUE THREAD

**Issue by nikhildesa** [eleurent/highway-env#101]
1.We can get the center (x,y) from the observation but i want to find the ego vehicles all four coordinates (considering it as a rectangle box) I want to get all the vertex of the rectangle.  

2. Where can we get the ego vehicles heading direction, Basically the degree to which it is inclined to the horizontal. Ex. If the car is turning to the left it will be at angle 20 degree inclined to the horizontal.

**Comment by eleurent** [comment]
2. To get the ego-vehicle heading, you can simply do: `env.vehicle.heading`

1. To get the four corners, there is no function available for that at the moment, but you can recompute them by getting `env.vehicle.position`, `env.vehicle.heading`, `env.vehicle.LENGTH` and `env.vehicle.WIDTH`.

**Comment by eleurent** [comment]
Something like:
```
l = np.array([env.vehicle.LENGTH/2, 0])
w = np.array([0, env.vehicle.WIDTH/2])
points = np.array([- l - w, - l + w, + l - w, + l + w])
c, s = np.cos(env.vehicle.heading), np.sin(env.vehicle.heading)
R = np.array([[c, -s], [s, c]])
rotated_points = R.dot(points.transpose()).transpose()
translated_rotated_points = [env.vehicle.position + np.squeeze(p) for p in rotated_points])
```

**Comment by nikhildesa** [comment]
Thanks @eleurent , Great work!

**Comment by nikhildesa** [comment]
Hi Thanks for answering the question, Now I want to get the coordinates of all other cars in (Blue). I can use the same above logic but how can we calculate env.vehicle.heading and env.vehicle.position for other cars.

**Comment by eleurent** [comment]
All vehicles (including the ego-vehicle) are listed in `env.road.vehicles`.
They share the same interface, so you can call this function for each of them.

**Comment by nikhildesa** [comment]
Got it ! Thank you @eleurent
