### ISSUE TITLE
How to to get heading for other vehicles (Blue).

### ISSUE THREAD

**Issue by nikhildesa** [eleurent/highway-env#107]
for our agent we can find heading using env.vehicle.heading, Now I want to calculate the heading for other vehicles which are in blue. I am sure even if there is no direct implementation we can surely calculate using observation table. I am using observation type kinematics. presence,x,y,vx,vy,cos_h,sin_h. Please help.

**Comment by eleurent** [comment]
Hi @nikhildesa,
You can access it
- directly through the env object: `headings = [vehicle.heading for vehicle in env.road.vehicles]`
- or reconstruct it from the observation: `heading = np.arctan2(sin_h, cos_h)` (since `cos_h` and `sin_h` are the cos and sine of the heading)
