### ISSUE TITLE
The vehicle doesn't change.

### ISSUE THREAD

**Issue by dx2919717227** [eleurent/highway-env#108]
i want to increase density of vehicles in highway-v0 just like #81 .But no matter how I adjust the "initial_spacing",  the density of vehicles does not seem to have any changed, just the initial position of the green vehicle has changed.

How can I increase the density of the blue vehicle when the green vehicle is running?
By setting a low value for the "initial_spacing"?

thanks for your reply.

**Comment by eleurent** [comment]
Hi @dx2919717227,
Indeed, my answer to #81 was wrong: `initial_spacing` is only applied to the controlled vehicle(s), and not every vehicle. It was meant to ensure that the ego-vehicle would not start in a near-crash situation, while still having a dense traffic for other vehicles.
I'll add a separate configuration for other vehicles.

**Comment by eleurent** [comment]
You can now use the `vehicles_density` config

**Comment by dx2919717227** [comment]
thank you very much.:smile:
