### ISSUE TITLE
Unable to render the environment (return black image)

### ISSUE THREAD

**Issue by liushunyu** [eleurent/highway-env#114]
The environment: highway-v0

I use gym.Wrapper to flatten the obs and I use [spinningup](https://github.com/openai/spinningup) to train ppo algorithm on highway-v0.

When I trained successfully, I want to test it and render it, and I get a black image as a return. But if I don't use the spinningup package and just render the environment, I can get the right image.

I don't know what's wrong. In which case will the image turn black?

P.S. the output include the following warnings / errors, but the program works fine.
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default

**Comment by eleurent** [comment]
You are probably running your training and test+render on a server that is not equipped with a display?
If this is the case, the call to render() will fail when the pygame library (used for rendering) tries to initialize a new window.
This can be avoided by configuring the environment as follows:

```env.configure({"offscreen_rendering": True})```

And using the rgb_array render mode:
```img = env.render(mode='rgb_array')```

**Comment by liushunyu** [comment]
> You are probably running your training and test+render on a server that is not equipped with a display?
> If this is the case, the call to render() will fail when the pygame library (used for rendering) tries to initialize a new window.
> This can be avoided by configuring the environment as follows:
> 
> `env.configure({"offscreen_rendering": True})`
> 
> And using the rgb_array render mode:
> `img = env.render(mode='rgb_array')`

Oh...I find the bug.

Because of a previous error 

`pygame.error: No available video device`

I follow the advice on the [stackoverflow](https://stackoverflow.com/questions/15933493/pygame-error-no-available-video-device) and write that 

`os.environ['SDL_VIDEODRIVER'] = 'dummy'`

But I forget I set it, after uncomment this setting, I can get the right image.

Thank you for reply!!!

**Comment by root221** [comment]
Hi,

I had the same problem. I've done all the suggestions above, but I'm still getting a black image.
