### ISSUE TITLE
Adding lidar scans for training. 

### ISSUE THREAD

**Issue by nikhildesa** [eleurent/highway-env#116]
Hi @eleurent, 
environment: HighwayEnv
Algorithm: DQN

My goal is to train the agent using DQN by giving observation as well as lidar scans input to the NN.
I have a function that returns lidar scans for the agent's current position. Something like below

```
def lidar_scans(observation):
    /* code/
    return lidar     # lidar is a numpy array of shape (360,)

lidar_scans(observation)

```
I want to give the lidar as input along with the observation.
Example:
```
def choose_action(self, observation,lidar):
    if np.random.random() > self.epsilon:
            observation = T.tensor([observation]).to(self.Q_eval.device)
            lidar = T.tensor([lidar]).to(self.Q_eval.device)
            state_lidar = T.cat([observation,lidar],dim = 1)
            actions = self.Q_eval.forward(state_lidar)
            action = T.argmax(actions).item()
    else:
            #random action
    return action

action = agent.choose_action(observation,lidar)
```

How can we implement this to your code? Your code looks very systematic and I would like to implement it.
Thanks!

**Comment by nikhildesa** [comment]
Hi @eleurent,
my lidar file looks something like this. 

https://drive.google.com/file/d/1sztPyBTL_EF2zr9rIxU9-bLFcB2Gx8Gp/view?usp=sharing

[code](https://drive.google.com/file/d/1sztPyBTL_EF2zr9rIxU9-bLFcB2Gx8Gp/view?usp=sharing)

**Comment by eleurent** [comment]
Hi @nikhildesa 
Thats a great idea! The way I see it, there are two steps for a good integration in the project: what you want is basically to define a new type of `Observation` which gives you both access to the lidar scan and a more traditional observation (e.g. the current `KinematicsObservation`).

1. Create a `LidarObservation` class in `envs/common/observation.py`, which returns a lidar scan from a scene and considered vehicle
2. Create a `Tuple` observation to define an observation which is made up of several others.
A configuration for an instance of this class should look like this:
```
{
    type: "Tuple",
    configs: [ {"type": "KinematicsObservation"}, {"type": "LidarScan"} ]
}
```
And the `Tuple` type of observation space already exists in gym, so it can be used directly.

**Comment by nikhildesa** [comment]
Hi @eleurent 
Thanks for the idea. I don't want to make much changes with the environment setup, As I am beginner here.
Can you please help me with a simpler way like instead of giving KinematicsObservation as input I want to give the lidar as input.

Where I have a function that returns lidar data using kinematic observation.

Example
`
def lidar_scans(KinematicObservation):
    /* code/
    return lidar     # lidar is a numpy array of shape (360,)

for i in range(episodes):
    while not done:
         lidar = lidar_scans(KinematicObservation)
         state,new_state,reward,done = env.step(lidar)    
         score+=reward
         state = new_state
`

Also,Ideally using DQN with highway_env how much should we train the data so that loss is almost zero?

**Comment by eleurent** [comment]
> instead of giving KinematicsObservation as input I want to give the lidar as input

You mean as an input of the policy, right? in your code example, you give the lidar scan as an input of the environment, which does not really make sense to me... the environment takes an action as input, and returns an observation. I guess the proper syntax should be something like

```
obs = env.reset()
for i in range(episodes):
    while not done:
        lidar = lidar_scans(obs)
        action = policy(obs, lidar)
        obs, reward, done, info = env.step(action)    
        score += reward
```
where the policy is fed with the (kinematic) observation and lidar, and the environment is step with the resulting action.
If you do have an implementation of the lidar measurement, it should be quite straightforward.

> Also, Ideally using DQN with highway_env how much should we train the data so that loss is almost zero?

I'm afraid I don't have a simple anwser for that question, it kind of depends on your choice of observation, policy architecture, learning parameters etc. But it should be in the order of magnitude of 1k-10k episodes.
I suggest that you decrease the number of vehicles and episode duration while training, as it will increase the simulation performance.

**Comment by nikhildesa** [comment]
hey @eleuerent,
Yes you are correct with syntax.

> > instead of giving KinematicsObservation as input I want to give the lidar as input
> 
> You mean as an input of the policy, right? in your code example, you give the lidar scan as an input of the environment, which does not really make sense to me... the environment takes an action as input, and returns an observation. I guess the proper syntax should be something like
> 
> ```
> obs = env.reset()
> for i in range(episodes):
>     while not done:
>         lidar = lidar_scans(obs)
>         action = policy(obs, lidar)
>         obs, reward, done, info = env.step(action)    
>         score += reward
> ```
> 
> where the policy is fed with the (kinematic) observation and lidar, and the environment is step with the resulting action.
> If you do have an implementation of the lidar measurement, it should be quite straightforward.
> 
> > Also, Ideally using DQN with highway_env how much should we train the data so that loss is almost zero?
> 
> I'm afraid I don't have a simple anwser for that question, it kind of depends on your choice of observation, policy architecture, learning parameters etc. But it should be in the order of magnitude of 1k-10k episodes.
> I suggest that you decrease the number of vehicles and episode duration while training, as it will increase the simulation performance.

**Comment by nikhildesa** [comment]
Hey @eleurent,
Yes you are correct with syntax. Sorry for the confusion. 
My revised goal is  to implement following 

lidar--> fc1--fc2-->(output+velocity)-->fc3-->fc4-->actions

I was just making changes to your code, basically adding the lidar_scans function. 
In evaluation.py at line 154. 
`actions = self.agent.plan(self.observation)`

Where is this plan function? As instead of sending observations I need to send lidars to it and get the best action.

**Comment by eleurent** [comment]
- the highway-env repository contains the simulation environment, which consumes actions and produces observations
- the rl-agents repository contains RL & planning agents, which consume observations and produce actions

If you want to change the type of observation, there are two possibilities:

1. you add a new kind of LIDAR observation in highway-env, and rl-agents is unchanged. This is what I originally suggested, and feels the most natural to me. It would be a contribution to the open-source environment.
2. as you suggest: you change the training pipeline in rl-agents: the observation produced by the environment is discarded, you compute the lidar scans manually, and then use them in place of the old observation for the agent. It is also a possibility, but it seems more sloppy to me, and should not be merged (i.e. it won't profit to anyone).

> Where is this plan function? 

It is implemented by every agent in highway-env. When agents only plan a single action, it is implemented in the `agent.act(observation)` method. e.g. [here for DQN](https://github.com/eleurent/rl-agents/blob/master/rl_agents/agents/deep_q_network/abstract.py#L65)
For example,
