### ISSUE TITLE
Question about vehicle behavior

### ISSUE THREAD

**Issue by chenxiaochang** [eleurent/highway-env#117]
Hi , 
I have been using highway environment to create vehicles in some scenario. I want to know can we modify the behavior of other vehicles (not the ego one), i.e., aggressive or conservative? Especially can we modify their behavior according to the ego vehicle. Thank you in advance.

**Comment by eleurent** [comment]
Hi @ chenxiaochang,
Right now, the vehicles behave according to the IDM and MOBIL models, implemented in `vehicle/behavior.py`
There behaviors are parametrized, and adjusting some of these parameters (e.g. the desired maximum acceleration/deceleration, time gap, minimum acceleration gain for lane changes and maximum imposed braking) will yield more aggressive/conservative behaviors. For instance, you can try the values indicated in the Table 3.1 of https://zachary.sunberg.net/thesis.pdf (or Table 2 of https://arxiv.org/pdf/0805.0300.pdf)

**Comment by chenxiaochang** [comment]
Hi @ eleurent ,
Thank you for your reply to the vehicle behave, it's very useful!
I also have one question: if the ego-vehicle(or other vehicle) and another vehicle are driving in the same lane in the  opposite direction ,will IDM models  can change the behave of the vehicles(such as braking or stopping) to avoid collision.Thank you.

**Comment by eleurent** [comment]
Yes, the IDM model adapts its speed to avoid collisions with the front vehicle on the same lane. It this front vehicle is going in the opposite direction, the IDM should brake even faster.

**Comment by chenxiaochang** [comment]
Thank you for your guidance.I created two other vehicles in the same lane with the opposite direction , but the vehicles collision,I don't know it's why ,could you give me some help.

`     v1 = vehicles_type(road,
                           position=road.network.get_lane(("b", "a", 1))
                           .position(400, 0),
                           heading=road.network.get_lane(("b", "a", 1)).heading_at(400),
                           speed=20,
                           enable_lane_change=False)
        v1.target_lane_index = ("b", "a", 1)
        self.road.vehicles.append(v1)

        v2 = vehicles_type(road,
                           position=road.network.get_lane(("a", "b", 1))
                           .position(200, 0),
                           heading=road.network.get_lane(("a", "b", 1)).heading_at(200),
                           speed=20,
                           enable_lane_change=False)
        v2.target_lane_index = ("a", "b", 1)
        self.road.vehicles.append(v2)`
![Uploading 2020-11-10 22-40-26屏幕截图.png…]()

**Comment by chenxiaochang** [comment]
Hi，@ eleurent, could you give some solutions to the problem of vehicle collision, looking forward to your reply!

**Comment by eleurent** [comment]
Hi @chenxiaochang , 
I investigated: there is a bug in the neighbour_vehicles() function that computes the front vehicle of a given vehicle, used in the IDM model to regulate speed.
Basically, the vehicle coming from the right is assigned to the lane going to the right, so the other vehicle is considered as behind it (rather than in front of it), which explains why it won't even decelerate.

I'll push a fix soon.
