### ISSUE TITLE
automatic_rendering_callback

### ISSUE THREAD

**Issue by xli4217** [eleurent/highway-env#118]
Hi, it seems that when I use gym.wrappers.Monitor to record videos intermediate frames are not recorded. I see in the abstract.py class that setting a automatic_rendering_callback() can solve this issue, I was wondering how exactly can this be done. Thank you.

**Comment by eleurent** [comment]
Hi,
Yes, this comes from the fact that the simulation frequency is not the same as the decision (policy) frequency, but the Monitor implementation from openai.gym is only able to capture a frame whenever `env.step(action)` is called.

To record intermediate frame, I did the following
* as you have seen, the environment has an `automatic_rendering_callback` callback, initialized to None
* this callback, when set, is called whenever a timestep is simulated (i.e. at each frame)
* thus, at environment creation, it remains to set the callback to the Monitor's video recorder `capture_frame` method.

Here is an example:
```
import highway_env
import gym
from gym.wrappers import Monitor

env = gym.make('highway-v0')
env = Monitor(env, directory=".", force=True)
env.reset()
env.unwrapped.automatic_rendering_callback = env.video_recorder.capture_frame

done = False
while not done:
    _, _, done, _ = env.step(1)
    env.render()
env.close()
```

**Comment by xli4217** [comment]
It works, thanks a lot!
