### ISSUE TITLE
Run the environment not via pip

### ISSUE THREAD

**Issue by Derekabc** [eleurent/highway-env#119]
Hi author, thanks for this wonderful open-sourced environment. I am wondering can I run the environment not by installing it via pip.

Can I just download it and run it by download the files and put them into my project? How can I do that?
![image](https://user-images.githubusercontent.com/25771207/98444347-32fa6a80-20df-11eb-866f-7cfd73f731ac.png)

**Comment by eleurent** [comment]
Hi,
Yes of course, you can just git clone the repository, and add the `highway_env` directory to your python path.

If you are using PyCharm, just add the cloned `highway-env` directory into your projet, and its content will be automatically added to the python path. 
![image](https://user-images.githubusercontent.com/1706935/98656007-730c5800-2340-11eb-8447-e23eebe9f0a9.png)

You may have to set the dependency of your main project to `highway-env` in Settings/Project/Project dependencies 

![image](https://user-images.githubusercontent.com/1706935/98656110-9505da80-2340-11eb-926f-a029fd8f4cfb.png)

**Comment by Derekabc** [comment]
Thanks, I have made it! One quick question: if I made any changes to the highway-env environments, say vehicle model, do I need to recompile it? Or it will automatically detect the changes.

**Comment by eleurent** [comment]
It should automatically detect the changes, if it is copied locally.
