### ISSUE TITLE
Be able to create multiple "Ego" Vehicles to run multi-threads algorithms such as A2C, A3C...

### ISSUE THREAD

**Issue by munirjojoverge** [eleurent/highway-env#12]

**Comment by eleurent** [comment]
Hello Munir,
I guess A2C/A3C can already be implemented by instanciating several workers, each having their own instance of highway-env (with a single ego-vehicle).

If you are thinking of a multi-agent setting, where the different ego-vehicles actually interact with each other, then it is different. On the simulation side, it is already possible to add several MDPVehicle to a scene. The question is how to interface these agents in terms of Gym API. As a joint state-action space, maybe?

**Comment by munirjojoverge** [comment]
Hi Edouard,
Thanks for your prompt response. Very nice to hear from you.
Well, I was testing your environments and made some changes to be able to run some of the OpenAI baselines (ddpg, ppo2, trpo, a2c) and also change it to use a continuous action space (Steering, Accel/Decel) and was struggling getting A2C running with more than 1 env. I digged into it but wasn't able to address the problem...so I started to think about running multi-agents and 1 environment. I did run it with 1 env, though, and I'm still waiting to finish training.My objective was to compare performances of the different algos on the roundabout. So far, the results are not promising (ddpg, ppo2 & trpo) (even after also changing the reward function) an it looks like a continuous space with the information provided to the agents is not enough to solve the "driving properly" problem. Have you ever experimented with your environments using a continuous action space for steering and Accel/Decel to solve the roundabout?I'd love to hear your thoughts on that.
I'm probably moving back to a discrete action space and letting the "motion planner" figure the steering/accel details...and compare the performance of various algos. 
Best regards,
Munir Jojo-Verge  
*****************************************This message is intended only for the individual or entity to which it is addressed and may contain information that is privileged, confidential and exempt from disclosure under applicable law. If you are not the intended recipient, or the employee or agent responsible for delivering the message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited, and you are requested to please notify us immediately using this email address, and to purge the communication. 

    En jueves, 24 de enero de 2019 10:04:53 GMT-5, Edouard Leurent <notifications@github.com> escribió:  
 
 
Hello Munir,
I guess A2C/A3C can already be implemented by instanciating several workers, each having their own instance of highway-env (with a single ego-vehicle).

If you are thinking of a multi-agent setting, where the different ego-vehicles actually interact with each other, then it is different. On the simulation side, it is already possible to add several MDPVehicle to a scene. The question is how to interface these agents in terms of Gym API. As a joint state-action space, maybe?

**Comment by munirjojoverge** [comment]
Hi again,
Let me quickly respond:
   
   - Continuous actions: Done
   - Contributing: I'd love to. I'll clean up the code soon and reach out.
   - Running several instances: Aware of the rendering issue. At the end of the day, A2C/A3C is just being slower since it's basically 1 single agent anyway..so I'm patient
   - Bad PPO/TRPO performances on Roundabout: Make sense. Great points.
   - Roundabout with continuous actions: Done. The Reward has been changed:
   
   -  Off road changes required: self.road.network.is_inside_network(self.vehicle.position)   

   - Goal distance (re-used)
   - General view:
   -     COLLISION_REWARD     = -1
   -     HIGH_VELOCITY_REWARD = 0.2 # Only if it's inside the rode    RIGHT_LANE_REWARD    = 0    LANE_CHANGE_REWARD   = -0.05 # At this point not using this. Letting the agent wander    REVERSE_REWARD       = -0.5    OFF_ROAD_REWARD      = -0.5    DISTANCE_TO_GOAL_REWARD = 1     



Best regards,
Munir Jojo-Verge  
*****************************************This message is intended only for the individual or entity to which it is addressed and may contain information that is privileged, confidential and exempt from disclosure under applicable law. If you are not the intended recipient, or the employee or agent responsible for delivering the message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited, and you are requested to please notify us immediately using this email address, and to purge the communication. 

    En jueves, 24 de enero de 2019 11:26:24 GMT-5, Edouard Leurent <notifications@github.com> escribió:  
 
 
Hi again,
There are many points in your last comment:
   
   - Continuous actions: the base class Vehicle implementing the car kinematics is controlled in terms of continuous accereration and steering (see Vehicle.act()), so you can easily implement a new variant/configuration of the environment by changing the MDPVehicle class by a simple Vehicle class, and updating the action space accordingly to a Box.
   - Contributing: apparently you already made some changes in this direction, please feel free to contibute and create pull requests, and I'll be glad to review and help if needed.
   - Running several instances: one limitation that is present today is that I am using PyGame for rendering, and unfortunately it doesn't support multiple windows at the same time. So running several instances of highway-env in parallel should work, but only as long as you do not render the environments.
   - Bad PPO/TRPO performances on Roundabout: I think the main issue probably comes from the state representation. For now, it is not generic at all: coordinates are expressed in the XY frame instead of a Frenet frame, with scalings/clipping that only make sense for an horizontal road. So I wouldn't expect this particular observation format to work on the roundabout env. Rescaling may probably help a lot, or even switching to an image/occupancy map representation.
   - Roundabout with continuous actions: with a good state representation, continuous actions should not be a problem. However, the reward function should be modified to penalize off-road driving (which doesnt happen with discrete actions, are low-level controllers are already in charge of lane keeping)

Does that help? Thank you for your interest,
Edouard

**Comment by eleurent** [comment]
I am looking forward to your pull request. Now that you've dealt with actions and rewards, the last question remaining for continuous control will be the choice of state representation. The road geometry must obviously be included. A top-view image similar to [Waymo's ChauffeurNet](https://sites.google.com/view/waymo-learn-to-drive) or [David Ha & Schmidhuber's World Models](https://worldmodels.github.io/) is a possibility, along with other kind of geometric features (e.g. lateral distance, local curvature, etc).

Concerning this particular issue of multithread training, it is already possible to do so by disabling rendering, which I think is not too constraining (rendering can still be used for evaluation purposes).
Thus, I am closing this issue. If you care about the single-environment multi-agent setting as opposed to simply A2C/A3C parallel training, feel free to open another one.

Edouard
