### ISSUE TITLE
Collecting experiences is very much slow.

### ISSUE THREAD

**Issue by StepNeverStop** [eleurent/highway-env#121]
Hello,

Is there any config that could accelerate the speed of interaction with the training environment?  'cause the process is very much slow, it takes me about 1 sec to receive every new observation(state), is there any chance to improve the speed 100x and more?

I've tried modifying the configurations like this, but no significant improvement was felt:

```
env.config['simulation_frequency'] = 10000 
env.config['policy_frequency'] = 1000
env.config['duration'] = 100000
```

**Comment by Derekabc** [comment]
hi, from my perspective, I think you should set the duration as a small value, it determines your episode length. I think simulation frequency should depend on your hardware and algorithms. You can set like  
```
env.config['simulation_frequency'] = 30
env.config['policy_frequency'] = 1
env.config['duration'] = 30
```
It means duration 30s, a policy taken 1 Hz, simulation 30 Hz.

**Comment by StepNeverStop** [comment]
@Derekabc Hi, for this issue, I don't care about the episode length actually. It is very slow to collect only one experience <s_t, a_t, r_t, s_{t+1}>, 'cause you set policy_frequency to 1. What I concern about is how should I set the configuration to collect more experiences within 1 sec beyond using vectorized environments. 

Turn up `policy_frequency` doesn't bring great speed improvements to me.

**Comment by eleurent** [comment]
Hi,
* `simulation_frequency` controls the frequency at which the world is refreshed. Increasing it will increase the accuracy of the simulation, but also the computation time.
* `policy_frequency` controls the frequency at which decisions are taken, and thus that at which transitions (s,a,s') are observed

Increasing policy frequency (it should always be lower or equal to the simulation frequency) will give you more samples for the same simulated trajectories.
But if you want to increase the "speed" of the simulation (simulated time / real time), you should:

* decrease simulation frequency (but if it is too low, the simulation will become unstable)
* most importantly: decrease the number of vehicles in the scene. See https://github.com/eleurent/highway-env/issues/36 for more details.

Disclaimer: This simulator is in full python, and ease of prototyping was prioritized over performance. There are many steps which could be taken to optimize the simulation speed (e.g. use quadtrees for collision checks, rely on numba/jit/cython for loops and numerical integration), but it is not planned for the moment.

**Comment by StepNeverStop** [comment]
@eleurent Hi, thank you for the explanation.

From what I understand, `simulation_frequency` controls how many frames will be calculated within 1s, and `policy_frequency` controls how many decisions should be requested within 1s. Am I right?

For now, I can just receive 1 transition per second with `policy_frequency=1`, and decrease the simulation frequency will bound the value of `policy_frequency`. I wanna obtain much more transitions per second, do you have some advice to set the configuration to achieve this? Thx...

**Comment by eleurent** [comment]
> From what I understand, simulation_frequency controls how many frames will be calculated within 1s, and policy_frequency controls how many decisions should be requested within 1s. Am I right?

Yes, exactly

> I wanna obtain much more transitions per second, do you have some advice to set the configuration to achieve this? Thx...

If your only concern is the number of observations per second, regardless of the corresponding simulated time, you should set policy_frequency = simulation_frequency = something probably between 10 and 30 (so that no frame is "wasted"). Changing from 10 to 30 will affect the number of transitions you get per second, but only the "duration (dt)" of each of these transitions.

Then, to speed up computations of each frame, you should
1. make sure that you are not rendering
2. decrease the number of vehicles in the scene, which is a quadratic term in the computational complexity. For exemple, going from 50 to 10 simulated vehicles will give a x25 speedup.

**Comment by StepNeverStop** [comment]
@eleurent Thank you for your solutions, very helpful.
