### ISSUE TITLE
Trajectory Planer Implementation

### ISSUE THREAD

**Issue by ashivam03** [eleurent/highway-env#123]
Can you explain how is the trajectory planer implemented in the code?
As in how and where is the reference trajectory being generated for the controller to track

**Comment by eleurent** [comment]
Hi @ashivam03,
The trajectory planners are implemented in the https://github.com/eleurent/rl-agents repository.
They consist in Monte-Carlo Tree Search (MCTS) algorithms, which output a sequence of discrete actions: change lane, faster, slower, etc. These actions change the setpoints of desired speed and lateral position, which are tracked by the speed and steering controllers.
Several MCTS algorithms are implemented, including [OPD](https://hal.archives-ouvertes.fr/hal-00830182/document), [UCT](http://ggp.stanford.edu/readings/uct.pdf) and [OLOP](http://sbubeck.com/COLT10_BM.pdf).
