### ISSUE TITLE
Reward Design in Merging-v0

### ISSUE THREAD

**Issue by Derekabc** [eleurent/highway-env#124]
Hi author, I am trying to play with the merging-v0 environment. I found there is a merging_reward.
```
# Altruistic penalty
 for vehicle in self.road.vehicles:
       if vehicle.lane_index == ("b", "c", 2) and isinstance(vehicle, ControlledVehicle):
            reward += self.MERGING_SPEED_REWARD * \
                     (vehicle.target_speed - vehicle.speed) / vehicle.target_speed
```
It seems it is designed to only penalize the controlled vehicles in the merging lane, which is replicated with the Speed reward? If I want to consider the efficiency of the merging, how to design the merging efficiency reward? Any suggestions. Thank you!

**Comment by eleurent** [comment]
Hi @Derekabc ,

Actually, this reward was originally meant for a scenario where the ego-vehicle is already on the highway, and must act in an altruistic manner by making space (i.e. slowing down or changing lane) for the vehicles on the merging lane. 

Note: here, the class `ControlledVehicle` does that the vehicle is controlled by the agent, but rather that it is able to control its own speed and lateral position (required for `target_speed` to be defined), but it could be any vehicle on the road.

It is a different task than the one you are suggesting, where the ego-vehicle itself has to merge into traffic. In this case, there could be many possible designs, but all should include an efficiency term (average velocity, amount of time spent on the highway vs on the access ramp, etc.) and a safety term (avoid collisions).

**Comment by Exasor** [comment]
Hi, I notice that in the `_reward` function in merge_env.py, it returns 
```
 return utils.lmap(action_reward[action] + reward,  
                          [self.COLLISION_REWARD + self.MERGING_SPEED_REWARD,  
                            self.HIGH_SPEED_REWARD + self.RIGHT_LANE_REWARD],
                          [0, 1])
```
and the minimum reward ignores the lane change reward wihch equals to `self.COLLISION_REWARD + self.MERGING_SPEED_REWARD` , should I add it?

**Comment by eleurent** [comment]
Indeed! Yes, please, that would be better.
