### ISSUE TITLE
pip3 install repo in stable-baselines docker

### ISSUE THREAD

**Issue by KexianShen** [eleurent/highway-env#131]
Hi eleurent,

I try to use "pip3 install git+https://github.com/eleurent/highway-env" to install highway-env module in the stable-baselines docker. I installed the docker from this link "https://stable-baselines.readthedocs.io/en/master/guide/install.html?highlight=docker#using-docker-images". It returned

root@cc9c19bd2d84:/# pip3 list | grep highway
highway-env                   1.0.dev0    
root@cc9c19bd2d84:/# python3
Python 3.5.2 (default, Oct  8 2019, 13:06:37) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import highway_env
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/venv/lib/python3.5/site-packages/highway_env/__init__.py", line 5, in <module>
    import highway_env.envs
  File "/root/venv/lib/python3.5/site-packages/highway_env/envs/__init__.py", line 1, in <module>
    from highway_env.envs.highway_env import *
  File "/root/venv/lib/python3.5/site-packages/highway_env/envs/highway_env.py", line 20
    RIGHT_LANE_REWARD: float = 0.1
                     ^
SyntaxError: invalid syntax

**Comment by eleurent** [comment]
Thanks for the feedback!
The SyntaxError is related to the type hint (:float). This syntax comes from the [PEP 526](https://www.python.org/dev/peps/pep-0526/) rule that I used, which only supported in Python 3.6+ while the docker image is based on Python 3.5.

That's unfortunate... I'd like to support any Python 3 version, but I don't really want to drop type hinting either.

**Comment by KexianShen** [comment]
Thank you for your reply. 
Yeah, if I were you, I would keep the type hinting too.
