### ISSUE TITLE
When I monitor env with wrappers, the configuration is not reflected.

### ISSUE THREAD

**Issue by Kota9684** [eleurent/highway-env#132]
Hi!
If I defined `env=gym.wrappers.Monitor(gym.make(ENV_NAME), SAVE_DIR + str(i_), force=True)`,` env.configure(HighwayEnv_CONFIG)` is not reflected.
Of course, it will be reflected if I defined `env=gym.make(ENV_NAME)`.

Could you tell me if you have any idea what might be causing this?
Or do you know another way to record ?

Thank you.

Ubuntu 18.04 LTS

**Comment by eleurent** [comment]
Hi! I've tried it and it works, but don't forget that you should `reset()` the environment for most configuration changes to be applied. For example:

```
import gym
from gym.wrappers import Monitor
import highway_env

env = Monitor(gym.make("highway-v0"), './log', force=True)
env.configure({"lanes_count": 7})
env.reset()
env.render()
```

**Comment by Kota9684** [comment]
Thank you for responding!

I had done the reset after applying the config, but for some reason I could not get the action_space as applied in the config.
But, I was able to solve the problem by monitoring it afterwards as follows!
Thank you.
```
import gym
import highway_env

BATCH_SIZE = 1

envs = [gym.make("highway-v0") for idx in range(BATCH_SIZE)]
for env in envs:
                env.configure({"lanes_count": 7})
                env.reset()
envs = [gym.wrappers.Monitor(env.unwrapped, "./log", force=True) for env in envs]
```
