### ISSUE TITLE
Spawn ego-vehicles and other vehicles randomly

### ISSUE THREAD

**Issue by Mikael-OLS** [eleurent/highway-env#134]
Hi, I am running a multi-agent project on highway-v0. Say that I have 5 controlled ego-vehicles, then they all spawn in a cluster at the beginning of the road. I would like them to spawn randomly, with a probability that other vehicles(not controlled) spawn in between them. Is this possible? Thanks, Mikael.

**Comment by eleurent** [comment]
Hi @Mikael-OLS,

That should not be too difficult to modify.

I think that at the moment, I spawn every new vehicle at the front of the current traffic. I start with the N controlled vehicles, and then proceed to the M other vehicles.
It suffices to change the order and insert M/N other vehicles after each controlled vehicle.
