### ISSUE TITLE
videos saved play very fast and record the last frame of previous episode

### ISSUE THREAD

**Issue by eleurent** [eleurent/highway-env#139]
I found another problem that the videos saved play very fast and record the last frame of previous episode, but don't display the first frame of this episode like this 

https://user-images.githubusercontent.com/56293255/109617311-31aeeb00-7b71-11eb-95f1-2bc2fd81f379.mp4

and my code is as follows:
```
for episode in range(1, 1 + n_episode):
    ...
    while not done:
        if display_record:
            env.render()
        ...
        if done:
            env.reset()
            ...
            break
env.close()
```

_Originally posted by @Exasor in https://github.com/eleurent/highway-env/issues/138#issuecomment-788721984_

**Comment by eleurent** [comment]
About the video playing too fast, this is due to the fact that env.render() only renders a single frame, while env.step(action) (policy) typically simulates several frames of dynamics (which are not rendered).

This issue is difficult to circumvent given gym's implementation of Monitor and video_recorder. I use a little hack where  I provide the monitor's video recorder's `capture_frame` method to the Environment, so that it can call it whenever it simulates a timestep.

```
env = Monitor(env, ...)
...
env.reset()  # a new video recorder is created at every environment reset
env.unwrapped.automatic_rendering_callback = env.video_recorder.capture_frame  # forward its capture_frame to the env 
```

With this, your videos should contain every frame and play at a normal speed.

I'll investigate the first frame issue.

**Comment by Exasor** [comment]
I add `env.unwrapped.automatic_rendering_callback = env.video_recorder.capture_frame` after `env.reset()` but there's something wrong:
```
env.unwrapped.automatic_rendering_callback = env.video_recorder.capture_frame
AttributeError: 'list' object has no attribute 'capture_frame'
```

**Comment by eleurent** [comment]
That is strange... The video recorder should be created after Monitor.reset(), which calls Monitor.reset_video_recorder().

The following script worked for me:

```
import gym
import highway_env

env = gym.make("highway-v0")
env = gym.wrappers.Monitor(env, "./log", video_callable=lambda episode: True, force=True)

for episode in range(3):
    done = False
    env.reset()
    env.unwrapped.automatic_rendering_callback = env.video_recorder.capture_frame
    while not done:
        _, _, done, _ = env.step(env.action_space.sample())
        env.render()
```

Can you confirm?
However, I could reproduce your issue with the first/last frame, so I will investigate and fix it, thanks for the feedback.

**Comment by eleurent** [comment]
The first/last frame issue should be fixed now.

**Comment by Exasor** [comment]
Thanks a lot for your quick reply, indeed, I use a deep reinforcement platform [https://github.com/thu-ml/tianshou](url)  and follow the example code to set `env = DummyVectorEnv([lambda: env])` , I'm not clear about what the `DummyVectorEnv()` do, so I guess it maybe the source of problem, and I may ask the author of the platform for help.
