### ISSUE TITLE
question about the right lane reward

### ISSUE THREAD

**Issue by Exasor** [eleurent/highway-env#140]
I noticed the right lane reward in highway_env is `self.RIGHT_LANE_REWARD * lane / max(len(neighbours) - 1, 1)`, it aims at get larger reward while getting closer to the right lane, and according to my understanding, the road with 3 lanes is as follows:
![图片](https://user-images.githubusercontent.com/56293255/110090176-f3643680-7dd1-11eb-8c84-38efb679c67a.png)
while in left lane, the lane_index[2] is larger, leading to a larger reward, I don't know where I misunderstand

**Comment by eleurent** [comment]
This is because the coordinate system that I use has a downward y axis.

So its actually like this:
```
-------------------------------> X
|                      lane 0
|   -----------------------------
|                      lane 1
|   -----------------------------
|                      lane 2
|   -----------------------------
V
Y
```

If this frame convention is too confusing, I may change it

**Comment by Exasor** [comment]
Thanks a lot, no wonder I feel strange

**Comment by eleurent** [comment]
Old habits I guess, I used to work in aeronautics: https://en.wikipedia.org/wiki/Axes_conventions :)

**Comment by Bernicorn** [comment]
Where did you defined the coordinate system?
I want to try to change it to the first quadrant of cartesian coordinate systems.

**Comment by eleurent** [comment]
@Bernicorn the simulation is performed in an (arbitrary) x/y cartesian coordinate system.
Then, i chose the convention that x = horizontal, left to right and y = vertical, top to bottom in the rendering parts of the library, and in particular in the ``WorldSurface` class, which defines conversions from world space to pixel coordinates here: https://github.com/eleurent/highway-env/blob/3ef36a0fb17f91769ecac9581206bd51cce41108/highway_env/road/graphics.py#L47

**Comment by Bernicorn** [comment]
ok thanks for that, i want to change the coordinate system to y -> bottom to top. Where did you choose that convention in code?

**Comment by eleurent** [comment]
In `pos2pix`, where I wrote that an (x,y) word position corresponds to the pixel coordinate
```
return self.pix(x - self.origin[0]), self.pix(y - self.origin[1])
```
where self.pix is simply a scaling function.

Basically, I kept the same convention that is used in computer graphics (and here in pygame, which is used for rendering), where the (0,0) pixel is the top-left corner, and y is downward.

If you want to change it, you can simply replace this line by
```
self.pix(x - self.origin[0]), self.get_height() - self.pix(-y + self.origin[1])
```

However, note that by switching the direction of the Y axis, you also need to reverse all angles from θ to -θ.

For instance, here:
https://github.com/eleurent/highway-env/blob/3ef36a0fb17f91769ecac9581206bd51cce41108/highway_env/vehicle/graphics.py#L90
replace `h` by `-h`

**Comment by Bernicorn** [comment]
thanks a lot edouard :)
