### ISSUE TITLE
Best Strategy for applying stable baselines to dict obs env (such as parking-v0, summon-v0, lane-keeping-v0)

### ISSUE THREAD

**Issue by hougiebear** [eleurent/highway-env#142]
Hi

Has anyone had any success in applying stable baselines to the continuous environments from Highway that return a dictionary of observations?

I'm looking into it (works for HER algos but that is because they are using a wrapper). I'd rather not do a ham-fisted job and lose information thus has anyone implemented this for let's say, A2C or SAC? 

If not I can take a stab at it.

**Comment by eleurent** [comment]
Hi @hougiebear 
Indeed this dict observation format was initially meant to fit the definition of GoalConditionedEnv environments, which are required by the HER implementation.

I haven't tried it directly with A2C or SAC yet, but the best way would probably be to define a new ObservationType which simply concatenates the different values contained in the original dict

**Comment by hougiebear** [comment]
Hi Edouard, I will close this. I don't need to run the Actor-Critic/Policy Gradient methods vanilla for my research, Hindsight experience replay is fine.
