### ISSUE TITLE
a small error of online document.

### ISSUE THREAD

**Issue by zhen-liu-github** [eleurent/highway-env#145]
Hello, eleurent, a very nice job of this environment.
But I found a small spell error in online document where I waster some time.
[https://highway-env.readthedocs.io/en/latest/observations/index.html](url)

In this line.
If configured with normalized=True (default), the observation is normalized within a fixed range, which gives for the range [100, 100, 20, 20]:

I think the right config name is normalize not normalized.

**Comment by eleurent** [comment]
Indeed! Sorry for the typo, and thanks for reporting this.
