### ISSUE TITLE
A question about IDMVehicle.make_on_line function

### ISSUE THREAD

**Issue by zhen-liu-github** [eleurent/highway-env#146]
hello, i'm sorry to bother you again. I try to use IDMVehicle.make_on_line function to create a new vehicle according to lane index and lon position, but it reports an error which is  "type object 'IDMVehicle' has no attribute 'make_on_line'".
I think the IDMVehicle is a subclass of Vehicle and has the make_on_line method.
Please help me and point out my error, thank you very much.

**Comment by eleurent** [comment]
Hi @zhen-liu-github 
I think you simply misread the method name, it is make_on_**lane** rather than line :)

https://github.com/eleurent/highway-env/blob/a6b390ca9115607304c8808e0d84dcf7ff5e831d/highway_env/vehicle/kinematics.py#L45

**Comment by zhen-liu-github** [comment]
thanks
