### ISSUE TITLE
highway-v0 environment Multiple controlled vehicles

### ISSUE THREAD

**Issue by yubai111** [eleurent/highway-env#155]
Thank you for creating such a perfect environment for autonomous driving. In the example you give, a vehicle can run reinforcement learning perfectly and avoid obstacles perfectly. But wheni changed ‘controlled vehicles’  parameter as 2, one of the vehicles was out of control. I don't know why. Could you teach me?

**Comment by rjoseph24** [comment]
@yubai111 , could you provide the code you used to train the model on highway-v0 environment? I have been trying it using DQN and A2C but it doesn't seem to provide the results I am looking for. It does try to avoid collisions in DQN and doesn't go onto the rightmost lane or avoid collisions in case of A2C.

Any help is appreciated.

**Comment by eleurent** [comment]
@yubai111 
Sorry for the late response.

The docs embarrassingly lack a section about the multi-agent setting.

In addition to increasing the number of controlled vehicles, you must also change the action type to `'MultiAgentAction'`, which corresponds to a tuple of actions (you must provide the shared base action config). Then, you have to send all actions in a tuple:
```env.step((action1, action2))```

Likewise, the observation should be set to a `MultiAgentObservation`, which returns a tuple of observations:
```
obs = env.reset()
while not done:
    obs1, obs2 = obs
    action1 = agent1.predict(obs1)
    action2 = agent2.predict(obs2)  # note that agent2 can also be the same as agent1
    obs, reward, done, info = env.step((action1, action2))
```

I will update the docs.

@rjoseph24 see the provided example and notebook in the documentation.
