### ISSUE TITLE
highway-v0 environment with high vehicle numbers and vehicle density

### ISSUE THREAD

**Issue by yubai111** [eleurent/highway-env#158]
thanks for your codes. it's really useful for me. But when i use your examles in google colab ,  i try to change the parmas about 'vehicle numbers and vehicle density'. the vehicles are always crashed , i don't know why .  could you please help me?
![32d579f5bf02bda8e33bdc31cd6695a](https://user-images.githubusercontent.com/74220986/114024654-e510ab00-98a6-11eb-9e16-af592a5978d5.png)

**Comment by eleurent** [comment]
Mmmmh, right now the vehicle spawn mechanism is a bit simplistic, it ensures that the vehicles initially do not collide but their initial velocity are chosen randomly, which means that crashes may be unavoidable in some situations (if a fast vehicle is created very close to a slow one, it won't have the time to brake).

This only happens in dense traffic though, which probably require a more sophisticated initialization.

But simply initializing all vehicle speeds to a constant value, though unrealistic, should at least solve the issue.
