### ISSUE TITLE
The ego vehicle speed in IDM

### ISSUE THREAD

**Issue by Exasor** [eleurent/highway-env#184]
I noticed that in behavior.py, the of code in `acceleration()` is 
```
acceleration = self.COMFORT_ACC_MAX * ( 1 - np.power(max(ego_vehicle.speed, 0) / ego_target_speed, self.DELTA))
```
but I think in IDM, the speed refers to the longitudinal speed of ego vehicle, which is only a part of `ego_vehicle.speed`.

**Comment by eleurent** [comment]
The name might be confusing, but `Vehicle.speed` actually denotes the longitudinal speed of a `Vehicle`.
- most vehicles follow the bicycle kinematics model, where the no-slip condition is assumed
- in the dynamical model (rarely used), `speed` still denotes the longitudinal speed (for consistency), and a `lateral_speed` attribute is added.

**Comment by eleurent** [comment]
Actually, you are right: if the vehicle has heading $\psi$ and steering angle $\delta$, the vehicle `speed` is actually applied in the direction $\psi+\delta$, so it is not aligned with the vehicle's longitudinal axis.

So adding a projection is probably more correct, but I don't think this will have a big impact on the simulation.

**Comment by Exasor** [comment]
Thanks a lot
