### ISSUE TITLE
Changing observations for each env

### ISSUE THREAD

**Issue by hougiebear** [eleurent/highway-env#186]
Hi just a query. Is it possible to change the observations from kinematic to image based to use SB3 CNN Policies? If so do you have working examples?

**Comment by eleurent** [comment]
The instructions on how to change observations can be found in [the documentation](https://highway-env.readthedocs.io/en/latest/observations/index.html).

An example based on SB3 CNN policies is shown in [the scripts](https://github.com/eleurent/highway-env/blob/master/scripts/stablebaselines_highway_cnn.py).

However, it only works with the current development version and not with the latest version, which is a problem -> I'll make a new release.

**Comment by hougiebear** [comment]
Thanks. Worked fine. Tested it on the discrete environments - Intersection, merge, Roundabout, u-turn, highway etc and worked fine. 

Haven't tested it on Continuous Goal environments (parking-v0, summon-v0) as assume have to build a custom observation type to handle the observation shapes from (target_size, target_size) to something akin to (target_size, target_size, 1) ?

**Comment by eleurent** [comment]
> Haven't tested it on Continuous Goal environments (parking-v0, summon-v0) as assume have to build a custom observation type to handle the Grayscale observation shapes from a continuous env?

Yes, exactly. And you also need to be able to generate image observations of the goal, which is doable but may not be trivial.

**Comment by hougiebear** [comment]
> > Haven't tested it on Continuous Goal environments (parking-v0, summon-v0) as assume have to build a custom observation type to handle the Grayscale observation shapes from a continuous env?
> 
> Yes, exactly. And you also need to be able to generate image observations of the goal, which is doable but may not be trivial.

Thanks for confirming Edouard. For now, I believe the existing observation type is fine for my experiments given the "collision" in parking is effectively crossing parking space lines and doesn't terminate the episode.
