### ISSUE TITLE
The relationship among policy frequency,simulation frequency and duration

### ISSUE THREAD

**Issue by Exasor** [eleurent/highway-env#187]
I set the policy frequency = 5, simulation frequency = 15, duration = 400, and the duration checks the `self.steps` which updates according to the policy frequency, and the video should last 400/5 = 80s, but while reaching the duration of 400, I get a video with only 53s. I think the number of 53 comes from 400 ≈ 53*15/2, but not clear about the reason.

**Comment by eleurent** [comment]
You may have a 1/2 factor because the video is played at a default framerate of 30 fps, while simulation frames are only recorded at 15 Hz (the video plays at x2 speed). But that should give you a video duration of 400/5 * 15/30 = 80s, not 53s.
I'll try to reproduce it and see what's going on.

**Comment by eleurent** [comment]
I could not reproduce this issue, please reopen if the problem is still there for you.
