### ISSUE TITLE
SB3 HER Example

### ISSUE THREAD

**Issue by araffin** [eleurent/highway-env#188]
Hello,
As SB2 is now deprecated, would you be interested in an updated version of the notebook that uses SB3?

I also found better hyper-parameters (the agent reaches 90% training success in 20 000 steps only) using TQC from the [contrib](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib) repo.

**Comment by eleurent** [comment]
Hi @araffin, yes I would, thank you very much!

I already started switching to SB3 in [a few](https://github.com/eleurent/highway-env/blob/master/scripts/stablebaselines_highway_cnn.py) [scripts](https://github.com/eleurent/highway-env/blob/master/scripts/stablebaselines_highway_attention_ppo.py), but let's make it official :)

**Comment by araffin** [comment]
I will do that (and probably will have to re-do it soon as the refactored version is almost ready: https://github.com/DLR-RM/stable-baselines3/pull/351).

It should work well with SAC too (with the new hyperparams), but best results are with TQC.

**Comment by hougiebear** [comment]
@araffin  super stuff. Waiting for the merge.

I've done some baseline experiments on HER with SB3 and Parking and Summon. I will be trying at somepoint to use SB3 benchmark for HER for all 4 algorithms (SAC,TD3,TQC & DDPG) for parking-v0 but if you have the params already done can you share them with me so I can re-run them soon?
![her-baseline](https://user-images.githubusercontent.com/22470422/116784673-7a115900-aa8d-11eb-9468-d49a111f7433.png)
![her2](https://user-images.githubusercontent.com/22470422/116784678-7e3d7680-aa8d-11eb-9917-89869c011215.png)

**Comment by araffin** [comment]
all hyperparameters are in the rl zoo: https://github.com/DLR-RM/rl-baselines3-zoo
(and i would recommend using it for doing experiments)

**Comment by hougiebear** [comment]
> all hyperparameters are in the rl zoo: https://github.com/DLR-RM/rl-baselines3-zoo
> (and i would recommend using it for doing experiments)
Yes thank you. I've been using your benchmark tool. It's pretty solid but haven't checked out from repo or updated in several months.
