### ISSUE TITLE
[Suggestion] Move jupyter to extra dependencies

### ISSUE THREAD

**Issue by araffin** [eleurent/highway-env#19]
Hello,
I'm currently trying to make a colab notebook to demonstrate how to use HER with the highway-env and I encountered issues because jupyter was part of the dependencies (and breaks colab installation).

Moving it to extra-requires would make more sense I think, as it is not directly used in the code.

The notebook: https://colab.research.google.com/drive/1VDD0uLi8wjUXIqAdLKiK15XaEe0z2FOc

**Comment by eleurent** [comment]
Yes I'll just remove the dependency altogether. I experimented a little bit with a notebook as documentation in the past, but nothing really serious.
I love your colab idea however! May I include it in the README.md when it's ready?

**Comment by araffin** [comment]
>May I include it in the README.md when it's ready?

Sure, it will be also featured in the stable-baselines documentation for the 2.6.0 release ;) (certainly this month)

**Comment by araffin** [comment]
@eleurent the colab notebook is cleaned and ready ;) (I did a small tweak to make it work with both dev version and future pip release)
