### ISSUE TITLE
Doubts about modifying allowed actions

### ISSUE THREAD

**Issue by sen-pai** [eleurent/highway-env#190]
I would like to have the vehicle move constantly and not provide an option to stop/ remain idle irrespective of what the agent provides as an action. 

For action type Discrete Meta-Actions how should I remove IDLE action from ACTIONS_ALL? do I re-map that action to another action? or is there a better way? 

For Continous Actions, if I'm not wrong, I need to modify the throttle/ acceleration value for the environment right?

**Comment by eleurent** [comment]
To be clear, the IDLE action corresponds to driving at constant speed in the current lane (as opposed to the change lane/speed actions), and not stopping.

If you want to remove this ability (i.e. force the agent to always change speed or lane), then yes simply removing the IDLE option from ACTIONS_ALL should work.
If you simply want to prevent the vehicle from stopping, you can set its minimum velocity MDPVehicle.SPEED_MIN to a high enough value.

The same will hold for continuous actions (except you can't really remove the (throttle=0, steering=0) action, if that is what you wanted)

**Comment by sen-pai** [comment]
Thanks a lot!
I misunderstood what IDLE action does.
MDPVehicle.SPEED_MIN is what I was really looking for.
