### ISSUE TITLE
SocialAttentionDQN fatal: destination path 'highway-env' already exists and is not an empty directory.

### ISSUE THREAD

**Issue by guzonghua** [eleurent/highway-env#194]
The first few times it goes well, but if you run it multiple times with "Run All", it gives an error in the first code cell:
"fatal: destination path 'highway-env' already exists and is not an empty directory."
Then subsequent training does not work, the agent does not learn. "Restart runtime" does not fix it. "Factory reset runtime" fixes it, and the agent can learn again.
Here is my notebook, I have set training num_episodes=1 to easily reproduce the problem.
https://colab.research.google.com/drive/1OBP8o9HjAgXUpgn87BAv6l_iv1DvleJo?usp=sharing

**Comment by eleurent** [comment]
This is because the script is attempting to clone the packages again, and directories already exist. I simply added `2> /dev/null` to the clone commands so that they fail silently.
