### ISSUE TITLE
ModuleNotFoundError: No module named 'baselines'

### ISSUE THREAD

**Issue by songanz** [eleurent/highway-env#20]
In folder "scripts" `baseline_run.py`, it says `import baselines.run`. But I found no baselines in your repo

**Comment by eleurent** [comment]
This module refers to https://github.com/openai/baselines
I should probably make it more obvious with a comment or extra dependencies.

**Comment by songanz** [comment]
> This module refers to https://github.com/openai/baselines
> I should probably make it more obvious with a comment or extra dependencies.

Thx~

**Comment by karbapi** [comment]
I am getting the following error:
  ModuleNotFoundError: No module named 'baselines'

I have Tensorflow 2.0.0 in my computer, with python 3.7.7. Could you please help?

**Comment by eleurent** [comment]
The baselines module is [this one](https://github.com/openai/baselines).
For tensorflow compatibility, see https://github.com/openai/baselines#tensorflow-versions

**Comment by ZohrehAlizadehm** [comment]
!pip install baselines
