### ISSUE TITLE
The problem in graphics.

### ISSUE THREAD

**Issue by EthanCodesss** [eleurent/highway-env#200]
https://github.com/eleurent/highway-env/blob/62b7f3f9ac8d17e4121d465601ed7dc828832c39/highway_env/envs/common/graphics.py#L70-L77
Hello! Thanks for your excellent work. But I have encountered a problem in use. The display of the vehicle trajectory seems that it doesn't work. 
When I debug, the console shows 'HighwayEnv' object has no attribute 'ACTIONS'. How should I do?

**Comment by eleurent** [comment]
Hi, thank you for the feedback, it should work now :)
