### ISSUE TITLE
In the Highway - v0 scenario, how do you make a green vehicle change lanes as shown in the previous demonstration

### ISSUE THREAD

**Issue by liuqi1998** [eleurent/highway-env#206]
In the Highway - v0 scenario, how do you make a green vehicle change lanes as shown in the previous demonstration

**Comment by eleurent** [comment]
By choosing the LANE_CHANGE_LEFT (0) or LANE_CHANGE_RIGHT (2) actions:

env = gym.make('highway-v0')
env.render()
env.act(0)  # to left lane
env.render()
env.act(1)  # idle, stay on current lane
env.render()
env.act(2)  # to right lane
env.render()

**Comment by liuqi1998** [comment]
I see this, but I also need to know how to make the green car automatically change lanes, like if I use the PPO reinforcement learning algorithm, where should I plug this algorithm in.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eleurent/highway-env"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月22日(星期二) 晚上10:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [eleurent/highway-env] In the Highway - v0 scenario, how do you make a green vehicle change lanes as shown in the previous demonstration (#206)





 
By choosing the LANE_CHANGE_LEFT (0) or LANE_CHANGE_RIGHT (2) actions:
 env = gym.make('highway-v0') env.render() env.act(0)  # to left lane env.render() env.act(1)  # idle, stay on current lane env.render() env.act(2)  # to right lane env.render()

**Comment by eleurent** [comment]
Well, the algorithm is responsible for choosing an action with respect to the current observation.
Something like:

```
env = gym.make('highway-v0')
obs = env.reset()
while True:
    action = <your RL algorithm>(obs)
    obs, reward, done, info = env.step(action)
    if done:
        obs = env.reset()
```
See e.g. openai gym for examples.

**Comment by liuqi1998** [comment]
OK. I understand this. And I also have a question: how to make green vehicles automatically change lanes? For example, I use PPO reinforcement learning algorithm, and how to call this reinforcement learning code in < Yout RL Algorithm >

**Comment by eleurent** [comment]
That depends on your implementation of PPO. It probably has a model/function that represents the policy, and takes an observation as input to output an action.

**Comment by liuqi1998** [comment]
OK, I'll take a look at the code of the PPO algorithm. If I don't understand, I'll ask you again. Thank you for your answer.

**Comment by eleurent** [comment]
You may take a look at the provided scripts and notebooks in https://github.com/eleurent/highway-env/tree/master/scripts
(includes a PPO example)
