### ISSUE TITLE
Wrapper for changing observations 

### ISSUE THREAD

**Issue by PhanindraParashar** [eleurent/highway-env#213]
How do we use the gym wrapper to override the history and change the default hostory of 30 to 100?

Also is it possible to have different behaviour for the other vehicles?

Like having different delta values for the IDM behaviour for different vehicles?

**Comment by eleurent** [comment]
> How do we use the gym wrapper to override the history and change the default hostory of 30 to 100?

I am not sure what history you are referring to?

> Also is it possible to have different behaviour for the other vehicles? Like having different delta values for the IDM behaviour for different vehicles?

It is not implemented right now, but it could easily be done by filling the `IDMVehicle.randomize_behaviour` method, and calling it after the vehicles are created in the environment reset.

**Comment by PhanindraParashar** [comment]
In the Class Vehicle in the file kinematics.py in highway_env

self.history = deque(maxlen=30)


We use this with env.road.vehicles[i].hostory to get history of the vehicle position in the past 30 period. 

How do we use the gym wrapper to get in history of vehicles position from the past 100 steps instead of 30.

**Comment by PhanindraParashar** [comment]
Also thanks for your previous quick response

**Comment by eleurent** [comment]
Ah I see!
I don't think this can be achieved by a wrapper.
The easiest would be to add a parameter to the environment configuration , rather than having this '30' value hardcoded.

**Comment by PhanindraParashar** [comment]
I used the fallowing code


env.configure(
{
'history' : deque(maxlen=50)
}
)

However when i check the history 
Only 30 steps are recorded.

Please let me know how to do it the right way.

**Comment by eleurent** [comment]
I made the history size a parameter, here is what you can do now:

```
import gym
import highway_env
from highway_env.vehicle.kinematics import Vehicle

Vehicle.HISTORY_SIZE = 100
env = gym.make('highway-v0')
env.config["show_trajectories"] = True
env.reset()

done = False
while not done:
    _, _, done, _ = env.step(1)
    print([len(v.history) for v in env.road.vehicles])
env.close()
```

**Comment by PhanindraParashar** [comment]
Thanks for the reply 

But still the history is 30 

I am not sure why this is happening

**Comment by eleurent** [comment]
To include the patch, you have to install the latest development version:
```
pip uninstall highway-env
pip install --user git+https://github.com/eleurent/highway-env
```

**Comment by PhanindraParashar** [comment]
Thanks 
Its working
