### ISSUE TITLE
How to modify the graphics of simulation 

### ISSUE THREAD

**Issue by PhanindraParashar** [eleurent/highway-env#214]
How to change the graphics of the simulation so that I can change color of vehicles, draw other objects on the vehicles or road (using it for trajectory forecasting)

**Comment by eleurent** [comment]
Hi @PhanindraParashar

The scene rendering is done here: https://github.com/eleurent/highway-env/blob/3857bb20d56b5c941270617db9ee281dbf6d4c92/highway_env/envs/common/graphics.py#L92

The road is drawn from https://github.com/eleurent/highway-env/blob/3857bb20d56b5c941270617db9ee281dbf6d4c92/highway_env/envs/common/graphics.py#L92

And vehicles from https://github.com/eleurent/highway-env/blob/3857bb20d56b5c941270617db9ee281dbf6d4c92/highway_env/vehicle/graphics.py#L17

You can freely edit this code to change/add the graphics of objects in the scene.
