### ISSUE TITLE
RunTimeWarning

### ISSUE THREAD

**Issue by PhanindraParashar** [eleurent/highway-env#215]
RunTimeWarning: invalid value encountered in power

1 - np.power(max(ego_vehicle.speed,0)/ego_target_speed, self.DELTA)

I am getting this error after few steps of simulation.

**Comment by PhanindraParashar** [comment]
Resolved

**Comment by PhanindraParashar** [comment]
import os
Os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'

**Comment by eleurent** [comment]
That is weird. Were you able to fix the runtime warning with by setting this environment variable?
