### ISSUE TITLE
Simulation of specific scenarios 

### ISSUE THREAD

**Issue by PhanindraParashar** [eleurent/highway-env#216]
How can we simulate specific scenarios? 

Eg:
Ego vehicle at (180,2) with initial speed of 25,
Vehicle 1 at (180,4) with initial speed 30 and heading .1?

Please let me know

**Comment by eleurent** [comment]
Hi,
You can edit the `_create_vehicles()` method of an existing environment in `highway_env/envs`, or create your own.
See [the docs](https://highway-env.readthedocs.io/en/latest/make_your_own.html) for more details.
