### ISSUE TITLE
def space(self) -> spaces.Space:error

### ISSUE THREAD

**Issue by wuyukun-tong** [eleurent/highway-env#228]
def space(self) -> spaces.Space:
AttributeError: module 'gym.spaces' has no attribute 'Space'
why

**Comment by eleurent** [comment]
I don't know, it should: https://github.com/openai/gym/blob/master/gym/spaces/space.py#L4

Do you have the latest version of gym installed?
Try:
`pip install gym --upgrade`

and

```
> from gym import spaces
> print(spaces.Space())
```
