### ISSUE TITLE
Q: The training uses relative information and is normalized. How to get the distance travelled, lateral displacement, absolute velocity, absolute heading angle of the main vehicle at each time

### ISSUE THREAD

**Issue by limeng-1234** [eleurent/highway-env#230]
Q: The training uses relative information and is normalized.
How to get the distance travelled, lateral displacement, absolute velocity, absolute heading angle of the main vehicle at each time

**Comment by eleurent** [comment]
Hi @limeng-1234 

> The training uses relative information and is normalized

This can be configured by two KinematicsObservation options:
```
absolute: False
normalize: True
```

>  How to get the distance travelled, lateral displacement, absolute velocity, absolute heading angle of the main vehicle at each time

If the `absolute` config is `True`, the first row of the observation will contain the x,y position, and vx,vy speed.
If the road is straight (e.g. highway), then the x coordinate is ~ distance travelled, and y~lateral displacement.
Heading angle can be added by adding `'heading'` to the `features` parameter. See all features here:     https://github.com/eleurent/highway-env/blob/a7b603fcd5d1560593a23fc4517b7ea3eedfc37f/highway_env/vehicle/kinematics.py#L206

And note that if absolute is False, the coordinates are relative only for other vehicles, while the first row (ego-vehicle) stays in absolute coordinates: 
https://github.com/eleurent/highway-env/blob/a7b603fcd5d1560593a23fc4517b7ea3eedfc37f/highway_env/envs/common/observation.py#L203
