### ISSUE TITLE
Automatic lane change

### ISSUE THREAD

**Issue by liuqi1998** [eleurent/highway-env#233]
How to realize automatic lane change in “highway-v0”?

**Comment by eleurent** [comment]
In many environments, a discrete action spaces allow you to change lane though the actions 0: left lane and 2: right lane.
To make it automatic, you need to train an agent to do so, see https://highway-env.readthedocs.io/en/latest/quickstart.html#training-an-agent

**Comment by liuqi1998** [comment]
So I need to download the latest "highway-env"&nbsp;environment, is it right?

**Comment by eleurent** [comment]
Yes

**Comment by liuqi1998** [comment]
There is a problem in the code of “training an agent”: the dqn package cannot be imported or installed. Which package needs to be installed to solve this problem?

**Comment by eleurent** [comment]
The line is `from stable_baselines3 import DQN`, so you should install https://github.com/DLR-RM/stable-baselines3

**Comment by liuqi1998** [comment]
And I input "pip install" what?

**Comment by eleurent** [comment]
Please kindly read the installation instructions in the page I mentioned.

**Comment by liuqi1998** [comment]
OK, I succeed. And my Python version is 3.6.8. When the sample code runs, two errors are reported, one is "ImportError: cannot import name 'MappingProxyType'" and the other is "ImportError: cannot import name 'wraps'". How to solve it?

**Comment by eleurent** [comment]
No idea, I have never this error before.
I don't know if it is related, but if you are on windows I recommend that you install python through Anaconda.

**Comment by liuqi1998** [comment]
I have tried, but it failed.

**Comment by eleurent** [comment]
Well, you can still run the online version: https://colab.research.google.com/github/eleurent/highway-env/blob/master/scripts/sb3_highway_dqn.ipynb

**Comment by liuqi1998** [comment]
This site is timeout in my computer. And I copy the code to my pycharm, the error is that:

**Comment by liuqi1998** [comment]
This site is timeout in my computer. And I copy the code to my pycharm, the error is that:


D:\Anaconda\python.exe D:/PycharmProjects/pythonProject2/test.py
Error processing line 1 of D:\Anaconda\lib\site-packages\google_auth-1.18.0-py3.8-nspkg.pth:


Fatal Python error: initsite: Failed to import the site module
Traceback (most recent call last):
&nbsp; File "D:\Anaconda\lib\site.py", line 168, in addpackage
&nbsp; &nbsp; exec(line)
&nbsp; File "<string&gt;", line 1, in <module&gt;
&nbsp; File "D:\PycharmProjects\pythonProject2\highway_env\types.py", line 1, in <module&gt;
&nbsp; &nbsp; from typing import Union, Sequence, Tuple, List
&nbsp; File "D:\Anaconda\lib\typing.py", line 28, in <module&gt;
&nbsp; &nbsp; import re as stdlib_re&nbsp; # Avoid confusion with the re we export.
&nbsp; File "D:\Anaconda\lib\re.py", line 122, in <module&gt;
&nbsp; &nbsp; import enum
&nbsp; File "D:\Anaconda\lib\enum.py", line 2, in <module&gt;
&nbsp; &nbsp; from types import MappingProxyType, DynamicClassAttribute
ImportError: cannot import name 'MappingProxyType' from 'types' (D:\PycharmProjects\pythonProject2\highway_env\types.py)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):
&nbsp; File "D:\Anaconda\lib\site.py", line 586, in <module&gt;
&nbsp; &nbsp; main()
&nbsp; File "D:\Anaconda\lib\site.py", line 573, in main
&nbsp; &nbsp; known_paths = addsitepackages(known_paths)
&nbsp; File "D:\Anaconda\lib\site.py", line 349, in addsitepackages
&nbsp; &nbsp; addsitedir(sitedir, known_paths)
&nbsp; File "D:\Anaconda\lib\site.py", line 207, in addsitedir
&nbsp; &nbsp; addpackage(sitedir, name, known_paths)
&nbsp; File "D:\Anaconda\lib\site.py", line 178, in addpackage
&nbsp; &nbsp; import traceback
&nbsp; File "D:\Anaconda\lib\traceback.py", line 5, in <module&gt;
&nbsp; &nbsp; import linecache
&nbsp; File "D:\Anaconda\lib\linecache.py", line 11, in <module&gt;
&nbsp; &nbsp; import tokenize
&nbsp; File "D:\Anaconda\lib\tokenize.py", line 33, in <module&gt;
&nbsp; &nbsp; import re
&nbsp; File "D:\Anaconda\lib\re.py", line 122, in <module&gt;
&nbsp; &nbsp; import enum
&nbsp; File "D:\Anaconda\lib\enum.py", line 2, in <module&gt;
&nbsp; &nbsp; from types import MappingProxyType, DynamicClassAttribute
&nbsp; File "D:\PycharmProjects\pythonProject2\highway_env\types.py", line 1, in <module&gt;
&nbsp; &nbsp; from typing import Union, Sequence, Tuple, List
&nbsp; File "D:\Anaconda\lib\typing.py", line 31, in <module&gt;
&nbsp; &nbsp; from types import WrapperDescriptorType, MethodWrapperType, MethodDescriptorType
ImportError: cannot import name 'WrapperDescriptorType' from 'types' (D:\PycharmProjects\pythonProject2\highway_env\types.py)


Process finished with exit code 1

**Comment by eleurent** [comment]
Interesting, thank you for sending the full error message!
Apparently, python is confused because I named a file "types.py". I will rename it and the problem should be fixed. I'll let you know when it is done.

**Comment by liuqi1998** [comment]
OK, thanks.

**Comment by eleurent** [comment]
It should now work.
Please, reinstall highway-env using the development version with:
```shell
pip uninstall highway-env
pip install --user git+https://github.com/eleurent/highway-env
```

**Comment by eleurent** [comment]
Or alternatively, if you cloned the project into PycharmProjects\pythonProject2 rather than installing it with pip, you can simply do a 
`git pull origin master`

**Comment by liuqi1998** [comment]
However, there are still mistakes, as follows:"gym.error.UnregisteredEnv: No registered env with id: highway-fast-v0".

**Comment by liuqi1998** [comment]
I know this error. And there is another error: "AttributeError: module 'tensorflow' has no attribute 'io'". How to solve it?

**Comment by eleurent** [comment]
> However, there are still mistakes, as follows:"gym.error.UnregisteredEnv: No registered env with id: highway-fast-v0".

This probably means highway-env is not up to date. Try
`import highway_env`
And
`print(highway_env.__version__)`

It should be at least v1.3. Otherwise, uninstall it and reinstall. 
Also, check that highway-env was imported in the beginning of the script.

**Comment by eleurent** [comment]
> I know this error. And there is another error: "AttributeError: module 'tensorflow' has no attribute 'io'". How to solve it?

You should probably install tensorflow separately.

**Comment by liuqi1998** [comment]
Is this a dead circle?&nbsp;And&nbsp;in the following&nbsp;DQN&nbsp;function, how to adjust the number of training times and the minimum number of training times?# Load and test saved model model = DQN.load("highway_dqn/model") while True:   done = False   obs = env.reset()   while not done:     action, _states = model.predict(obs, deterministic=True)     obs, reward, done, info = env.step(action)     env.render()env.close()env = gym.make("highway-fast-v0") model = DQN('MlpPolicy', env,               policy_kwargs=dict(net_arch=[256, 256]),               learning_rate=5e-4,               buffer_size=15000,               learning_starts=200,               batch_size=32,               gamma=0.8,               train_freq=1,               gradient_steps=1,               target_update_interval=50,               verbose=1,               tensorboard_log="highway_dqn/") model.learn(int(2e4)) model.save("highway_dqn/model")

**Comment by eleurent** [comment]
What do you mean "a dead circle"?
The number of training timesteps is the argument of `model.learn()`

**Comment by liuqi1998** [comment]
No statement to terminate the outer loop was seen.

**Comment by liuqi1998** [comment]
Which parameter is used to adjust the training times?

**Comment by eleurent** [comment]
> No statement to terminate the outer loop was seen.

I see, but what outer loop are you talking about?

> Which parameter is used to adjust the training times?

The training loop is started by the line
`model.learn(int(2e4))`

Here, 2e4 is the training duration, you can make it longer or shorter.

**Comment by liuqi1998** [comment]
The&nbsp;outer&nbsp;loop&nbsp;is “while&nbsp;True:”, and the inner loop is "while not done:".

**Comment by eleurent** [comment]
Oh okay!
- the purpose of these loops is to test the trained policy and generate videos of episodes.
- the outer loop is a loop over episodes, and it is infinite (we will generate videos until the script is manually interrupted)
- the inner loop is a loop over timesteps within an episode

But this is all happening **after** the training, which is inside `model.learn()`

Note that I have since updated the script, and the outer loop has been changed to a fixed number of episodes, instead of the infinite loop:

https://github.com/eleurent/highway-env/blob/97aabdc6b34b2b178ba5922beaf9e7e1206d8bcf/scripts/sb3_highway_dqn.py#L41

**Comment by liuqi1998** [comment]
OK. And what does the following three lines of code mean? Is it for updating the "env", where "env = gym.make("highway-fast-v0")"?


env = Monitor(env, directory="highway_dqn/videos", video_callable=lambda e: True) env.set_monitor(env) env.configure({"simulation_frequency": 15})  # Higher FPS for rendering

**Comment by eleurent** [comment]
`env = Monitor(env, directory="highway_dqn/videos", video_callable=lambda e: True)`

The Monitor wrapper allows to record videos and statistics of the env episodes.

```env.set_monitor(env)
env.configure({"simulation_frequency": 15})  # Higher FPS for rendering```

Both of these lines are optional, and used to have a higher video framerate

**Comment by liuqi1998** [comment]
Okay. And I have a question: what does the "centering_position" mean? In code, "centering_position" is "[0.3, 0.5]".

**Comment by eleurent** [comment]
It is the [horizontal, vertical] position of the vehicle in the rendering window. For example:
[0, 0] --> top-left
[0.5, 0.5] --> middle
[1, 1] --> bottom-right

**Comment by liuqi1998** [comment]
Okay. I understand it.
