### ISSUE TITLE
How to create an environment whihc is the same as the road structure in dataset, such as interaction?

### ISSUE THREAD

**Issue by Joe12138** [eleurent/highway-env#238]
For example, I have the road structure which is openstreetmap format (.osm) in the Interaction data set. Can I use this osm file to create an exactly same road environment as the real road environment by using this package simply? Because it need much time to create the same environment manually.

**Comment by eleurent** [comment]
Hi @Joe12138,
I agree that this would be an awesome feature to have, but it is missing at the moment.
This would require
- writing or using an existing .osm parser
- probably adding the possibility to handle arbitrary lane geometries (e.g. Bezier curves)

**Comment by Joe12138** [comment]
Thanks for your reply!
I'm doing this work. I don't think that we need to handle arbitrary lane geometries. Since in .osm file, any lane can be represented by many short straight lanes. But this is what I think and it may be wrong. 
Anyway, I can do this work and need to do this work for my research. But I have two trouble shown as below:
1. coordinate conversion mechanism as mentioned in issue #240 
2. some knowledge about .osm file format. Since I can parse node, short way and short lane (including short left and right way) from .osm file (Each short way only has some reference nodes.). Therefore, I don't know how to connect these short lanes to a complete lane. Anybody know these can help me to complete this work.
