### ISSUE TITLE
How to show planned trajectory?

### ISSUE THREAD

**Issue by Wasedarocket** [eleurent/highway-env#239]
Hi, Thanks for your excellent work. 
I want to know how to show planned trajectory like the gif 'An episode of one of the environments available in highway-env'. Should I set some configs? like setting 'show_trajectories' to show history trajectory. Or I need to call a class or some functions to show the planned trajectory?
Thank you very much.

**Comment by eleurent** [comment]
Hi @Wasedarocket,

Yes, this is kind of hidden. To do it, you need to call
```
list_of_planned_action = <your agent code...>
env.viewer.set_agent_action_sequence(list_of_planned_actions)
```

Note that the Env Viewer must have been created, which you can do by calling env.render().

**Comment by cisimon7** [comment]
Does the above only work for Discrete Action Space?

**Comment by eleurent** [comment]
No, it should work with continuous actions as well.

**Comment by cisimon7** [comment]
Any idea please why the error message below when I call your above code?
`AttributeError: 'Vehicle' object has no attribute 'predict_trajectory'`

It seems to me the ContinuousAction space only creates vehicle of types from `highway_env.vehicle.kinematics.Vehicle` or `highway_env.vehicle.dynamics.BicycleVehicle` depending on the config property `self.config["action"]["dynamical"]`. And these classes don't have attribute 'predict_trajectory', hence the error.

**Comment by eleurent** [comment]
Ah you're right, predict_trajectory is only implemented for ControlledVehicles for now (with speed and steering controllers embedded). But it should be even easier to add support for the simpler Vehicle class and continuous actions. Let me add that.

**Comment by cisimon7** [comment]
Thank you for the quick fix.
