### ISSUE TITLE
Multi-objective optimization

### ISSUE THREAD

**Issue by liuqi1998** [eleurent/highway-env#242]
Can this model solve the problem of multi-objective optimization while maintaining safety at high speed?

**Comment by eleurent** [comment]
Well, this project only describes the simulation environment, and not the agent / learning process.

It has been used in the context of multi-objective optimization, see e.g. https://budgeted-rl.github.io/
However, maintaining safety is typically only achieved at the price of the decreasing average speed, especially in the presence of uncertainty.

**Comment by liuqi1998** [comment]
I just tried to reproduce the code, but failed. The reason for the error is as follows: in the "rl-agents/trainer/evaluation.py" file, line 227, self.after_all_Episodes() prompts "typeerror: after_all_episodes() missing 1 required positive argument: 'duration'". How to solve it?

**Comment by liuqi1998** [comment]
How can collision be reduced by adjusting parameters? If yes, what parameters need to be adjusted?
