### ISSUE TITLE
Colab Session Crashes

### ISSUE THREAD

**Issue by nileshop22** [eleurent/highway-env#243]
Hi @eleurent, I was training using this [colab notebook](https://colab.research.google.com/github/eleurent/highway-env/blob/master/scripts/intersection_social_dqn.ipynb#scrollTo=QowKW3ix45ZW), and I noticed that whenever I try to make environment again by configs after stopping training the colab crashes. 

Here are the steps to reproduce:
1.  Run all the cells till this [one](https://colab.research.google.com/github/eleurent/highway-env/blob/master/scripts/intersection_social_dqn.ipynb#scrollTo=sFVq1gFz42Eg&line=1&uniqifier=1). After few episodes stop it. 
2. Then run [this](https://colab.research.google.com/github/eleurent/highway-env/blob/master/scripts/intersection_social_dqn.ipynb#scrollTo=QowKW3ix45ZW&line=9&uniqifier=1) cell again. You will notice that the colab crashes. 

Don't know why the links to the cell aren't working but the cell I'm talking in 1 is `evaluation.train()` and in 2 the cell above this.

I'm using similar code for my algorithm and it becomes too annoying when the colab crashes. I noticed this since, my network wasn't training well so I started the training again with new configs and it crashed.

**Comment by eleurent** [comment]
Hi @nileshop22 
I followed your instructions but could not really reproduce the issue. It may have been caused by some weird interaction between pygame and the fake display used for rendering. I pushed a change to disable some rendering, could you try again?
