### ISSUE TITLE
how to reduce the time for env.step(action)

### ISSUE THREAD

**Issue by LianhaoYin** [eleurent/highway-env#246]
Currently, it takes around 300ms for one env.step. Is it possible to reduce it to less than 30ms?

**Comment by eleurent** [comment]
Hi @LianhaoYin,

Here are a few ideas to make it faster: https://github.com/eleurent/highway-env/issues/223

See also: https://github.com/eleurent/highway-env/issues/36, https://github.com/eleurent/highway-env/issues/121
