### ISSUE TITLE
idle

### ISSUE THREAD

**Issue by piccupl** [eleurent/highway-env#247]
I don't understand action,'IDLE',
What happens when  perform this action？

**Comment by hiccup-luohao** [comment]
ego_vehicle = self.action_type.vehicle_class(road,
                                                     road.network.get_lane(("j", "k", 0)).position(110, 0),
                                                     speed=0)
the speed is 0， but this action will make the vehicle speed not zero

**Comment by eleurent** [comment]
The IDLE action keeps following the current lane at a constant velocity.

For your other question, see https://github.com/eleurent/highway-env/issues/248
