### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'io'

### ISSUE THREAD

**Issue by liuqi1998** [eleurent/highway-env#251]
I use the latest code of "highway_env", but it has the error, "AttributeError: module 'tensorflow' has no attribute 'io'". How to solve it? My version of tensorflow is 1.2.0.

**Comment by eleurent** [comment]
Hi @liuqi1998,
I don't think the issue is related to this project, since tensorflow is not used anywhere in this codebase.

**Comment by liuqi1998** [comment]
Oh, I understand it, but&nbsp;I&nbsp;cannot get the effect in the example picture. What's wrong?

**Comment by eleurent** [comment]
It may be caused by the use [tensorboardx](https://github.com/lanpa/tensorboardX) in the [rl-agents](https://github.com/eleurent/rl-agents) repository. You can try to reinstall it manually.

**Comment by liuqi1998** [comment]
OK. I will try it, and I also have a question in this, is 'tensorboard' equal to 'tensorboardx'?

**Comment by eleurent** [comment]
No, tensorboardx is a portage of tensorboard that is compatible with pytorch, while tensorboard only supports tensorflow

**Comment by liuqi1998** [comment]
OK, I understand it. Thank you for answering my question.

**Comment by liuqi1998** [comment]
Is there any sample code combined with this "highway_env" environment?&nbsp;I need to use this environment for my research.

**Comment by liuqi1998** [comment]
In my simulation experiment, automatic vehicles rarely change lanes, and there are 947 collisions in the 1000 times the experiment shows the effect. Is it related to my reward setting?

**Comment by eleurent** [comment]
> Is there any sample code combined with this "highway_env" environment?&nbsp;I need to use this environment for my research.

You can find sample scripts in notebook in the [scripts/](https://github.com/eleurent/highway-env/tree/master/scripts) directory.

> In my simulation experiment, automatic vehicles rarely change lanes, and there are 947 collisions in the 1000 times the experiment shows the effect. Is it related to my reward setting?

What environment are you using? Are the collisions caused by the agent or other vehicles?

**Comment by liuqi1998** [comment]
I use the “highway-fast-v0” environment. The collisions are caused by the agent. And most of the causes of the collision are caused by the simulated green car (agent) not changing lanes.

**Comment by eleurent** [comment]
Ah I see, this is related to you learning algorithm then, this repository only specifies the environment.
However, you should be able to reach pretty good performance for the highway-fast variant, certainly better that 947/1000 collisions. Is that statistic reported **after** the agent has trained? It is expected that you see a lot of collisions during training, but it should eventually converge to something better.
You may also want to try different types of observations.

**Comment by liuqi1998** [comment]
The last collision rate of 947 / 1000 is the collision rate after my training.
After I adjusted the collision reward, high-speed reward and lane change reward, the collision rate decreased to 42 / 1000.
