### ISSUE TITLE
Questions about parallelization, increasing timescale velocity, custom observations.

### ISSUE THREAD

**Issue by Andrealberti** [eleurent/highway-env#255]
Hi @eleurent, 

I'm here again and want to ask you some questions. As I wrote you, two, maybe three weeks ago, I'm building a custom parking environment. 
I have worked on this project with Unity (ML-agents) before starting with gym/highway-env, due to some aspects that makes it unsuitable for the continuation of my work. 
In ML-agents you could speed up a bit the training phase with the parallelization of the environments and speeding up the simulation time, defining the timescale as you wanted. I was wondering if even here you can do that, I didn't find much about this topic.

The last question is about the observation, basically I want to do a porting of the reward function (which is not the problem) and observations since I have achieved some good results, I want to use multiple observations, for example lidar or greyscale and add them some features to observe from the environment, have you tryed that yet?

Thanks in advance.
Regards,
Andrea

**Comment by eleurent** [comment]
Hi again @Andrealberti,
1. parallelization of the environments: I typically use multiple python processes, and each of them instantiates their own environment, using 1 CPU thread. The two common pipelines are:
  - each process is a full training job, and running several in parallel allows you to try different random seeds or hyperparameters
  - you have a separate training job, and an acting job consisting of several CPU workers
2. simulation time: you can configure the timescale using `env.configure(dict(simulation_frequency=simulation_frequency, policy_requency=policy_frequency))`. See some [explanations here](https://github.com/eleurent/highway-env/issues/130), and also some [suggestions here](https://github.com/eleurent/highway-env/issues/223).
3. last question about the observation: if I understand well, you want a stack of several observation as a new observation? I guess that could be implemented similarly to the MultiAgentObservation, by defining a new ObservationType that takes a list of observation configs, produces the corresponding observations, and returns them as a tuple. I'll propose a patch. And for the environment features, you can also add a separate EnvironmentObservation and add it to your observations list.

**Comment by Andrealberti** [comment]
Thanks for the answer @eleurent!

I'm still having some problems with the last one. Your TupleObservation was exactly what I was searching for, now I'm building a new class for the EnvironmentObservation. 
I'm trying to understand how the code works, I see that each of the RoadObjects has some features predefined in a dict. For example, if I want to add a new feature like the distance between ego-vehicle and the goal computed at each step, I have to do it in the kinematics.py file and then add a new feature to the dict, right? 
And in the case I want to add the target heading or position for example, how can I do it? 
For this last question I have seen a similar implementation in the KinematicsGoal class, I think it can be helpful.

Hope to have been clear enough.
Thanks again for your time.
Andrea

**Comment by eleurent** [comment]
Hi again Andrea!

> I see that each of the RoadObjects has some features predefined in a dict. For example, if I want to add a new feature like the distance between ego-vehicle and the goal computed at each step, I have to do it in the kinematics.py file and then add a new feature to the dict, right?

It is a possible way to do it, but it is not strictly necessary.

Basically, within an ObservationType you have access to the env object, so you can basically access any information that you want, and return it in the format that you want. For instance, you can iterate through `self.env.road.vehicles`, and compute the `ego_distance = np.linalg.norm(vehicle.position - self.env.position)` (or using `lane_distance_to`)

The rationale behind this idea of having features predefined in a dict in kinematics.py is that I wanted to have a configurable observation type, where you can easily select the vehicle features you want to observe without having to change the code. So you can add new vehicle features to the existing list (such as target heading or position), but maybe everything won't fit in that framework (e.g. distance to ego, which is arguably a feature of a pair of vehicles rather than one vehicle), in which case you can just add it manually in the observe() function.

Hope that was clear too ^^ let me know if you have any question :)

**Comment by Andrealberti** [comment]
Hi Edouard,

Thanks again for your answer! It was clear enough :)

I made my new observation class like this:  

    class EnvironmentObservation(KinematicObservation):
      def __init__(self, env: 'AbstractEnv', **kwargs: dict) -> None:
          super().__init__(env, **kwargs)
  
      def space(self) -> spaces.Space:
          try:
              obs = self.observe()
              return spaces.Dict(dict(
                  desired_goal=spaces.Box(-np.inf, np.inf, shape=obs["desired_goal"].shape, dtype=np.float64),
                  achieved_goal=spaces.Box(-np.inf, np.inf, shape=obs["achieved_goal"].shape, dtype=np.float64),
                  ego_distance=spaces.Box(-np.inf, np.inf, shape=obs["ego_distance"].shape, dtype=np.float64),
                  observation=spaces.Box(-np.inf, np.inf, shape=obs["observation"].shape, dtype=np.float64),
              ))
          except AttributeError:
              return spaces.Space()
  
      def observe(self) -> Dict[str, np.ndarray]:
          if not self.observer_vehicle:
              return {
              "observation": np.zeros((len(self.features),)),
              "achieved_goal": np.zeros((len(self.features),)),
              "desired_goal": np.zeros((len(self.features),)),
              "ego_distance": np.zeros((1,))
          }
  
          obs = np.ravel(pd.DataFrame.from_records([self.observer_vehicle.to_dict()])[self.features])
          goal = np.ravel(pd.DataFrame.from_records([self.env.goal.to_dict()])[self.features])
          vehicle_position = self.observer_vehicle.position
          target_position = self.env.goal.position
          distance = np.ravel(np.linalg.norm(vehicle_position-target_position))
          #print("distance", distance)
          obs = {
              "observation": obs,
              "achieved_goal": obs,
              "desired_goal": goal,
              "ego_distance": distance 
          }
          return obs   

Adding a new feature to the dict and it seems to be working good.

**Comment by Andrealberti** [comment]
A quick update.

When I try to train a new model with HER + TD3, the console throw this exception:

> Traceback (most recent call last):
>   File "/home/elios/Tesi_Alberti/trainingTest.py", line 39, in <module>
>     model.learn(int(2e6))
>   File "/home/elios/Tesi_Alberti/.venv/lib/python3.7/site-packages/stable_baselines/her/her.py", line 113, in learn
>     replay_wrapper=self.replay_wrapper)
>   File "/home/elios/Tesi_Alberti/.venv/lib/python3.7/site-packages/stable_baselines/td3/td3.py", line 349, in learn
>     self.replay_buffer_add(obs_, action, reward_, new_obs_, done, info)
>   File "/home/elios/Tesi_Alberti/.venv/lib/python3.7/site-packages/stable_baselines/common/base_class.py", line 1005, in replay_buffer_add
>     self.replay_buffer.add(obs_t, action, reward, obs_tp1, float(done), **kwargs)
>   File "/home/elios/Tesi_Alberti/.venv/lib/python3.7/site-packages/stable_baselines/her/replay_buffer.py", line 79, in add
>     self._store_episode()
>   File "/home/elios/Tesi_Alberti/.venv/lib/python3.7/site-packages/stable_baselines/her/replay_buffer.py", line 176, in _store_episode
>     reward = self.env.compute_reward(next_obs_dict['achieved_goal'], goal, info)
>   File "/home/elios/Tesi_Alberti/.venv/lib/python3.7/site-packages/stable_baselines/her/utils.py", line 97, in compute_reward
>     return self.env.compute_reward(achieved_goal, desired_goal, info)
>   File "/home/elios/Tesi_Alberti/.venv/lib/python3.7/site-packages/gym/core.py", line 209, in compute_reward
>     raise NotImplementedError
> NotImplementedError

This other with TD3:

> 
> Traceback (most recent call last):
>   File "/home/elios/Tesi_Alberti/trainingTest.py", line 34, in <module>
>     tensorboard_log="./TensorBoardLogs/parking_HER_TD3")
>   File "/home/elios/Tesi_Alberti/.venv/lib/python3.7/site-packages/stable_baselines/td3/td3.py", line 114, in __init__
>     self.setup_model()
>   File "/home/elios/Tesi_Alberti/.venv/lib/python3.7/site-packages/stable_baselines/td3/td3.py", line 134, in setup_model
>     **self.policy_kwargs)
>   File "/home/elios/Tesi_Alberti/.venv/lib/python3.7/site-packages/stable_baselines/td3/policies.py", line 217, in __init__
>     feature_extraction="mlp", **_kwargs)
>   File "/home/elios/Tesi_Alberti/.venv/lib/python3.7/site-packages/stable_baselines/td3/policies.py", line 100, in __init__
>     reuse=reuse, scale=(feature_extraction == "cnn"))
>   File "/home/elios/Tesi_Alberti/.venv/lib/python3.7/site-packages/stable_baselines/td3/policies.py", line 23, in __init__
>     super(TD3Policy, self).__init__(sess, ob_space, ac_space, n_env, n_steps, n_batch, reuse=reuse, scale=scale)
>   File "/home/elios/Tesi_Alberti/.venv/lib/python3.7/site-packages/stable_baselines/common/policies.py", line 118, in __init__
>     self._obs_ph, self._processed_obs = observation_input(ob_space, n_batch, scale=scale)
>   File "/home/elios/Tesi_Alberti/.venv/lib/python3.7/site-packages/stable_baselines/common/input.py", line 51, in observation_input
>     type(ob_space).__name__))
> NotImplementedError: Error: the model does not support input space of type Dict

that was not the right way to implement my custom observations.

**Comment by eleurent** [comment]
If you really want to use HER, I think you have to include the entire observation as part of the 'observation' field, which means you have to concatenate both tensors.

Something like:
```
      [...]
      achieved = np.ravel(pd.DataFrame.from_records([self.observer_vehicle.to_dict()])[self.features])
      goal = np.ravel(pd.DataFrame.from_records([self.env.goal.to_dict()])[self.features])
      vehicle_position = self.observer_vehicle.position
      target_position = self.env.goal.position
      distance = np.ravel(np.linalg.norm(vehicle_position-target_position))
      observation = np.concatenate((achieved, distance))     

      obs = {
          "observation": observation,
          "achieved_goal": achieved,
          "desired_goal": goal,
          "ego_distance": distance 
      }
      return obs
```

Also, the error that you get is that your environment is missing a `compute_reward` function, that HER uses to compute the reward of  imagined transitions. See e.g. this line: https://github.com/eleurent/highway-env/blob/9d63973da854584fe51b00ccee7b24b1bf031418/highway_env/envs/parking_env.py#L118


However, this dict observation type with the fields `observation`, `achieved_goal` and `achieved_goal` is very specifi to HER, which is why TD3 probably does not support it. If you want to use TD3 directly, you should use a different kind of Observation type that directly provide your observation as a tensor, or maybe as a Tuple of tensors (I think it is supported)

**Comment by Andrealberti** [comment]
Yes, I did exactly this:

> If you want to use TD3 directly, you should use a different kind of Observation type that directly provide your observation as a tensor, or maybe as a Tuple of tensors (I think it is supported)

with tensor you mean spaces.Box type, right?
But unfortunately seems that Tuples are not supported too in TD3...

**Comment by Andrealberti** [comment]
This is the exception: 

      Traceback (most recent call last):
      File "/home/elios/Tesi_Alberti/trainingTest.py", line 35, in <module>
        tensorboard_log="./TensorBoardLogs/parking_multiobs_TD3")
      File "/home/elios/Tesi_Alberti/.venv/lib/python3.7/site-packages/stable_baselines3/td3/td3.py", line 122, in __init__
        self._setup_model()
      File "/home/elios/Tesi_Alberti/.venv/lib/python3.7/site-packages/stable_baselines3/td3/td3.py", line 125, in _setup_model
        super(TD3, self)._setup_model()
      File "/home/elios/Tesi_Alberti/.venv/lib/python3.7/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 218, in _setup_model
        **self.replay_buffer_kwargs,
      File "/home/elios/Tesi_Alberti/.venv/lib/python3.7/site-packages/stable_baselines3/common/buffers.py", line 182, in __init__
        super(ReplayBuffer, self).__init__(buffer_size, observation_space, action_space, device, n_envs=n_envs)
      File "/home/elios/Tesi_Alberti/.venv/lib/python3.7/site-packages/stable_baselines3/common/buffers.py", line 49, in __init__
        self.obs_shape = get_obs_shape(observation_space)
      File "/home/elios/Tesi_Alberti/.venv/lib/python3.7/site-packages/stable_baselines3/common/preprocessing.py", line 158, in get_obs_shape
        raise NotImplementedError(f"{observation_space} observation space is not supported")
    NotImplementedError: Tuple(Box([-inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf], [inf inf inf inf inf inf inf inf inf inf inf inf inf], (13,), float64), Box([[-1. -1.]
     [-1. -1.]
     [-1. -1.]
     [-1. -1.]
     [-1. -1.]
     [-1. -1.]
     [-1. -1.]
     [-1. -1.]
     [-1. -1.]
     [-1. -1.]
     [-1. -1.]
     [-1. -1.]
     [-1. -1.]
     [-1. -1.]
     [-1. -1.]
     [-1. -1.]], [[1. 1.]
     [1. 1.]
     [1. 1.]
     [1. 1.]
     [1. 1.]
     [1. 1.]
     [1. 1.]
     [1. 1.]
     [1. 1.]
     [1. 1.]
     [1. 1.]
     [1. 1.]
     [1. 1.]
     [1. 1.]
     [1. 1.]
     [1. 1.]], (16, 2), float32)) observation space is not supported

**Comment by eleurent** [comment]
Yes, I meant spaces.Box. Well, if is the only observation type handled by TD3, you will have to provide one, you could e.g. simply flatten and concatenate all your observation features (including distance), as well as the goal location etc. into a single vector.

**Comment by eleurent** [comment]
Actually, the stable baseline3 docs state that TD3 [supports Dict observations](https://stable-baselines3.readthedocs.io/en/master/modules/td3.html?highlight=spaces#can-i-use), so I guess you could just replace the Tuple by a Dict.

**Comment by Andrealberti** [comment]
Thanks again for your time, Dict is working well. 
I had another problem, just to inform you about that. In stable-baselines3 (precisly stable-baselines3/stable_baselines3/common/monitor.py line 96) they do a round() approximation which gave me an error with numpy array. 
Fixed it replacing round with np.round(). 

Then, I have to ask you another question. Like I said before, I'm trying to use Lidar sensor. This is what I saw the first time I used it in my env:

![LidarOriginal](https://user-images.githubusercontent.com/22549382/150645242-ec78ed5a-8bf3-4312-a58f-5f34242ba117.PNG)

changing the cells parameter in 360, this is what I obtain:

![Lidar360°](https://user-images.githubusercontent.com/22549382/150645482-0ccf64ac-c54f-46fe-ad42-f1d3bd3a0786.PNG)
 
It seems to be quite buggy. in this last image as you can see with a 360° resolution, the sensor only sees the center of each object on the road.

**Comment by eleurent** [comment]
Hi @Andrealberti,
Well, the observation is not really buggy, it is by design ^^

Basically, to simplify the ray tracing code, I approximated every object in the scene by a circle of radius WIDTH. It worked sufficiently well for my use case (just a few vehicles on the highway, with coarse angular sectors), but of course it is not accurate enough in your environment where you have thin obstacles and a finer angular partition.

The easiest temporary fix could be to replace the circle of radius WIDTH by a rotated ellipse with WIDTH and HEIGHT, which should represent much better your thin obstacles, while barely changing the line-circle intersection code (ellipse being a slightly generalized circle).

Of course, the proper solution would be to use the proper model of line to rectangle intersection, and I believe we already have the necessary code for that: https://github.com/eleurent/highway-env/blob/9d63973da854584fe51b00ccee7b24b1bf031418/highway_env/utils.py#L151

I'll try to write a fix soon.

**Comment by Andrealberti** [comment]
Oh

**Comment by Andrealberti** [comment]
Hi @eleurent,

Thanks again and again for your quick response, and sorry if I am so stressful 🙄.

Well, I had to imagine that, everything here makes sense now, btw my colleagues told me that and I didn't care about them.

I'll try to fix it next week, maybe I'll give you an update.

Thanks.
Have a great weekend,
Andrea

**Comment by eleurent** [comment]
No worries Andrea!
I had a few spare minutes and I implemented the proper line-rect intersection, things should look better for you now:
![image](https://user-images.githubusercontent.com/1706935/150653637-837fe10e-7d2d-4fbb-9af4-4c1127cbb0f6.png)

**Comment by eleurent** [comment]
Also works with non-square geometries: 
![image](https://user-images.githubusercontent.com/1706935/150653737-e5d574a5-2efb-4a93-8240-ec60fe81339c.png)

**Comment by Andrealberti** [comment]
Thank you so much for what you did Edouard! And thanks for your time! Now I think I'm ready test my env.

**Comment by eleurent** [comment]
Your environment actually looks very nice, would you mind sharing it with a PR once it’s ready?

**Comment by eleurent** [comment]
Side note: maybe the goal landmarks shouldn’t be considered as collidable by the LiDAR observation. I’ll fix this.

**Comment by Andrealberti** [comment]
> Your environment actually looks very nice, would you mind sharing it with a PR once it’s ready?

Of course! 


> Side note: maybe the goal landmarks shouldn’t be considered as collidable by the LiDAR observation. I’ll fix this.

This was already in my TO DO list 😉
Thanks btw!

**Comment by Andrealberti** [comment]
Hi @eleurent,
I added these two lines

    if obstacle is self.env.goal:
    continue

now it is working as I want.
