### ISSUE TITLE
some questions about "intersection-v0"

### ISSUE THREAD

**Issue by ssexuejinwei** [eleurent/highway-env#258]
Hi, @eleurent 
Thanks for creating this easy to use environment for intersection tasks.
I wanted to use this environment for multi agent learning with continuous action, there are some questions:

1. when I use this config:
    `"action": {
            "type": "MultiAgentAction",
            "action_config": {
                "type": "ContinuousAction",
                "longitudinal": True,  # 
                "lateral": True  # 
            }
        }`
the ego-vehicles will not driving along the line. So to ensure the vehicle moving along the line , i set the "lateral" to False,  but the ego-vehicles can only go straight.
I just want to ask the question that how to set up the vehicle so that it follows the road and the movement space is continuous?

2. I just see a configuration is " 'observe_intentions‘ " in default configuration for intersection, but I don't know what it is for and it is not used in the source code.
![微信截图_20220110201311](https://user-images.githubusercontent.com/27001411/148764309-74237da4-16f2-44a9-a85b-cc2e76625b8b.png)

**Comment by ssexuejinwei** [comment]
Oh, I found the "observe_intentions" in "highway_env/envs/common/observation.py", but I still want to know, if I set this to "true", why do not the coordinates of the destination appear in the features?

**Comment by eleurent** [comment]
Hi @ssexuejinwei 
It seems you have found answers to your questions, but I'm still replying in case this is useful to anyone.

1. It is not possible at the moment, but an action type can be added/modified to add this ability. The lane-following behaviour can be found in DiscreteMetaAction, and the continuous acceleration control in ContinuousAction, so it is just a matter of merging the two.
2. As you found out, observe_intentions enable the computation of the intended destination of each observed vehicle (if they have a planned route). When enabled, the `cos_d, sin_d` fields also have to be added to the observation's list of `features`.

**Comment by ssexuejinwei** [comment]
Your answer allowed me to verify that I was correct. For the two questions, and I have changed the source code to make it more usable in this way.

Thank you very much for providing such a good simulation library.

**Comment by huang6668** [comment]
> Your answer allowed me to verify that I was correct. For the two questions, and I have changed the source code to make it more usable in this way.
> 
> Thank you very much for providing such a good simulation library.

您好，请问您后续是否成功将intersection里的离散动作改成了连续动作了吗，能否教我一下怎么修改

**Comment by eleurent** [comment]
Here are the docs, let me know if you have any question: http://highway-env.farama.org/actions/

**Comment by huang6668** [comment]
> Here are the docs, let me know if you have any question: http://highway-env.farama.org/actions/

Thank you for your reply. My current question is that if I set the Action to Continues, the egocar cannot reach the destination according to the specified route and will wander around in the map

**Comment by eleurent** [comment]
Yes the route is only used by high-level controllers, if you're doing continuous control where your agent sets the acceleration and steering, then the agent is in charge of following a path / reaching a destination. For exemple, see the parking env or the racetrack env.

**Comment by huang6668** [comment]
I referred to the racetrack env and want to complete the task of following a path/reaching a destination. Is it achieved by modifying the Reward function?

**Comment by eleurent** [comment]
Yes, that sounds about right.

You can check out the current reward for the racetrack env, which has a term for not driving offroad (a bit similar to following a path), and the parking env, whose reward has a term for getting closer to the goal location.

Also dont forget that the observation should also include information about the path / destination.

**Comment by huang6668** [comment]
Thanks!
