### ISSUE TITLE
reward on RoundaboutEnv

### ISSUE THREAD

**Issue by tingtingLiuLiu** [eleurent/highway-env#270]
Hi, bother you !Training a dqn agent in a Roundabout environment, I'm wondering if the wait time when the ego_vehicle enters and how to get out of the roundabout is taken into account (can you show the location in highway_env code)? In addition, I would like to ask that  in order for the agent to learn to collide, do you add some penalties to the reward of the code (considering it as a collision and giving a negative reward)? Thank you in advance.

**Comment by eleurent** [comment]
Hi, sorry for the late reply,

The route that the ego-vehicle takes is pre-defined here:

https://github.com/eleurent/highway-env/blob/19770b9e2a4a4e740b1aec6680d14d36fd4da3c2/highway_env/envs/roundabout_env.py#L141

The reward function is defined here:

https://github.com/eleurent/highway-env/blob/19770b9e2a4a4e740b1aec6680d14d36fd4da3c2/highway_env/envs/roundabout_env.py#L40

As you can see, it already contains a collision penalty term (of -1).
