### ISSUE TITLE
Intersection training issues in the environment

### ISSUE THREAD

**Issue by wuyukun-tong** [eleurent/highway-env#271]
When I use the DDPG algorithm to train an intelligent body in an intersection environment why does the vehicle always go off the road and out of the environment?

**Comment by eleurent** [comment]
Indeed, there was no reward/penalty associated with driving offroad.
I changed the reward function such that the reward is now 0. You can also enable the `"offroad_terminal"` config such that leaving the road is considered a terminal state.
