### ISSUE TITLE
How to set up the start and end points of ego-vehicles in the intersection env

### ISSUE THREAD

**Issue by wuyukun-tong** [eleurent/highway-env#274]
How to set up the start and end points of ego-vehicles in the  intersection environment？

**Comment by eleurent** [comment]
Hi,
Only the destination is configurable for now, with the `"destination"` environment config, which you can set to one of ["o0", "o1", "o2", "o3"], see the description here:

 https://github.com/eleurent/highway-env/blob/049888adea0537b8e2d1d52aa0ae5b5722610629/highway_env/envs/intersection_env.py#L121

For the start location so you would have to clone the project and edit the source code. It is define as follows: 

* we select a road segment (see the create_road method for how these are defined) here

https://github.com/eleurent/highway-env/blob/049888adea0537b8e2d1d52aa0ae5b5722610629/highway_env/envs/intersection_env.py#L192

* and then a position along this road segment there:

https://github.com/eleurent/highway-env/blob/049888adea0537b8e2d1d52aa0ae5b5722610629/highway_env/envs/intersection_env.py#L196
