### ISSUE TITLE
environment

### ISSUE THREAD

**Issue by HUXIAOWANG513** [eleurent/highway-env#276]
What environment is needed to run the code in scripts? Like gym and SB3?

**Comment by eleurent** [comment]
There has been some recent changes in the last gym versions broke a few things, and repos like this one or SB3 are still adjusting. However
I got it to work with the following configuration:
- python 3.7 or 3.8
- highway-env==1.5 (which I just released, or the development version. Supports gym>=0.21)
- stable-baseline 3 current development version (pip install git+https://github.com/DLR-RM/stable-baselines3)
- gym 0.21 (the latest gym version supported by current stable_baselines dev branch)

**Comment by HUXIAOWANG513** [comment]
Thank you very much for your contribution
