### ISSUE TITLE
How to get the front and rear vehicles of ego-vehicle ?

### ISSUE THREAD

**Issue by tingtingLiuLiu** [eleurent/highway-env#282]
How to get the front and rear vehicles of ego-vehicle  if they are in different lanes of the road  in roundabout env?
For example, the ego vehicle is on a straight lane, and the preceding vehicle is on a connected circular lane.I called your neighbor_vehicles(), but the results are inconsistent when verified in simulation, I'm a little confused
So,thanks for your reply.

**Comment by eleurent** [comment]
Hi,
This is a tricky question whenever we are dealing with a road network more complicated than a straight road (topogically).
For example, if two lanes are merging into the ego-vehicle lane, how should we define the following vehicle? Is it V1 or V2? Similarly, if the ego-vehicle's lane is splitting in two, which vehicle is the preceding one, V3 or V4?
```
V1 --          -- V3
      \      /
       --EV--         
      /      \ 
V2 --          -- V4
```

I chose the simple heuristic to project every vehicle on the current vehicle lane and pick the closest, and it works fine most of the time but can easily fail in more complex situations.
If you have any better idea I'm happy to hear your suggestions.

**Comment by tingtingLiuLiu** [comment]
I am very happy to receive your reply!
Can you elaborate on how to project each vehicle onto the ego_vehicle's lane?
