### ISSUE TITLE
Question about DiscreteMetaAction

### ISSUE THREAD

**Issue by tingtingLiuLiu** [eleurent/highway-env#283]
DiscreteMetaAction [0:lane_left  3 :lane_right]
I understand that these two actions are selected to change lanes, but in the simulation results, is this not the case? I am confused. Does selecting these two actions cause a little change in the left and right angles of the vehicle?

**Comment by eleurent** [comment]
Indeed, these actions should result in a complete change of lane, but that only applies to multi-lane roads.
To freely control the steering wheel, the ContinuousAction or DiscreteAction should be used instead.

**Comment by tingtingLiuLiu** [comment]
Thank you very much for your help.
