### ISSUE TITLE
How to check the state is "terminal" or not?

### ISSUE THREAD

**Issue by BaniLiu** [eleurent/highway-env#285]
Hi, thanks for your work.@eleurent
 
I just trained a SB3 DQN agent in a highway-v0 environment,  and when I test it, I found that in some episodes, the ego vehicle didn't collide and follow the front vehicle for a while, but then it also turned into a new episode.

I guess it may have relationship with the "done" getting from the "env.step(action)". And I found that there is a function "_is_terminal" which "checking whether the current state is a terminal state" in the source code. But I don't understand how to check it? I can't find enough information about it, while I already knew that a collision will lead to the terminal.

I want to make the ego vehicle driving longer, instead of ending the episode so fast, could you please give me some advice?

The following is my code:
```
import gym
import highway_env
from stable_baselines3 import DQN
import matplotlib.pyplot as plt
import numpy as np
import pprint

env = gym.make("highway-v0") 
model = DQN('MlpPolicy', env,
            policy_kwargs=dict(net_arch=[256, 256]),  
            learning_rate=5e-4,     
            buffer_size=15000,     
            learning_starts=200,    
            batch_size=32,          
            gamma=0.8,              
            train_freq=1,           
            gradient_steps=1,      
            target_update_interval=50,  
            verbose=1               
            )
# tensorboard_log="highway_dqn/"

model.learn(int(2e3))               
model.save("sb_dqn/model")

# Load and test saved model

model = DQN.load("sb_dqn/model")
rewards = []

for _ in range(500):
    done = False
    obs = env.reset()
    episode_reward = 0

    while not done:
        action, _states = model.predict(obs, deterministic=True)  
        obs, reward, done, info = env.step(action)
        env.render()
```

**Comment by eleurent** [comment]
> I guess it may have relationship with the "done" getting from the "env.step(action)". And I found that there is a function "_is_terminal" which "checking whether the current state is a terminal state" in the source code. But I don't understand how to check it? I can't find enough information about it, while I already knew that a collision will lead to the terminal.

Yes exactly, in addition to collisions, the episodes have a fixed `duration`, after which any state is set as terminal.

https://github.com/eleurent/highway-env/blob/4f6d837543cbcaf97037c5236f849c0aea56e391/highway_env/envs/highway_env.py#L106

https://github.com/eleurent/highway-env/blob/master/highway_env/envs/highway_env.py#L35

You can increase this maximum duration with e.g.

```
env.configure({"duration": 120})
```

But note that the other vehicles in the scene are only spawned once in the beginning, so after the agent has passed them it will be alone on the road. Moving from the episodic setting to a non-episodic one would require changing this, and spawning new vehicles in front of the ego-vehicle / destroying those that are too far away.

**Comment by BaniLiu** [comment]
Thanks a lot
