### ISSUE TITLE
Why ep_mean_reward and EP_mean_len in the environment training of the highway- DQN-CNN are NAN

### ISSUE THREAD

**Issue by HUXIAOWANG513** [eleurent/highway-env#289]
Thanks for the code, but when I was training DQN in the CNN environment I found some cases where the value was NAN..why ep_mean_reward and ep_mean_len in the environment training of the highway- DQN-CNN are NAN.

**Comment by eleurent** [comment]
This is not supposed to happen. One possible explanation is that your model maybe output a NaN at some point, and that NaN got propagated in the actions, then in the vehicle state (acceleration, speed, position), and finally in the reward function.
Unless you can reproduce it, it is hard to tell whether this is a simulator bug.

**Comment by HUXIAOWANG513** [comment]
Thank you for your answer。But I found this situation when I was running the model in ' \highway-env-master\scripts\sb3_highway_dqn_cnn.py', and I printed self.ep_info_buffer and the result was 'deque([], maxlen=100)'. Do you know what might cause this?

**Comment by eleurent** [comment]
This code (self.ep_info_buffer) is part of StableBaselines3 (the agents), not this project (the environment).
Moreover, this result is not an error, it only means that the episode info is stored in a queue of length 100.

**Comment by HUXIAOWANG513** [comment]
Thank you very much for your patient reply

**Comment by fafar105** [comment]
How to I get the agent to drive like on the Getting Started page, I used the same code and trained for around 100k steps. And still my agent oftens crashes after a very short time amount.
