### ISSUE TITLE
Maximum speed for continuous action

### ISSUE THREAD

**Issue by zsbeta** [eleurent/highway-env#290]
I tried to train a model that is capable of reaching a speed of 40 onwards in a continuous highway environment. The reward function is modified, such that:
     "high_speed_reward": 1,
    "reward_speed_range": [40, 50],
And the action defined as:
"action": {
                "type": "ContinuousAction",
                "steering_range": [-0.1, 0.1]  
            }
In order to encourage that speed, I set the initial speed to 40 manually at the first iteration in order to encourage the exploration. However, the agent does not seem to reach that speed ever. I wonder whether there is actually some speed limit in the simulator?

**Comment by eleurent** [comment]
Yes there is a maximum speed defined here:

https://github.com/eleurent/highway-env/blob/19770b9e2a4a4e740b1aec6680d14d36fd4da3c2/highway_env/vehicle/kinematics.py#L27

But keep in mind that the default kinematics model relies on a no-slippage assumption which is not realistic at high speeds. If you want to do drift control you can use a dynamics Model instead

https://github.com/eleurent/highway-env/blob/19770b9e2a4a4e740b1aec6680d14d36fd4da3c2/highway_env/vehicle/dynamics.py#L11

but you will have to set/tune the tire friction coefficients. I think an air friction term is also probably missing from the model, which would be needed at high speed.

**Comment by zsbeta** [comment]
Thanks! That makes a lot sense.
