### ISSUE TITLE
Monitor is not called in dqn_cnn.py

### ISSUE THREAD

**Issue by HUXIAOWANG513** [eleurent/highway-env#291]
I'm sorry to bother you again. As for the problem that reward value was nan last time, after investigating these days,  I found that it was because monitor was not called at all in dqn_cnn.py.  I wonder if it's because of my environment or something else?

**Comment by eleurent** [comment]
Do you mean in sb3_highway_dqn_cnn.py?
There shouldn't be any more call to Monitor, since it has been removed from the latest versions of gym, replaced by separate wrappers to record statistics and videos.
Maybe you should upgrade gym and highway-env?

**Comment by HUXIAOWANG513** [comment]
Thanks a lot。
