### ISSUE TITLE
SAC

### ISSUE THREAD

**Issue by liuqi1998** [eleurent/highway-env#292]
How to apply SAC algorithm in this environment? I called the sac algorithm, but reported the following error: “assertionerror: the algorithm only supports < class' gym spaces. box. Box'> as action spaces but Discrete(5) was provided”. What is the reason?

**Comment by eleurent** [comment]
The reason is that SAC only handles continuous actions, and highway-env uses discrete actions by default.
To configure it to use continuous actions, see [the docs](https://highway-env.readthedocs.io/en/latest/actions/index.html#id1).
