### ISSUE TITLE
How to implement the IDM+Mobil model

### ISSUE THREAD

**Issue by yfxcore** [eleurent/highway-env#295]
Dear Eleurent,
I may want to know how I can implement the IDM+Mobil control model on the ego_vehicle, is there any command to do so? Thanks in advance.

**Comment by eleurent** [comment]
Hi,
I am not sure I follow your question, IDM+Mobil is already implemented but it is rather for other simulated vehicles in the scene. The ego-vehicle is typically controlled by the agent, so if it follows the IDM and MOBIL there are no decisions/actions left to take, it is already fully controlled. 

But I guess that if you really want to do so, you could remove the ego-vehicle from the scene altogether, and simply simulate the other vehicles.

**Comment by yfxcore** [comment]
Hi Eleurent，
Thanks for the reply. Just need it as a base to compare with agent performance, so I still need to remain the ego car to collect the speed and position information. It’s like using the ego car to act as an ‘other vehicle’, and produce the running data. How can I make this? Hope I had a clear explanation and Thank you for your advice~

**Comment by yfxcore** [comment]
> Hi, I am not sure I follow your question, IDM+Mobil is already implemented but it is rather for other simulated vehicles in the scene. The ego-vehicle is typically controlled by the agent, so if it follows the IDM and MOBIL there are no decisions/actions left to take, it is already fully controlled.
> 
> But I guess that if you really want to do so, you could remove the ego-vehicle from the scene altogether, and simply simulate the other vehicles.

Hi Eleurent，
Thanks for the reply. Just need it as a base to compare with agent performance, so I still need to remain the ego car to collect the speed and position information. It’s like using the ego car to act as an ‘other vehicle’, and produce the running data. How can I make this? Hope I had a clear explanation and Thank you for your advice~

**Comment by eleurent** [comment]
I see. Then you can do the following: 

1. edit this line, and replace `MDPVehicle` by `IDMVehicle` (you need to import it from highway_env/vehicle/behavior.py)

https://github.com/eleurent/highway-env/blob/abd837f239cf0c396d47d21456505b8d5b7dd550/highway_env/envs/common/action.py#L225

2. in act(), comment out the line and replace it by `pass`

https://github.com/eleurent/highway-env/blob/abd837f239cf0c396d47d21456505b8d5b7dd550/highway_env/envs/common/action.py#L228

**Comment by yfxcore** [comment]
Thanks a lot, it works well. 
By the way, I find the IDM control method is running at 1Hz as default, while the vehicle is simulated at 15Hz, if I understand correctly. Can it run at 15Hz as well, in order to output control command at each timestep as a continuous control?


> I see. Then you can do the following:
> 
> 1. edit this line, and replace `MDPVehicle` by `IDMVehicle` (you need to import it from highway_env/vehicle/behavior.py)
> 
> https://github.com/eleurent/highway-env/blob/abd837f239cf0c396d47d21456505b8d5b7dd550/highway_env/envs/common/action.py#L225
> 
> 2. in act(), comment out the line and replace it by `pass`
> 
> https://github.com/eleurent/highway-env/blob/abd837f239cf0c396d47d21456505b8d5b7dd550/highway_env/envs/common/action.py#L228

**Comment by eleurent** [comment]
No, actually the IDM is not really considered as a policy action, so it will be executed at the simulation frequency, so 15Hz as well.

**Comment by yfxcore** [comment]
Hi, I also tried to use it on the ContinuousAction mode, and tried to take IDM directly without modifying your original code,  but I didn't make it. Could you please check where is the problem? Below is my trial, where I want to make the Longitudinal and lateral control:

import gym
import numpy as np
import highway_env
import pprint
from highway_env import utils
from highway_env.vehicle.behavior import IDMVehicle

env = gym.make('highway-v0')
env.configure({
    "action": {
        "type": "ContinuousAction"
    },
})
env.reset()
max_frames  = 200
frame_idx   = 0
while frame_idx < max_frames:
    state = env.reset()  
    for step in range(512):
        env.render()
        action = [0, 0]
        front_vehicle, rear_vehicle = env.road.neighbour_vehicles(env.vehicle, env.vehicle.lane_index)

        #try to use the longitudinal control, the value seems to be wrong
        action[0] = IDMVehicle(env.vehicle.road, env.vehicle.position).acceleration(env.vehicle)
        print('action1:',action)

        #try to use both the longitudinal and lateral control, the result is None
        action = IDMVehicle(env.road, env.vehicle.position).act()
        print('action2:',action)

        next_state, reward, done, info = env.step(action)
        state = next_state
        frame_idx += 1

**Comment by yfxcore** [comment]
#Hi, I also tried to use it on the ContinuousAction mode, and tried to take IDM directly without modifying your original code, but I didn't make it. Could you please check where is the problem? Below is my trial, where I want to make the Longitudinal and lateral control:

#Draft code
import gym
import numpy as np
import highway_env
import pprint
from highway_env import utils
from highway_env.vehicle.behavior import IDMVehicle
env = gym.make('highway-v0')
env.configure({
"action": {
"type": "ContinuousAction"
},
})
env.reset()
max_frames = 200
frame_idx = 0
while frame_idx < max_frames: 
    state = env.reset()
    for step in range(512):
        env.render()
        action = [0, 0]
        front_vehicle, rear_vehicle = env.road.neighbour_vehicles(env.vehicle, env.vehicle.lane_index)

        #try to use the longitudinal control, the value seems to be wrong
        action[0] = IDMVehicle(env.vehicle.road, env.vehicle.position).acceleration(env.vehicle)
        print('action1:',action)

        #try to use both the longitudinal and lateral control, the result is None
        action = IDMVehicle(env.road, env.vehicle.position).act()
        print('action2:',action)

        next_state, reward, done, info = env.step(action)
        state = next_state
        frame_idx += 1

**Comment by yfxcore** [comment]
#Hi, I also tried to use it on the ContinuousAction mode, and tried to take IDM directly without modifying your original code, but I didn't make it. Could you please check where is the problem? Below is my trial, where I want to make the Longitudinal and lateral control:

import gym
import numpy as np
import highway_env
import pprint
from highway_env import utils
from highway_env.vehicle.behavior import IDMVehicle

env = gym.make('highway-v0')
env.configure({
"action": {
"type": "ContinuousAction"
},
})
env.reset()
max_frames = 200
frame_idx = 0
while frame_idx < max_frames: 
    state = env.reset()
    for step in range(512):
        env.render()
        action = [0, 0]
        front_vehicle, rear_vehicle = env.road.neighbour_vehicles(env.vehicle, env.vehicle.lane_index)
        #try to use the longitudinal control, the value seems to be wrong
        action[0] = IDMVehicle(env.vehicle.road, env.vehicle.position).acceleration(env.vehicle)
        print('action1:',action)
        #try to use both the longitudinal and lateral control, the result is None
        action = IDMVehicle(env.road, env.vehicle.position).act()
        print('action2:',action)

        next_state, reward, done, info = env.step(action)
        state = next_state
        frame_idx += 1

**Comment by yfxcore** [comment]
#Hi, I also tried to use it on the ContinuousAction mode, and tried to take IDM directly without modifying your original code, but I didn't make it. Could you please check where is the problem? Below is my trial, where I want to make the Longitudinal and lateral control:

import gym
import numpy as np
import highway_env
import pprint
from highway_env import utils
from highway_env.vehicle.behavior import IDMVehicle

env = gym.make('highway-v0')
env.configure({
"action": {
"type": "ContinuousAction"
},
})
env.reset()
max_frames = 200
frame_idx = 0
while frame_idx < max_frames: 
    state = env.reset()
    for step in range(512):
        env.render()
        action = [0, 0]
        front_vehicle, rear_vehicle = env.road.neighbour_vehicles(env.vehicle, env.vehicle.lane_index)
        #try to use the longitudinal control, the value seems to be wrong
        action[0] = IDMVehicle(env.vehicle.road, env.vehicle.position).acceleration(env.vehicle)
        print('action1:',action)
        #try to use both the longitudinal and lateral control, the result is None
        action = IDMVehicle(env.road, env.vehicle.position).act()
        print('action2:',action)
        next_state, reward, done, info = env.step(action)
        state = next_state
        frame_idx += 1

**Comment by yfxcore** [comment]
Hi, I also tried to use it on the ContinuousAction mode, and tried to take IDM directly without modifying your original code, but I didn't make it. Could you please check where is the problem? Below is my trial, where I want to make the Longitudinal and lateral control:

#Draft code
import gym
import numpy as np
import highway_env
import pprint
from highway_env import utils
from highway_env.vehicle.behavior import IDMVehicle
env = gym.make('highway-v0')
env.configure({
"action": {
"type": "ContinuousAction"
},
})
env.reset()
max_frames = 200
frame_idx = 0
while frame_idx < max_frames: 
    state = env.reset()
    for step in range(512):
        env.render()
        action = [0, 0]
        front_vehicle, rear_vehicle = env.road.neighbour_vehicles(env.vehicle, env.vehicle.lane_index)
        #try to use the longitudinal control, the value seems to be wrong
        action[0] = IDMVehicle(env.vehicle.road, env.vehicle.position).acceleration(env.vehicle)
        print('action1:',action)
        #try to use both the longitudinal and lateral control, the result is None
        action = IDMVehicle(env.road, env.vehicle.position).act()
        print('action2:',action)
        next_state, reward, done, info = env.step(action)
        state = next_state
        frame_idx += 1

**Comment by eleurent** [comment]
It is a bit tricky, since it requires casting the simple Vehicle class (used for continuous actions) to IDMVehicle, but the scene still holds the former Vehicle instead of the copy, so it's not a perfect replacement.

```

#Draft code
import gym
import numpy as np
import highway_env
import pprint
from highway_env import utils
from highway_env.vehicle.behavior import IDMVehicle
env = gym.make('highway-v0')
env.configure({
"action": {
"type": "ContinuousAction"
},
"policy_frequency": 15
})
env.reset()
max_frames = 200
frame_idx = 0
while frame_idx < max_frames:
    state = env.reset()
    for step in range(512):
        env.render()
        action = [0, 0]
        front_vehicle, rear_vehicle = env.road.neighbour_vehicles(env.vehicle, env.vehicle.lane_index)
        vehicle = IDMVehicle(env.vehicle.road, env.vehicle.position, heading=env.vehicle.heading, speed=env.vehicle.speed,
                             target_lane_index=env.vehicle.lane_index, target_speed=25)
        action[0] = vehicle.acceleration(vehicle, front_vehicle, rear_vehicle)
        action[1] = vehicle.steering_control(vehicle.target_lane_index)
        print('action:', action)
        next_state, reward, done, info = env.step(action)
        state = next_state
        frame_idx += 1
```

Calling act() does not return anything so it is expected to get a None. You can access env.vehicle.action instead, after calling act(), but that won't work since it will recompute the neighbour vehicle, and return the original Vehicle as the front_vehicle of the copy (IDMVehicle).

**Comment by yfxcore** [comment]
Okay I got it. Many thanks bro.
