### ISSUE TITLE
Continuous actions (parking-v0)

### ISSUE THREAD

**Issue by AntoNoga** [eleurent/highway-env#296]
Hello,

I wanted to ask you for a detailed explanation of Continuous actions (parking-v0).

The agents "learn" to set the "a" and "delta" parameters of the low-level controller for correct parking, but it is not clear to me if their definition range is discretized (if so, where) and the idea that you used.
 It's a continuous control task which learns from pixels ? 

Thanks for your attention

**Comment by eleurent** [comment]
You can select several options:

By using
```
env = gym.make('highway-v0')
env.configure({
    "action": {
        "type": "ContinuousAction"
    }
})
env.reset()
```
you get continuous actions where you can set a and delta directly (no discretization).

Alternatively, you can set 
```
env.configure({
    "action": {
        "type": "ContinuousAction"
    }
})
```
To discretize this continuous space to a discrete set of actions, and you can choose the discretization step per axis (a and delta).

Likewise, you can also choose the type of observation, which can be from pixels (GrayscaleObservation), or from scalar features, like the KinematicsObservation, TTCObservation, etc.

For more information, see https://highway-env.readthedocs.io/en/latest/actions/index.html and https://highway-env.readthedocs.io/en/latest/observations/index.html
