### ISSUE TITLE
Add more kinetics constraints

### ISSUE THREAD

**Issue by zhumingpassional** [eleurent/highway-env#301]
How to add more kinetics constraints, e.g., max speed, max acceleration, max jerk, max curvature, max variance curvature with respect to distance, and min distance to other vehicles?

**Comment by eleurent** [comment]
- For simple kinetic constraints (position, speed, acceleration, curvature), you should edit vehicle/kinematics.py
- For dynamical constraints (jerk; variance curvature; etc) you should edit vehicle/dynamics.py
- And for the min distance to other vehicles, it kind of depends on the behavioural model of the vehicles you are considering. By default, uncontrolled vehicles in the scenes follow the IDM longitudinal model, which has a parameter controlling the desired distance to the front vehicle, which you can set in vehicle/behavior.py
