### ISSUE TITLE
Use other DRL libraries

### ISSUE THREAD

**Issue by zhumingpassional** [eleurent/highway-env#302]
How to use other DRL libraries (e.g., elegantRL, tianshou) with highway-env as env?

**Comment by eleurent** [comment]
I have only tried to use openai/baselines, DLR-RM/stable-baselines3, and eleurent/rl-agent libraries. But highway-env follows the common openai/gym interface, so if these DRL libraries support it then it should work fine. I encourage you to look at the documentation of these libraries to find out how to run them on a custom openai/gym environment.

**Comment by lostboy233333** [comment]
Have you tried to combine tianshou with highway environment? Did it work?

**Comment by eleurent** [comment]
Hi, no I have not. If you try, let me know how it goes :)
