### ISSUE TITLE
Keep agent in lane in Continuous Action space

### ISSUE THREAD

**Issue by TibiGG** [eleurent/highway-env#307]
I am playing around with the intersection environment with continuous actions, and I am having a hard time modelling the agent to stay in lane.
It would be great to have the information of his angle/offset from the middle of the lane as part of his observation space, and learn the behaviour from there, not purely from the reward function. I am using the Kinematic Observation. For multi-agent.

Sorry if it was in the documentation already and I did not notice.

**Comment by wuyukun-tong** [comment]
hi，I have the same problem. Can we talk about it in detail? My email is wuyukun001@163.com

**Comment by TibiGG** [comment]
I'm happy to connect, but I think we ideally keep the discussion in here, so that others may add their own input to our ideas.

I saw another discussion where @eleurent modelled a reward function based on the proximity of the car to the middle of the lane, in the racing environment. This makes me aware that it is possible to model, and there are already tools in place to help with this. I am just not aware of them, or whether they can be added as input to the observation space already.

**Comment by wuyukun-tong** [comment]
I set up a lane-keeping function, but I'm not sure if it's correct



***@***.***
***@***.***



---- Replied Message ----
From ***@***.***>Date 05/15/2022 17:38 To ***@***.***>Cc ***@***.******@***.***>Subject Re: [eleurent/highway-env] Keep agent in lane in Continuous Action space (Issue #307)
I'm happy to connect, but I think we ideally keep the discussion in here, so that others may add their own input to our ideas.
I saw another discussion where @eleurent modelled a reward function based on the proximity of the car to the middle of the lane, in the racing environment. This makes me aware that it is possible to model, and there are already tools in place to help with this. I am just not aware of them, or whether they can be added as input to the observation space already.

**Comment by wuyukun-tong** [comment]
Which environment do you use? I use intersection environment, and my idea is to set up a reward function to train the vehicle keep lane. 
The steering Angle can also be controlled with a lower level controller

**Comment by TibiGG** [comment]
I have a custom environment based on the intersection and the parking environment, but mostly an intersection replica with goal locations instead of pre-planned directions. 

I wanted to have the offset to the middle of the lane as part of the observation space, in order to maintain a more linear policy, and make it easier to transfer the policy between environments.

I control both the acceleration and the steering angle.

**Comment by wuyukun-tong** [comment]
How did you set up the reward function for lane departure
My idea is to add one-dimensional information (the angle of vehicle deviates from the lane) to the observation matrix as observation. But I don't know how to get this Angle  @eleurent 
Maybe you can  use image as the observation.

**Comment by TibiGG** [comment]
The reward function is the same one as for the parking environment: distance/offset to the goal. I want to add some extreme environment resets: either to force the car to crashed if it strays off its lane, or to give it an extreme negative reward once it exits it.

But yes, your reward function looks like a good idea to stabilise the car's movement.

It would be nice of you to consider including this info within the observation space as well. Once it is there, you should be able to retrieve it quite easily to add into your reward

**Comment by eleurent** [comment]
Hello to you both,
Yes, I fully agree that an observation providing lateral and angular deviations from the lane centerline is currently missing, and would be quite useful in continuous control tasks. 
I will add it when I have a few spare minutes. 
In the meantime, you could still try to make it work with absolute kinematic observations (e.g. for a straight horizontal road, y=lateral deviation and heading=angular deviation. And in the racetrack-env the agent can basically "memorize" the road curve by mapping the offroad penalty signal to its (x,y) location in the observation), but I agree that relative lane-centric observations would be much better for generalisation.

**Comment by eleurent** [comment]
Also, in the mean time, you can have a look a the LaneKeeping environment and its observation : https://github.com/eleurent/highway-env/blob/master/highway_env/envs/lane_keeping_env.py

But I think it is a bit convoluted and it would still be worth adding a separate observation type for that.

**Comment by wuyukun-tong** [comment]
Thanks a lot ! I hope you can add a reward function for lane keeping in the intersection environment.



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | Edouard ***@***.***> |
| Date | 05/15/2022 21:18 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [eleurent/highway-env] Keep agent in lane in Continuous Action space (Issue #307) |

Also, in the mean time, you can have a look a the LaneKeeping environment and its observation : https://github.com/eleurent/highway-env/blob/master/highway_env/envs/lane_keeping_env.py

But I think it is a bit convoluted and it would still be worth adding a separate observation type for that.

**Comment by TibiGG** [comment]
Thank you for the clarification!

I am on a bit of a deadline, so I will try to add the observations. Will create a draft pull request today for it.

**Comment by TibiGG** [comment]
I created a pull request #310 with the extra info.
Before the pull request is accepted, @wuyukun-tong, feel free to pull my commits into your version of the highway-env project.

You can extract them from the vehicle's `lane_offset` property and plug them into your reward function as you like. Or from your observation space, works both ways.

**Comment by wuyukun-tong** [comment]
Thanks a lot for your great work



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 05/16/2022 20:45 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [eleurent/highway-env] Keep agent in lane in Continuous Action space (Issue #307) |

I created a pull request #310 with the extra info.
Before the pull request is accepted, @wuyukun-tong, feel free to pull my commits into your version of the highway-env project.

You can extract them from the vehicle's lane_offset property and plug them into your reward function as you like. Or from your observation space, works both ways.

**Comment by ZhenZhuHuang** [comment]
Why do I run out of the driveway using a continuous Kinematics

**Comment by ZhenZhuHuang** [comment]
![image](https://user-images.githubusercontent.com/97666369/169484805-ab924093-a356-424b-96cd-5d4674151986.png)

**Comment by wuyukun-tong** [comment]
When you select continuous action, the steering angle is randomly sampled within your defined range. You can read the previous Q&A carefully, I'm sure you will find a solution to the problem



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 05/20/2022 16:13 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [eleurent/highway-env] Keep agent in lane in Continuous Action space (Issue #307) |

Why do I run out of the driveway using a continuous Kinematics

**Comment by ZhenZhuHuang** [comment]
Ok, I will take a closer look, thank you for your answer!

**Comment by Lplenka** [comment]
Hello @eleurent @TibiGG @wuyukun-tong 

I am using PPO to train the agent in a highway-fast-0 environment. I am using the Continuous Action type as follows:

```
"observation": {
    "type": "Kinematics",
    "vehicles_count": 5,
    "features": ["presence", "x", "y", "vx", "vy", "long_off", "lat_off", "ang_off"],
},
"action": {
    "type": "ContinuousAction",
    "steering_range": [-np.pi/5, np.pi/5],
    "speed_range":[5, 25],
    "longitudinal": True,
    "lateral": True,
    "dynamical": True
}
```

Based on @eleurent's [comment ](https://github.com/eleurent/highway-env/issues/307#issuecomment-1126940421) above, I added the lane-centring reward to the existing reward function. I also tried using tips in this [issue#331](https://github.com/eleurent/highway-env/issues/331). 

After updating the reward function, I spent a lot of time finding bugs, and changing the weights of different rewards to make it work. Unfortunately, the BicycleVehicle still doesn't learn to stay in the lane. It still just wiggles around and doesn't move straight. I am not sure what's the cause of this. 

@TibiGG could you share your reward setting or environment file? Or any tips on how to use the lane-offset property in the reward function.

**Comment by eleurent** [comment]
Did you try it with the simpler kinematics model (Vehicle) rather than the dynamics model (Bicycle Vehicle)?
Also what observation type are you using, can the agent locate itself relatively to the road?

**Comment by Lplenka** [comment]
Hello @eleurent 

I tried the kinematics (Vehicle) and dynamics model (Bicycle Vehicle).  The observation is kinematics, like the following:

```
"observation": {
    "type": "Kinematics",
    "vehicles_count": 5,
    "features": ["presence", "x", "y", "vx", "vy", "long_off", "lat_off", "ang_off"],
}
```


> "Can the agent locate itself relative to the road?"


I am not sure how to check this.

**Comment by eleurent** [comment]
Ok, then I think the agent should be able to predict going off-road, since the road is horizontal and the agent has access to its vertical position and speed (y, vy) (then, being off-road is y<0 or y>y_max).
Are there other vehicles in the scene? If so, a good sanity check would be to remove them, and I would expect the agent to learn a good lane-keeping policy very quickly. And if that works but adding back the vehicles breaks performance, it would mean that the representation of other vehicles must be improved.
