### ISSUE TITLE
how to run merge-v0 environment demo using rl_agents?

### ISSUE THREAD

**Issue by LawranceXcl** [eleurent/highway-env#31]

**Comment by eleurent** [comment]
1. Download and install [highway-env](https://github.com/eleurent/highway-env)
2. Download [rl-agents](https://github.com/eleurent/rl-agents), add to python path
3. `cd /path/to/rl-agents/scripts`
4. `python experiments.py evaluate configs/MergeEnv/env.json configs/MergeEnv/agents/DeterministicPlannerAgent/baseline.json --test --episodes=1`

**Comment by LawranceXcl** [comment]
![选区_003](https://user-images.githubusercontent.com/47016472/70312257-37befa80-184e-11ea-9e39-4a5fb69a39cc.png)
this error, how to solve it ? thks!

**Comment by eleurent** [comment]
I pushed the agent config yesterday so simply do: `git pull origin master`
Otherwise, you can also run: `python experiments.py evaluate configs/MergeEnv/env.json configs/HighwayEnv/agents/DeterministicPlannerAgent/baseline.json --test --episodes=1`

**Comment by LawranceXcl** [comment]
Ok! Done successfully! Thks!
Aiming at the merging env, do you also use the rl algorithm?And I can see that the host vehicle is in the main lane, I wonder if the method of RL algorithm you did can handle the case where the host vehicle is in the ramp.  Before the acceleration lane of ramp is end, the host can merging into the main lane successfully.
