### ISSUE TITLE
Set max velocity and min velocity of the ego vehicle

### ISSUE THREAD

**Issue by ycpengpeng** [eleurent/highway-env#313]
Hi, in the "ContinuousAction" action mode, how to set the max velocity and min velocity of the ego vehicle? It seems there existing a MAX speed of the ego vehicle, but I don't know how to change it.Thanks for your answer.

**Comment by eleurent** [comment]
Good point! I just added the functionality, if you install the development version you can now configure the minimum and maximum speed with e.g.
```
env.configure({
    "action": {
        "speed_range": (10., 20.)
    }
})
env.reset()
```
