### ISSUE TITLE
Any way to make DiscreteMetaActions move the vehicle backwards?

### ISSUE THREAD

**Issue by TibiGG** [eleurent/highway-env#316]
Currently, in the intersection environment, on the discrete meta action space, the vehicles can only be given 3 actions:
0: SLOWER
1: FASTER
2: IDLE

Is there any way to make the vehicles move backwards, given the way discrete meta actions have been designed? Or is this possible only through the usage of continuous action spaces?

Thanks!
EDIT: note that SLOWER does not make the cars move backwards. It only makes them stop. I checked.

**Comment by eleurent** [comment]
Sure, you can allow the vehicle to move backward by adding a negative to the list of allowed target speeds.

For instance,
```
env.configure({
    "action": {
        target_speeds: [-5, 0, 5, 10]
    }
})
```
The slower/faster action changes the tracked speed to the previous/next element in that list.

**Comment by TibiGG** [comment]
Thanks a lot! Really quick fix!
