### ISSUE TITLE
observation  in roundabout

### ISSUE THREAD

**Issue by tingtingLiuLiu** [eleurent/highway-env#317]
Hello ,Using kine observation type, the collision rate is still high after running 1000 episodes. Is this observation method not suitable for the roundabout scene? Are the absolute coordinates of the car based on the center position in the roundabout scene?

**Comment by eleurent** [comment]
Hi,
- yes, the absolute coordinates are based on the center position of the roundabout scene
- about the collisions still being high, well, RL is hard and there can be multiple causes ^^ But yes, I would say it can be likely attributed to the observation-model pair, so you can try to change either of these (e.g. image observations + CNN model, or kinematics obs + transformer model, etc.)

**Comment by tingtingLiuLiu** [comment]
Thanks

**Comment by tingtingLiuLiu** [comment]
How should the observation_shape value be set?
 Does the image show a car front-view or top-view in scene?

**Comment by tingtingLiuLiu** [comment]
how to show the path in the image?

**Comment by tingtingLiuLiu** [comment]
how to show the path(or routing) in the image?

**Comment by tingtingLiuLiu** [comment]
How many meters are the map settings around the vehicle?（50 x 50 meters?）

**Comment by eleurent** [comment]
See the docs: https://highway-env.readthedocs.io/en/latest/observations/index.html#grayscale-image

- the image is a top view of the scene
- the level of zoom (50x50m or other) is controlled by the `scaling` parameter
- showing planned route is not currently supported, so it would have to be added.

**Comment by tingtingLiuLiu** [comment]
Thanks a lot. Sorry to interrupt again
What value of scaling is set to determine that the topview observation of the vehicle is 50x 50 meters？Is scaling related to obervation_shape?

**Comment by eleurent** [comment]
Scaling is used to convert original distances in meters to distances in pixels for rendering, and the observation_shape determines the size of the observation in pixels. 
So to get a 50m x 50m observation, you can use observation_shape=(50, 50) and scaling=1, or observation_shape=(25, 25) and scaling=0.5,

More generally, you should use observation_shape=(50*scaling, 50*scaling), and the resolution (size of a pixel) will be 1/scaling meters/pixel (so higher scaling means better resolution)

**Comment by tingtingLiuLiu** [comment]
Hello, using RGB+CNN training, training 200 episodes, I spent half a day and an hour. What factor does this have to do with? is environment rendering?

**Comment by eleurent** [comment]
That seems very slow indeed, especially for the roundabout environment which has very few vehicles.
Obviously rendering the image observations will take more time than scalar observation, but not that much. Have you disabled rendering while you are training ? (beside rendering the obs, I mean)
