### ISSUE TITLE
Manual control Issues

### ISSUE THREAD

**Issue by jlwu002** [eleurent/highway-env#322]
Hi, I found out I can only use manual control for highway-v0. The game configuration/control does not work anymore for the other environments when I set it to be manual control. 

For example
1) in Merge, I cannot increase the number of vehicles or the density of the vehicles. 
2) In Intersection, on top of cannot change the number of vehicles/density, the car would stop moving.

I wonder is it that manual control is only meant for highway-v0 only?

Thank you!

**Comment by eleurent** [comment]
No; the manual control option is not only meant for highway-v0 and should also work with other environments. See https://github.com/eleurent/highway-env/issues/321

**Comment by jlwu002** [comment]
I wonder can you change the vehicles/density for Merge, especially with manual control? Thank you!

**Comment by eleurent** [comment]
Currently you can't, you have to edit the _make_vehicles method in merge_env.py.

**Comment by jlwu002** [comment]
Thank you!
