### ISSUE TITLE
How to use the seed in the training of ‘highway-env’?

### ISSUE THREAD

**Issue by liuqi1998** [eleurent/highway-env#329]
![image](https://user-images.githubusercontent.com/40832743/171583717-3541e57c-3d29-4d07-beea-675fbb5e080e.png)

How to use the seed in the training of ‘highway-env’?

**Comment by eleurent** [comment]
A seed can be used to reproduce the randomness of the environment with:
```
env.seed(1234)
env,reset()
```

Of course, if your agent has randomness too (e.g. for exploration / initialisation), you need to seed it as well.

**Comment by baimukashev** [comment]
Hi, 

I was testing 'highway-v0' scenario with default KinematicObservation . 

env.seed(124) gives an error < AttributeError: 'HighwayEnv' object has no attribute 'seed' >
env.reset(seed=123) does not give the same initial results. 

For example: 
>>> env = gym.make("highway-v0")
>>> obs, _ = env.reset(seed=1)
>>> obs
      ([[ 1.        ,  0.87680423,  0.        ,  0.3125    ,  0.        ],
       [ 1.        ,  0.10702147,  0.25      , -0.03396416,  0.        ],
       [ 1.        ,  0.21362191,  0.5       , -0.04374623,  0.        ],
       [ 1.        ,  0.30941233,  0.        , -0.04075122,  0.        ],
       [ 1.        ,  0.41150135,  0.5       , -0.02447509,  0.        ]],)
>>> obs, _ = env.reset(seed=1)
>>> obs
       [[ 1.        ,  0.8917242 ,  0.5       ,  0.3125    ,  0.        ],
       [ 1.        ,  0.1178149 , -0.25      , -0.0153798 ,  0.        ],
       [ 1.        ,  0.23038252, -0.25      , -0.01790893,  0.        ],
       [ 1.        ,  0.33949324, -0.25      , -0.03181197,  0.        ],
       [ 1.        ,  0.45183745, -0.5       , -0.02888946,  0.        ]], )

If possible, how to reproduce initial condition of the ego and the movement of nearby vehicles (i.e. non-reactive) by the usage of the seed?

**Comment by eleurent** [comment]
Hi,
You are probably using an old version of gym (pre-0.26). You can either upgrade gym and highway-env, or use the old syntax:
```
env = gym.make("highway-v0")
env.seed(1)
obs = env.reset()
```

**Comment by eleurent** [comment]
Oh okay, it looks like I temporarily disabled seeding when transitioning to the gym 0.26 API, and I completely forgot about it afterward. Anyway, this is now fixed at HEAD, thank you for the feeback!

**Comment by baimukashev** [comment]
Many thanks!
