### ISSUE TITLE
target_speeds

### ISSUE THREAD

**Issue by piccupl** [eleurent/highway-env#333]
Hi，@eleurent！DiscreteMetaAction has an attribution target_speeds. I can't understand its meaning.
Can you give a detailed example for understanding
issue278  seems not clear.

**Comment by eleurent** [comment]
As explained in https://github.com/eleurent/highway-env/issues/278, target speeds is a set of speeds that can be tracked by the vehicle.
For instance, you could set 
target_speeds = [5 m/s, 10 m/s, 15 m/s, 20m / s]
Assume the vehicle is initially created with a target speed of 10 m/s.
If you execute the FASTER action, the target speed will move to the next index in the list, i.e. 15 m/s.
If you execute FASTER again, the target speed will now be 20 m/s. From there, doing FASTER changes nothing (already max speed), and doing SLOWER changes it back to 15 m/s.

By setting this parameter, you can allow for different ranges of reachable speeds depending on your needs.

**Comment by pranchi** [comment]
If you execute FASTER again, the target speed will now be 20 m/s. From there, doing FASTER changes nothing (already max speed),

would this mean, at this point both FASTER and IDLE have the same effect?

**Comment by pranchi** [comment]
> If you execute FASTER again, the target speed will now be 20 m/s. From there, doing FASTER changes nothing (already max speed)

Would this mean FASTER and IDLE will be having having the same effect at this point?

**Comment by eleurent** [comment]
Yes, exactly. If your agent supports it, you can also call `env.get_available_actions()`, which will exclude the FASTER action when the vehicle is already at maximum speed.
