### ISSUE TITLE
Benchmark results

### ISSUE THREAD

**Issue by MeixinZhu** [eleurent/highway-env#334]
Thanks for this great project!! Are there any benckmar results on which model + obs + reward work best in a specific environment? @eleurent

**Comment by eleurent** [comment]
Unfortunately not. In [this paper](https://arxiv.org/abs/1911.12250), I benchmark three pairs of (obs, model), but that's about it.
But that would be a great idea, if you plan on doing a more comprehensive benchmark with reproducible experiments, that would make a nice addition, so feel free to do a PR.

**Comment by MeixinZhu** [comment]
Thanks! Yes, I will make a PR if I have some results about this. Another question is when I directly use steer and acceleration as continuous action (the continuous action type), the performance is really bad (vehicles will just rotate). Any suggestions for using continuous action?

**Comment by MeixinZhu** [comment]
@eleurent

**Comment by eleurent** [comment]
Sorry for not replying, let me know if this is still needed.
