### ISSUE TITLE
DQN example raises error

### ISSUE THREAD

**Issue by zhumingpassional** [eleurent/highway-env#338]
The DQN example  https://highway-env.readthedocs.io/en/latest/quickstart.html#training-an-agent, runs successfully if using colab, however, it raises error if running locally in MacOS. In detail, the training process is successful, but " model = DQN.load("highway_dqn/model")" failed.

The following is error: 
Traceback (most recent call last):
  File "/Users/mingzhu/opt/anaconda3/lib/python3.9/site-packages/stable_baselines3/common/save_util.py", line 256, in open_path_pathlib
    path = path.open("rb")
  File "/Users/mingzhu/opt/anaconda3/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
IsADirectoryError: [Errno 21] Is a directory: 'highway_dqn/model'
python-BaseException

Could you please test it locally? Thanks for your effort.

**Comment by eleurent** [comment]
Running [this script](https://github.com/eleurent/highway-env/blob/master/scripts/sb3_highway_dqn.py) locally works fine for me.
But since your issue is more related to [stable_baselines3](https://github.com/DLR-RM/stable-baselines3), I suggest you ask them, they may be able to help.

**Comment by pranchi** [comment]
I'm assuming you are getting this error because of trying to load the directory of your saved model. If you used the filename (file with .zip as an extension) of the model you have saved, it should load perfectly.

**Comment by siddahant** [comment]
Running [this script](https://github.com/eleurent/highway-env/blob/master/scripts/sb3_highway_dqn.py) locally raised an error for me,

    obs, reward, done, truncated, info = env.step(action)
ValueError: not enough values to unpack (expected 5, got 4)

    obs, info = env.reset()
ValueError: too many values to unpack (expected 2)

**Comment by zsn2021** [comment]
> 

请问你解决了吗

**Comment by eleurent** [comment]
The latest version only supports gym>=0.26. If you're using a previous version of gym, then you should install a previous release of highway-env.
