### ISSUE TITLE
Make attention vector visible in rendering

### ISSUE THREAD

**Issue by Plankson** [eleurent/highway-env#339]
Hi! Mr. eleurent. I'm interested in your social attention architecture work in intersection-v0. Now I design a new Attention network on my own and there is a interface of it to get the attention vector. I really want to know how to visualize the vector when rendering like your work result with lines of different width to represent attention between vehicles and ego vehicle in [intersection_social_dqn.ipynb](https://github.com/eleurent/highway-env/blob/master/scripts/intersection_social_dqn.ipynb). Is there any interface or config setting about it?

**Comment by eleurent** [comment]
Hi! No, there is no interface/config, but the visualisation code is here:

https://github.com/eleurent/rl-agents/blob/10b8e3060097c5f4c9bab9345f10bddf6f12297b/rl_agents/agents/deep_q_network/graphics.py#L55

It is not a great piece of code, especially one part is quite ugly: we need to map the attention tokens (rows of the observation) back to the vehicles in the original environment (so we can plot the lines), which requires undoing the observation normalisation to recover an unnormalised x/y location and find the closest vehicle in the scene... It would be much better to e.g. include the vehicle id in the observation or something like that.
