### ISSUE TITLE
Need explanation of observation, action and reward 

### ISSUE THREAD

**Issue by yryun** [eleurent/highway-env#34]
Thanks for your excellent environment!

Is there any explanation of observation, action and reward?

**Comment by eleurent** [comment]
Hi @yryun, thanks!
That's a very good question, there is no documentation on the matter and I should fix that.

The observation, action and reward all depend on the environment variant that you consider.
Each of them in https://github.com/eleurent/highway-env/tree/master/highway_env/envs must define an `observation_space`, an `action_space`, and a `_reward()` function.

**Actions** are usually a discrete set of short-term behaviours, among the set described in https://github.com/eleurent/highway-env/blob/master/highway_env/envs/common/abstract.py#L26
Some environments however, such as parking-env, use continuous control actions directly.

**Rewards** can change depending on the task, but it usually involves maximizing velocity (bonus) while avoiding collisions (penalty + terminal state)

Observations can be of several kinds, defined in https://github.com/eleurent/highway-env/blob/master/highway_env/envs/common/observation.py
The `KinematicObservation `gives an array of the relative positions and velocities of each vehicle around the ego-vehicle. The `OccupancyGridObservation `is similar, but represented as an occupancy grid, and the `GrayscaleObservation `is an image from `env.render()`.
For each environment, a default observation is defined in `default_config()`, but can be changed using 
depending on your needs, by calling `env.configure(config)`, where `config["observation"]` will land here: https://github.com/eleurent/highway-env/blob/master/highway_env/envs/common/observation.py#L282

I hope that helps,
Edouard
