### ISSUE TITLE
Question about confing  rewards

### ISSUE THREAD

**Issue by zhangjianguo-max** [eleurent/highway-env#341]
Hello, I'd like to ask you about a problem I'm having. First, there is a default lane change reward in the configuration, but when I assign a value to it, it doesn't work, what should I do with it? Second, I want to set the speed reward to a*(V-vmin)/(vmax-vmin) instead of rewarding a speed interval, what should I do? Thank you for your answer.

**Comment by KexianShen** [comment]
- 
  ```python
  import gym
  import highway_env
  import pprint
  env = gym.make("highway-fast-v0")
  env.configure({"lane_change_reward": -0.1})
  obs = env.reset()
  pprint.pprint(env.config)   # check the env config for sure
  ```
- you need to modify the [`_reward`](https://github.com/eleurent/highway-env/blob/9e3649dfc53d253185705e62484b5595692ebbb2/highway_env/envs/highway_env.py#L80-L101) function.
you can use `self.vehicle.action["acceleration"]` as acceleration.

**Comment by zhangjianguo-max** [comment]
Yes, I found this setting in env.configure({"lane_change_reward": -0.1}), but when I tried to set all the other rewards to zero and just looked at it, I found that it didn't work.I want to ask you how to change it to make it work. As you can see, there is no reward in _reward function.

**Comment by KexianShen** [comment]
for example:
```python
def _reward(self, action: Action) -> float:
    ...
    lane_change = (
        1 if action in {0, 2} and self.action_space == spaces.Discrete(5) else 0
    )  # DiscreteMetaAction with ACTIONS_ALL
    reward = (
        +self.config["collision_reward"] * self.ego_vehicle.crashed
        # + self.config["right_lane_reward"] * lane / max(len(neighbours) - 1, 1)
        + self.config["high_speed_reward"] * np.clip(scaled_speed, 0, 1)
        + self.config["lane_change_reward"] * lane_change
    )
    ...
```

**Comment by zhangjianguo-max** [comment]
Thank you very much for your help, which solved my problem.
