### ISSUE TITLE
Video Recording Broken

### ISSUE THREAD

**Issue by lorandcheng** [eleurent/highway-env#342]
Hello, thanks for this repo, it's been a great resource for me! I've recently run into some trouble with video recording using the latest unreleased commits.

I first used the latest release with pip to test some trajectories, and the video recording was working fine. Then, I had to change the reward function so I cloned the repo and used the latest commit instead. Now, I noticed that the video folder was still created but no new videos are being written. 

Here is the test code I am using after I cloned the repo, taken from the [example code](https://highway-env.readthedocs.io/en/latest/faq.html) in the docs.
```
import gym
from gym.wrappers import RecordVideo

import sys
sys.path.insert(0, './highway-env')
import highway_env

# Wrap the env by a RecordVideo wrapper
env = gym.make("highway-v0")
env = RecordVideo(env, video_folder="./videos", episode_trigger=lambda e: True)  # record all episodes

# Provide the video recorder to the wrapped environment
# so it can send it intermediate simulation frames.
env.unwrapped.set_record_video_wrapper(env)

# Record a video as usual
obs = env.reset()
done = False
while not done:
    action = env.action_space.sample()
    obs, reward, done, info = env.step(action)
    env.render()
env.close()
```

I started rolling back to previous commits to see where the code broke, and I identified commit b8e3f47fb15df193c8c3c19caaa36700023cdd10 as the one where it stopped working. I'm not sure how the video recording is impacted by this change, but when I use the latest commit and just undo the changes in b8e3f47fb15df193c8c3c19caaa36700023cdd10 it starts working fine again.

**Comment by KexianShen** [comment]
It's related to gym's version. In [setup.cfg](https://github.com/eleurent/highway-env/blob/9e3649dfc53d253185705e62484b5595692ebbb2/setup.cfg#L23), gym is set to version 0.23.1. I test the example code locally with gym 0.25.0 and it works fine.

Undo commit [b8e3f47](https://github.com/eleurent/highway-env/commit/b8e3f47fb15df193c8c3c19caaa36700023cdd10), if you don't care gym's new api.

**Comment by lorandcheng** [comment]
I see, got it thanks

**Comment by eleurent** [comment]
Thanks for flagging this. The fix in openai/gym is included in the latest release, so I could revert commit [b8e3f47](https://github.com/eleurent/highway-env/commit/b8e3f47fb15df193c8c3c19caaa36700023cdd10).

**Comment by lukas0516** [comment]
> 
Hello, thanks for the repo first. 
I also run this demo code as listed above. The video folder was created but nothing in it, it was empty. 
The gym version is 0.21.0 and highway-env is 1.6.
I don't know how to solve this.

**Comment by eleurent** [comment]
Hi, do you have any error message in the console?
I think this RecordVideo wrapper is only compatible with the latest gym versions (0.26+, which means using highway-env 1.7+).
If you want to stick with gym 0.21 and highway-env 1.6, I think you should use their previous `Monitor` wrapper, which they used for video recording at the time.
