### ISSUE TITLE
How to add a feature to Kinematic observation?

### ISSUE THREAD

**Issue by skonwa** [eleurent/highway-env#343]
Hi!
Sorry,i am not familiar with environment code,so this is a question.I want to add a road priority feature for all vehicles(containing mdp and idm vehicle) that depends on which lane the vehicle at(for example,i use merge env,so,priority for vehicles on main lane is 1,and 0 on merge lane ),like the last column in the picture below.Now i use Kinematic observation,what should i do for this?
![20220723190553](https://user-images.githubusercontent.com/92068333/180602462-00245392-b609-498f-8fcf-3bf52673a1a4.jpg)

Thanks in advance!

**Comment by Lplenka** [comment]
Hello @skonwa 

Take a look at this [pull request](https://github.com/eleurent/highway-env/pull/310). This adds extra observations to kinematics model. Hope this helps.

**Comment by skonwa** [comment]
ok! I will see it. Thanks for your help.@Lplenka

**Comment by eleurent** [comment]
Thanks @Lplenka for helping out! 👍
