### ISSUE TITLE
Questin about roundabout environment setup

### ISSUE THREAD

**Issue by lxjlu** [eleurent/highway-env#344]
Hello, thanks for this repo! Some confusion about the roundabout environment setup. 
![image](https://user-images.githubusercontent.com/55116031/180752651-931c0ca7-8b9b-49d9-906e-d334aa218e99.png)
This is the diagram as I understand it. However, the definition of the lane ["se", "ex", 0] is something like net.add_lane("se", "ex", CircularLane(center, radii[lane], np.deg2rad(90 - alpha), np.deg2rad(alpha), clockwise=False, line_types=line[lane])). This means the start point of the lane is at  [8.13, 18.27](lane.position(0, 0), where I think should be where the lane of ["nx", "ee", 0]. Is there something wrong with my understanding of the whole environment design? Thanks

**Comment by lxjlu** [comment]
Another explanation I can think of is this：
![image](https://user-images.githubusercontent.com/55116031/180754839-c88d16c1-cd4b-417f-85b2-0ecca9ec1419.png)
Then position calculation is corresponding, but the north-south direction is a bit weird

**Comment by eleurent** [comment]
Hi @lxjlu, your first post is absolutely correct, and the only subtility is that I am using the convention that the y axis is downwards (towards the south, here). So the position (8.13, 18.27) is indeed in the (se, ex) segment.

Sorry if that was confusing, I got used to this convention after working in the aerospace industry for a few years (see e.g. [wikipedia](https://en.wikipedia.org/wiki/Axes_conventions#/media/File:Plane.svg))
