### ISSUE TITLE
TypeError: unhashable type: 'numpy.ndarray' when running sb3_highway_dqn.ipynb

### ISSUE THREAD

**Issue by PatrickYanZ** [eleurent/highway-env#345]
Hi there,
I met the following error while executing [sb3_highway_dqn.ipynb](https://github.com/eleurent/highway-env/blob/master/scripts/sb3_highway_dqn.ipynb)

No other modification, running the original file in Google colab.
```
[/usr/local/lib/python3.7/dist-packages/highway_env/envs/common/action.py](https://localhost:8080/#) in act(self, action)
    226 
    227     def act(self, action: int) -> None:
--> 228         self.controlled_vehicle.act(self.actions[action])
    229 
    230 

TypeError: unhashable type: 'numpy.ndarray'
```

Appreciate it in advance if you can fix that.

**Comment by KexianShen** [comment]
env.step expects an `int`, but gets a `numpy.ndarray` of single element.

````python
env = gym.make("highway-fast-v0")
env = record_videos(env)
for episode in trange(3, desc="Test episodes"):
    obs, done = env.reset(), False
    while not done:
        action, _ = model.predict(obs, deterministic=True)
        obs, reward, done, info = env.step(int(action))    # add int() or replace with action.item() here
env.close()
show_videos()
````

**Comment by PatrickYanZ** [comment]
Thanks, it works @KexianShen

**Comment by eleurent** [comment]
(This is due to a change in gym’s interface, possibly? Reopening this so I remember to fix the notebook).

**Comment by KexianShen** [comment]
nah, the script has been failed to run since the stable-baselines3 version was upgraded from 1.3 to 1.4.
