### ISSUE TITLE
Get info of other vehicles collisions

### ISSUE THREAD

**Issue by pranchi** [eleurent/highway-env#349]
Hi,

I was trying to use highway_env with random Obstacles object on the road. In this scenario some IDM Vehicles seems to be colliding with these obstacles. Is there any way I can get the count of these collisions in addition to the collisions of ego vehicle.

on looking through the code env.road.vehicles[0].crashed will give if the 1st IDM vehicle collided, I was trying to get the info for total collisions of IDM vehicles while training. I was looking for something like

other_vehicle_collisions =0  at the beginning and 
other_vehicle_collisions = 10 (as 10 collisions happened in that episode)

Is it possible to obtain this?

I tried to find how the step action is being executed for this env so that I can increment the value I need at the end.

**Comment by eleurent** [comment]
Hi!
It is not provided directly, but you can can compute the total number of collided vehicles with something like
´´´
sum(vehicle.crashed for vehicle in env.road.vehicles)
´´´
e.g. just after a call to env.step.

**Comment by pranchi** [comment]
Thanku for the reply, this really helped
Using the above code takes into consideration of the ego-vehicle crash. looping after tweaking that list got me what I wanted.
