### ISSUE TITLE
some questings about highway-v0

### ISSUE THREAD

**Issue by haijime-w** [eleurent/highway-env#351]
Hello,thanks for this great project!! I encountered some problems when I was learning.

Firstly,I want to know, in HIGHWAY_V0 environment, how to limit the speed of the vehicle automatically generated by the system in the lane?
Then，I am confused about the way of the highway environment ends. I want to know what is the end sign of the highway environment under normal circumstances except a collision.

Thanks!

**Comment by KexianShen** [comment]
- you could set the speed by editing [line](https://github.com/eleurent/highway-env/blob/453f84e6d69676555a0f93a3f814114a481237a1/highway_env/envs/highway_env.py#L77) in highway_env.py, like
  ```python
  # all other vehicles start at one speed
  vehicle = other_vehicles_type.create_random(self.road, speed=10, spacing=1 / self.config["vehicles_density"])
  ```
  or modify https://github.com/eleurent/highway-env/blob/453f84e6d69676555a0f93a3f814114a481237a1/highway_env/vehicle/kinematics.py#L25
- check https://github.com/eleurent/highway-env/blob/453f84e6d69676555a0f93a3f814114a481237a1/highway_env/envs/highway_env.py#L104-L108

**Comment by eleurent** [comment]
That's exactly right @KexianShen, thanks!

**Comment by haijime-w** [comment]
A big help！Thanks！
