### ISSUE TITLE
How can run parking-v0 environment

### ISSUE THREAD

**Issue by Viloa13** [eleurent/highway-env#353]
I want to test parking-v0 but when When I run the code, it reports an error `No module named 'reinforcement_learning'`
Is there something wrong with my code? Is it necessary to have an RL agent to run this?
```
import gym
import highway_env
env = gym.make('parking-v0')
obs = env.reset()
for _ in range(30):
    obs, reward, done, info = env.step(env.action_space.sample())
    env.render()

```

**Comment by eleurent** [comment]
Hi, your code below should work, see e.g. this colab: https://colab.research.google.com/drive/13hHFZvl6tDvXaa8qSZWN0wXVvk4oo2HM?usp=sharing

This repo only specifies the environment, so it doesnt rely on importing reinforcement learning agents, this is probably in your own codebase.
