### ISSUE TITLE
Train highway with CNN  render issue

### ISSUE THREAD

**Issue by oladayosolomon** [eleurent/highway-env#354]
After training the highway with image observation, the record video portion raises the error

'DummyVecEnv'  object has no attribute 'render mode'

![image](https://user-images.githubusercontent.com/15249490/184570054-c956868c-3216-4039-8b78-20d24b8a8b6d.png)

**Comment by KexianShen** [comment]
can you print relevant packages info, using
```python
import stable_baselines3 as sb3
sb3.get_system_info()
```

**Comment by oladayosolomon** [comment]
![image](https://user-images.githubusercontent.com/15249490/184580516-623bf4e5-a584-49eb-b664-99e53ca9f4e7.png)

**Comment by KexianShen** [comment]
I guess this error is raised due to the [conflict](https://github.com/DLR-RM/stable-baselines3/blob/c4f54fcf047d7bf425fb6b88a3c8ed23fe375f9b/setup.py#L76) between stable-baselines3 and gym's new version.

try
```python
env = gym.make("highway-fast-v0", render_mode="rgb_array")
```
or open an issue under stable-baselines3.

**Comment by oladayosolomon** [comment]
Thanks, tried it but didn't work!

**Comment by eleurent** [comment]
Yes, gym has changed its API a lot lately, and SB3 has not kept up with these changes. Instead, they froze their dependencies to `gym==0.23.1`. 
In this project, I am trying to stay compatible with the latest gym version instead and update features before they become deprecated. In the last release, I set gym>=0.25 as the minimum version, thus breaking compatibility with SB3 (which is problematic).
For now, if you want to use SB3 and highway-env, you have to use a former release such as v1.5 (and gym==0.23.1). I'll try to think of a better solution.

**Comment by oladayosolomon** [comment]
Thanks I downgraded the packages and it worked. However I discovered that the log is not giving  ep_mean_reward.  I guess this is due to the use of the dummyvec to wrap the highway_env. Any way around will be appreciated.

**Comment by oladayosolomon** [comment]
Thanks downgraded the packages. It worked
