### ISSUE TITLE
Vehicle count and density

### ISSUE THREAD

**Issue by oladayosolomon** [eleurent/highway-env#355]
Hi,
please is the vehicle count and density anyway related to the number of lanes. 

for the sake of fair comparison, when using vehicle count as 20 in two lanes highway env, what should be the vehicle count for 3 lanes??

**Comment by eleurent** [comment]
Hi, sorry for the late reply,
The way lanes are populated with vehicles is mostly a heuristic: 

https://github.com/eleurent/highway-env/blob/319720e61cc7dc3c8911ab3bdf27de2036f08ab3/highway_env/vehicle/kinematics.py#L49

And I typically proceed by trial and error to get the desired result.

I haven't really derived theoretically how the density, number of lanes, vehicles count are related, but it should be doable. Each vehicle is basically added at the back of the traffic on a random lane with a given x offset + some zero-mean noise.
