### ISSUE TITLE
highway-v0 simulation speed is slow

### ISSUE THREAD

**Issue by yryun** [eleurent/highway-env#36]
Thank you for the great environment !

I'm training the highway-v0 and the fps is 1 which is too slow to see the result in reinforcement learning.

Is there any bottleneck or need change config in the code?

I think it shows same fps, if I turn on the render or not.

-------------edit-------------

I changed SIMULATION_FREQUENCY in abstract.py, and it's much faster.

Is there any problem if i train with SIMULATION_FREQUENCY = 1 (which is same with policy hz) first, and render with SIMULATION_FREQUENCY = 10 ?

**Comment by eleurent** [comment]
Hi @yryun 

Disclaimer: `highway-env` is not and was never meant for high-scale simulation. It is more a tool for fast prototyping of driving scenarios and learning algorithms. There are many ways in which it could be optimised, including porting the project in c++, but is not my priority right now.

That being said, I've always considered the performance to be sufficient for my personal use, such as training a DQN or a policy gradient.

I did some profiling today to investigate your problem, and found out the the bottleneck comes from three steps: 
1. checking collisions between any two vehicles
2. finding neighbour vehicles of any simulated vehicle (for their behavioural model)
3. computing the deviations of the vehicles from the lane centerline (for lateral control)

The steps 1 are 2 have naive implementations which scale quadratically with the number of vehicles. Thus, my first advice would be to decrease the number of vehicles in the scene when you train.
You can do it with:
```
env = gym.make("highway-v0")
env.configure({
    "vehicles_count": <number of vehicles>  # 50 is the default value
})
```

Here are the improvements I get with the following script:
```
import time
import gym
import highway_env

def time_highway(vehicles_count=50, num_frames=100):
    env = gym.make("highway-v0")
    env.configure({
        "vehicles_count": vehicles_count
    })
    env.reset()
    start = time.time()
    for _ in range(num_frames):
        action = env.action_space.sample()
        _, _, done, _ = env.step(action)
        if done:
            env.reset()
    end = time.time()
    print('FPS with {} vehicles: {:.1f}'.format(vehicles_count, num_frames / (end-start)))

time_highway(50)
time_highway(30)
time_highway(20)
time_highway(10)
```
> FPS with 50 vehicles: 2.1
> FPS with 30 vehicles: 5.1
> FPS with 20 vehicles: 9.8
> FPS with 10 vehicles: 25.8

**Comment by eleurent** [comment]
>I changed SIMULATION_FREQUENCY in abstract.py, and it's much faster.
>Is there any problem if i train with SIMULATION_FREQUENCY = 1 (which is same with policy hz) first, and render with SIMULATION_FREQUENCY = 10 ?

That is something you can do, but I'm using a simple Euler integration scheme, so it might degrade the control performances of the agents, prevent them from refreshing their commands often enough, lead to overshoots and collisions, etc. 

I suggest you try and decrease the simulation frequency _while_ rendering, to see the effects it has on the realism of the simulation.

**Comment by yryun** [comment]
Thank you for the solution!
