### ISSUE TITLE
The observation space in merge-v0 

### ISSUE THREAD

**Issue by Viloa13** [eleurent/highway-env#360]
Hi @eleurent,

I ran the environment **merge-v0** and printed the observation space for each step as follows:
```
[[ 1.          1.          0.3282177   0.31210405  0.00240169]
 [ 1.          0.32850587  0.00511564  0.0777404  -0.00240169]
 [ 1.          0.67408663 -0.3282177   0.05039595 -0.00240169]
 [ 1.          0.7640866   0.00511564  0.07539596 -0.00240169]
 [ 0.          0.          0.          0.          0.        ]]
```
How do I know which row of observations is the car on the merged lane ？In addition, how can I get the current Lane ID of ego-vehicle and add it to the observation space?
Looking forward to your reply.
Thanks!

**Comment by eleurent** [comment]
Hi, sorry for the late reply

> which row of observations is the car on the merged lane 

it is probably possible to figure it out by looking at the y position (3rd column)

> In addition, how can I get the current Lane ID of ego-

You have to add a new feature to the kinematics observation:
https://github.com/eleurent/highway-env/blob/master/highway_env/envs/common/observation.py#L142

and the corresponding implementation (lane id) can be added here: https://github.com/eleurent/highway-env/blob/master/highway_env/vehicle/kinematics.py#L203
