### ISSUE TITLE
Fixed Angle

### ISSUE THREAD

**Issue by piccupl** [eleurent/highway-env#362]
hi @eleurent , when i set "scaling": 2.5, How to view results from a fixed perspective.
Because my scenario is multi-agent，I can't observe the situation of the later agents.
Looking forward to your reply！

**Comment by eleurent** [comment]
Hi! 
>  Because my scenario is multi-agent，I can't observe the situation of the later agents.

For multi-agent scenario, there are two things we can consider

- agents' observations: these should already be agent-centric if you use the MultiAgentObservation. They are the most important, as they condition the policy being learned.

- the environment rendering: this is just for visualisation purposes, so it is not that important. By default, the window is centered on the position of the first controllable vehicle, see:

https://github.com/eleurent/highway-env/blob/742ce2e69bf00169f2b250e0388c6b9926c026ec/highway_env/envs/common/graphics.py#L149

you can instead focus on another vehicle by manually setting the `env.viewer.observer_vehicle` field, or to a fixed position (as you suggested) by editing the viewer's `window_position()` method (just return `np.array([x, y])`)
