### ISSUE TITLE
Question about continuous control

### ISSUE THREAD

**Issue by SEUCGX** [eleurent/highway-env#364]
Dear authors:
    Thank you for your excellent environment. I found that after training it with the sac algorithm (controller frequency is 1Hz), the vehicle tends to spin in place. Since the reward value only cares about the speed and whether it is in the lane a certain moment , it can get a higher reward. But in reality, it doesn't move forward, it just cheats by taking the higher reward action when checking. I think it makes sense to correct the behavior of the agent by limiting the position of the vehicle during the simulation or modifying the reward  to the change in position, but I don't know how to achieve it.  Although increasing the control frequency might also work, I don't think it's a good solution

**Comment by eleurent** [comment]
Right, I think a good solution would be to reward not the absolute speed, but rather the projection of the velocity on the lane's tangent direction, to ensure that the velocity vector is contributing to change of position in the desired direction.

**Comment by SEUCGX** [comment]
Thank you for your reply. But it still have a problem. The current reward only cares about the speed at a certain moment (seems to be related to the control cycle). So, even if the agent rushes off the track, as long as it can return to the track every time when it is checked, it can get a higher reward.

**Comment by eleurent** [comment]
Right. OK I'm a bit surprised that it happens in practice, I thought the control cycle should be still quite fast compared to the car dynamics. I guess you could either:
- decrease the policy frequency (e.g. so it matches the simulation frequency, and every frame has a matching reward)
- compute and accumulate rewards for intermediate frames, and return the `total step reward` at the end of the step.

**Comment by SEUCGX** [comment]
Thank you for your suggestions

**Comment by yshichseu** [comment]
> Dear authors: Thank you for your excellent environment. I found that after training it with the sac algorithm (controller frequency is 1Hz), the vehicle tends to spin in place. Since the reward value only cares about the speed and whether it is in the lane a certain moment , it can get a higher reward. But in reality, it doesn't move forward, it just cheats by taking the higher reward action when checking. I think it makes sense to correct the behavior of the agent by limiting the position of the vehicle during the simulation or modifying the reward to the change in position, but I don't know how to achieve it. Although increasing the control frequency might also work, I don't think it's a good solution

Hello, I have also been researching the contribution of Highwayenv in continuous control recently, but I have encountered some problems. As a beginner, I would like to ask for your advice, but I cannot find a contact information, so I am leaving a message here

**Comment by SEUCGX** [comment]
> > Dear authors: Thank you for your excellent environment. I found that after training it with the sac algorithm (controller frequency is 1Hz), the vehicle tends to spin in place. Since the reward value only cares about the speed and whether it is in the lane a certain moment , it can get a higher reward. But in reality, it doesn't move forward, it just cheats by taking the higher reward action when checking. I think it makes sense to correct the behavior of the agent by limiting the position of the vehicle during the simulation or modifying the reward to the change in position, but I don't know how to achieve it. Although increasing the control frequency might also work, I don't think it's a good solution
> 
> Hello, I have also been researching the contribution of Highwayenv in continuous control recently, but I have encountered some problems. As a beginner, I would like to ask for your advice, but I cannot find a contact information, so I am leaving a message here

我的邮箱是230218763@seu.edu.cn,欢迎讨论，但我后来放弃了连续控制的设置，可能我更认可强化学习应该用在high-level的控制上，如果有更多连续控制的问题，你可以联系下作者或者在社区提问
