### ISSUE TITLE
A single questing about the generation of the ego-vehicle

### ISSUE THREAD

**Issue by haijime-w** [eleurent/highway-env#366]
Hello,thanks for this great project!! I encountered some problems when I was learning.
I noticed that during the generation of the ego-vehicle, its heading angles were randomly generated, and I wondered how I can set them to 0.
Thanks!!!

**Comment by KexianShen** [comment]
https://github.com/eleurent/highway-env/blob/1d2f281ef0f970afb380b15dbec9da40cc0ba432/highway_env/vehicle/kinematics.py#L84

from here you can find that the heading angle is always along the lane

**Comment by haijime-w** [comment]
Thanks!!! In addition, I would like to ask how to delete vehicles other than ego-vehicle？

**Comment by KexianShen** [comment]
do you mean just create ego-vehicle at the very beginning?

**Comment by haijime-w** [comment]
yes

**Comment by KexianShen** [comment]
```python
import gym
import highway_env

env = gym.make("highway-fast-v0")
env.configure(
    {
        "vehicles_count": 0,
    }
)
obs = env.reset()
print(obs)
```

**Comment by haijime-w** [comment]
Thanks！！！
