### ISSUE TITLE
Questions about the observation radius

### ISSUE THREAD

**Issue by shile1998** [eleurent/highway-env#369]
Two questions about the viewing radius of the ego vehicle, hopefully answered
1. Can the observation radius of the ego vehicle be set?
2. Is its observation only for the vehicle ahead?

**Comment by eleurent** [comment]
I assume you are talking about the (default) kinematics observation.

> Can the observation radius of the ego vehicle be set?

It is set here: https://github.com/eleurent/highway-env/blob/319720e61cc7dc3c8911ab3bdf27de2036f08ab3/highway_env/envs/common/abstract.py#L38

You can change it with 

```
env.PERCEPTION_DISTANCE = ...
```

I should make this an observation config though, this would make more sense.

> Is its observation only for the vehicle ahead?

By default yes, but it can be configured:

https://github.com/eleurent/highway-env/blob/319720e61cc7dc3c8911ab3bdf27de2036f08ab3/highway_env/envs/common/observation.py#L152

e.g.
```
env.configure({'observation': 'see_behind': True}})
```
