### ISSUE TITLE
The argument mode in render method is deprecated.

### ISSUE THREAD

**Issue by qianyeshuilong** [eleurent/highway-env#370]
Hello, author.
I'm excited to leave you a message. I have some problems running the code. I hope you can browse it in your free time and get your help.
When I run sb3_highway_ppo.py and sb3_highway_dqn.py, the program can run normally, but after running for a period of time, such an error will be displayed.I hope to receive your reply, thank you.

![1](https://user-images.githubusercontent.com/106509542/193165108-c3b343af-e279-44b9-9819-d07cdb4d943f.png)

**Comment by eleurent** [comment]
Hi,
Looks like it is just a warning, it should still work for now?

**Comment by qianyeshuilong** [comment]
Thank you. Thank you very much for your answer.
