### ISSUE TITLE
Gym , Stable-baselines3 and Entry points dependencies compilation bug once executing script.

### ISSUE THREAD

**Issue by PatrickYanZ** [eleurent/highway-env#372]
Hi there,

once I execute the https://github.com/eleurent/highway-env/blob/master/scripts/sb3_highway_dqn.ipynb and executing https://github.com/eleurent/highway-env/blob/master/scripts/sb3_highway_dqn.py, I got the following error.

Some dependency upgrades introduce the error below.
1. gym dependency version leads to conflict.
- stable-baselines3 1.6.2a0 requires gym==0.21 but we install gym 0.26.2
- highway-env 1.6 requires gym>=0.25, but you have gym 0.21.0 which is incompatible.

```
  Attempting uninstall: gym
    Found existing installation: gym 0.21.0
    Uninstalling gym-0.21.0:
      Successfully uninstalled gym-0.21.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
stable-baselines3 1.6.2a0 requires gym==0.21, but you have gym 0.26.2 which is incompatible.
```

2. metadata.entry_points() bug. 
 Since importlib-metadata releases v5.0.0 yesterday. it removes the deprecated endpoint. That is why errors raise.
ref: https://stackoverflow.com/questions/73929564/entrypoints-object-has-no-attribute-get-digital-ocean

```
AttributeError                            Traceback (most recent call last)
[<ipython-input-5-30f89a9e5fae>](https://localhost:8080/#) in <module>
----> 1 import gym
      2 from gym. Wrappers import RecordVideo
      3 from stable_baselines3 import DQN
      4 
      5 import highway_env

2 frames
[/usr/local/lib/python3.7/dist-packages/gym/envs/registration.py](https://localhost:8080/#) in load_env_plugins(entry_point)
    248 def load_env_plugins(entry_point="gym.envs"):
    249     # Load third-party environments
--> 250     for plugin in metadata.entry_points().get(entry_point, []):
    251         # Python 3.8 doesn't support plugin.module, plugin.attr
    252         # So we'll have to try and parse this ourselves

AttributeError: 'EntryPoints' object has no attribute 'get'
```

Proposed solution: fix the dependency version if necessary.

Much appreciate your help in advance.

**Comment by eleurent** [comment]
1. Yes absolutely, stable-baselines3 does not currently support gym0.26 (I believe they have an ongoing PR for that, its WIP). So if you want to use stable-baselines3, you need to use a version of highway-env compatible with the previous interface, so you can just install the latest stable version (release) instead of the development version.
2. Thanks for flagging that, I'll look into it

**Comment by PatrickYanZ** [comment]
Thanks @eleurent,

Here is the temporary fix I am done with for the script. I manually configure the dependencies with specific versions as below.
The script works normally but it can not compatible with `highway-env==1.6`.

```
!pip install gym==0.21.0
!pip install highway-env==1.5
!pip install sb3-contrib==1.5.0
!pip install importlib-metadata==4.8.1
```
