### ISSUE TITLE
The Multi-Agent setting

### ISSUE THREAD

**Issue by shile1998** [eleurent/highway-env#377]
Hello, I would like to configure the multi-agent environment highway-v0, but there is little documentation, notice that there is HighwayEnv on the rl-agent, but it does not seem to be a multi-agent, it should be the code for this article "B-GAP: Behavior-Guided Action Prediction for Autonomous Navigation"? How can I quickly configure the multi-agent environment of highway-v0, especially the model part.Is there a more detailed description ？

**Comment by eleurent** [comment]
Hello,

> How can I quickly configure the multi-agent environment of highway-v0

See the [documentation](https://highway-env.readthedocs.io/en/latest/multi_agent.html#the-multi-agent-setting).
Let me know if any information is missing from the doc, or if you have a specific question on how to set it up.

> especially the model part

This repository only specifies the environment, not the agent/model part. If you use the eleurent/rl-agents repo for the agent, the DQNAgent does support multi-agent environments. 

There is one configuration of the intersection-v0 env in the multi-agent setting: https://github.com/eleurent/rl-agents/blob/master/scripts/configs/IntersectionEnv/env_multi_agent.json (run this using scripts/experiments.py)

If you want to enable it for highway-v0, all you have to do is edit the corresponding environment configuration json file to add more controlled vehicles.

>  it should be the code for this article "B-GAP: Behavior-Guided Action Prediction for Autonomous Navigation"?

I believe the authors of this paper used rl-agents and implemented their work on top of it, you can probably contact them if you want to access their fork.
