### ISSUE TITLE
About acceleration

### ISSUE THREAD

**Issue by Daichief** [eleurent/highway-env#378]
hi, what is the acceleration of FASTER in [IDLE, FASTER, SLOWER, LANE-RIGHT and LANE-LEFT.]?

**Comment by Daichief** [comment]
And, another qusition is that Is the coordinate point of the car in the middle or in the front of the car?

**Comment by eleurent** [comment]
Hi,
> what is the acceleration of FASTER in [IDLE, FASTER, SLOWER, LANE-RIGHT and LANE-LEFT.]?

It is a time-varying acceleration: FASTER/SLOWER change the speed setpoint of the vehicle, and the resulting acceleration is the output of a speed controller: https://github.com/eleurent/highway-env/blob/master/highway_env/vehicle/controller.py#L146

> And, another qusition is that Is the coordinate point of the car in the middle or in the front of the car?

The middle of the car
