### ISSUE TITLE
Can I customize the initial position and speed of surrounding cars?

### ISSUE THREAD

**Issue by yfxcore** [eleurent/highway-env#381]
Dear Eleurent,
Can I customize the initial position and speed of surrounding cars?  I found I could set the position and speed of controlled car, but could not find where to do with other cars. Do you have any hint? Thank you :)

**Comment by eleurent** [comment]
Hi,
This is not configurable, but you can manually edit the way other vehicles are created in the `_make_vehicles()` method of every environment.

**Comment by linhlpv** [comment]
Hi @eleurent,
Thank you for your replying. I just wanna as a small question to make it more clear a little bit. 
So to change to speed of the surrounding cars, I just need to change the value of the `speed` variable in the `_make_vehicles()` method, and when the `speed` variable is not `None` (I pass the value for it), the surrounding car's speeds are set to fixed value as the `speed` value. Do I miss anything?
Thank you so much.

**Comment by eleurent** [comment]
That's almost correct: when the initial speed is set to none, the speed is [initialised to a random value](https://github.com/Farama-Foundation/HighwayEnv/blob/master/highway_env/vehicle/kinematics.py#L74) in some range
