### ISSUE TITLE
ValueError: not enough values to unpack (expected 5, got 4)

### ISSUE THREAD

**Issue by zsn2021** [eleurent/highway-env#382]
Do you have this problem?
How can I solve it？

**Comment by eleurent** [comment]
What version of highway-env are you using, and which script are you running?

**Comment by Berk035** [comment]
Hello, 

Firstly, you can explain explicitly the bug you deal with. I know that the problem is caused by gym version. gym==0.26.2 has truncated variable in env.step() returns. You can install gym==0.21. 

Have a nice day.

**Comment by zsn2021** [comment]
> First of all, thank you for your reply
I tried your method and solved the problem
Wish you a happy life

**Comment by TongshenH** [comment]
> 

HELLO, I install gym gym==0.21.0, but it shows the same problem.

**Comment by eleurent** [comment]
>  I know that the problem is caused by gym version. gym==0.26.2 has truncated variable in env.step() returns. 

That is correct. So the solution depends on what your agent code expects.
If it does something like `obs, reward, done, info = env.step(action)`, then it expects a gym <0.25 version, and you should install a previous release of highway-env that was compabible.
If, on the other side, your agent uses the NEW step api of gym >= 0.26 (`obs, reward, done, truncated, info = env.step(action)`, then you should install the latest stable (or development) version of highway-env

**Comment by zsn2021** [comment]
> > I know that the problem is caused by gym version. gym==0.26.2 has truncated variable in env.step() returns.
> 
> That is correct. So the solution depends on what your agent code expects. If it does something like `obs, reward, done, info = env.step(action)`, then it expects a gym <0.25 version, and you should install a previous release of highway-env that was compabible. If, on the other side, your agent uses the NEW step api of gym >= 0.26 (`obs, reward, done, truncated, info = env.step(action)`, then you should install the latest stable (or development) version of highway-env

Thank you for your reply. The highway environment you developed has greatly helped me. You are an excellent researcher！
