### ISSUE TITLE
The finite_mdp module is required for conversion

### ISSUE THREAD

**Issue by ningwak** [eleurent/highway-env#383]
Hi!
I am trying with the value iteration algorithm. It keeps reporting "The finite_mdp module is required for conversion". 
`module = importlib.import_module("finite_mdp.mdp")`
I haven't found the "mdp" defined under "finite_mdp" and I am also confused about where the function `module.DeterministicMDP` is defined.

**Comment by eleurent** [comment]
You should install it from there: https://github.com/eleurent/finite-mdp

**Comment by ningwak** [comment]
> You should install it from there: https://github.com/eleurent/finite-mdp

Thank you very much! Now it works
