### ISSUE TITLE
Unable to render the environment

### ISSUE THREAD

**Issue by root221** [eleurent/highway-env#384]
Hi,

I had the same problem. I have done all the suggestions in [114](https://github.com/eleurent/highway-env/issues/114), but I'm still getting black images. I am using gym==0.22 and highway-env==1.5. How can I solve it？Thanks

**Comment by ydcttt** [comment]
Do you have any solution? @root221 I also cannot render the mp4 video.
![image](https://user-images.githubusercontent.com/18325529/205863480-289455bb-7312-433e-bcd4-b4583d76ad21.png)

**Comment by eleurent** [comment]
Sorry for missing your message, let me know if you still require help
