### ISSUE TITLE
Hello, dear author, I would like to ask some questions,

### ISSUE THREAD

**Issue by like2000522** [eleurent/highway-env#386]
I just run the Monte-Carlo Tree Search. 
First question: I would like to ask what do the changing images displayed below the driveway represent？
Second question: Where are the codes of the following values
These are some questions I would like to ask. If you could answer me, I would be very grateful. I hope I didn't bother you.
![PL$7Z@`$32V2WQA{U{B@I9E](https://user-images.githubusercontent.com/108260186/201679224-9b4b01b5-383d-4fdd-a673-47117ae1ceb5.png)

**Comment by eleurent** [comment]
Sorry for the very late reply:
>  First question: I would like to ask what do the changing images displayed below the driveway represent？

it represents the search tree: each square is a node, and the square to its right corresponds to its children (one for each action, and the resulting next state)

> Second question: Where are the codes of the following values

in the rl_agents repo, deep_q_network/graphics.py
