### ISSUE TITLE
[Feature] Allow `config` to be set in `reset(options=...)`

### ISSUE THREAD

**Issue by pseudo-rnd-thoughts** [eleurent/highway-env#388]
Thanks for the project, it is very high quality.
Would it be possible for the configures, in particular, `.config` to be set at the `option` parameter in `reset` as this is the spirit of the API?

Im happy to add the PR if you are interested

**Comment by eleurent** [comment]
Hi! Yes I agree that this would be more suitable to this new API, great idea. 

If you are willing to implement it, I will be happy to review your PR :)
