### ISSUE TITLE
The install of the project

### ISSUE THREAD

**Issue by zhangxinchen123** [eleurent/highway-env#39]
Hello! When i run the command in the terminal , the terminal tell me successfully,but i can't find the project in my computer, how can i do next ? Thanks for your reply!!

**Comment by eleurent** [comment]
Hi, if you installed the project with `pip install` you can use it _as is_ in a python script such as:
```
import gym
import highway_env

env = gym.make("highway-v0")

done = False
while not done:
    action = env.action_space.sample()       # Your agent code here
    obs, reward, done, info = env.step(action)
    env.render()
```

But if you want to explore/modify the project you should rather uninstall it and clone it locally.

**Comment by zhangxinchen123** [comment]
yes，i run create a python flie and the terminal tell me ImportError: No module named 'highway_env'
， i don‘t know how i do next，Thanks for your reply！

**Comment by zhangxinchen123** [comment]
> Hi, if you installed the project with `pip install` you can use it _as is_ in a python script such as:
> 
> ```
> import gym
> import highway_env
> 
> env = gym.make("highway-v0")
> 
> done = False
> while not done:
>     action = env.action_space.sample()       # Your agent code here
>     obs, reward, done, info = env.step(action)
>     env.render()
> ```
> 
> But if you want to explore/modify the project you should rather uninstall it and clone it locally.

Thanks, if i want to use DQN to train the vehicle,how i will do next ? thanks a lot ! !

**Comment by zhangxinchen123** [comment]
> Hi, if you installed the project with `pip install` you can use it _as is_ in a python script such as:
> 
> ```
> import gym
> import highway_env
> 
> env = gym.make("highway-v0")
> 
> done = False
> while not done:
>     action = env.action_space.sample()       # Your agent code here
>     obs, reward, done, info = env.step(action)
>     env.render()
> ```
> 
> But if you want to explore/modify the project you should rather uninstall it and clone it locally.

I download the rl-agents and run the command "python3 experiments.py evaluate envs/cartpole.json agents/dqn.json --train --episodes=200" but the terminal tell me "No module named 'docopt'"

**Comment by eleurent** [comment]
To install the dependencies, run `pip install -e . ` in the `rl-agents `directory.
Then, 
```
cd scripts
python3 experiments.py evaluate configs/CartPoleEnv/env.json configs/CartPoleEnv/DQNAgent.json  --train --episodes=200
```

**Comment by zhangxinchen123** [comment]
> To install the dependencies, run `pip install -e . ` in the `rl-agents `directory.
> Then,
> 
> ```
> cd scripts
> python3 experiments.py evaluate configs/CartPoleEnv/env.json configs/CartPoleEnv/DQNAgent.json  --train --episodes=200
> ```

Thanks , but when i run this command, the terminal tell me "[ERROR] Preferred device cuda:best unavailable, switching to default cpu " is this use gpu to train? and another error is"TypeError: argument should be string, bytes or integer, not PosixPath " , i have install the dependencies. Thanks for your help ! !

**Comment by eleurent** [comment]
The first error should be a warning, it is due to the fact that the GPU is selected in the configuration file, but when unavailable the CPU is used instead so you should be fine.
Can you tell me which file/line gives you the second error exactly?

**Comment by eleurent** [comment]
By the way, I noticed a regression caused by the use of the smoothed L1 loss instead of the L2 loss by default. I just fixed it in https://github.com/eleurent/rl-agents/commit/5244ce929a75ba3c73db4c7ad8a83b92b5e9c83c
You should update and reinstall rl-agents, or alternatively you can add the following line to the `scripts/configs/CartPoleEnv/DQNAgent.json` configuration file:
`    "loss_function": "l2"`

**Comment by zhangxinchen123** [comment]
> The first error should be a warning, it is due to the fact that the GPU is selected in the configuration file, but when unavailable the CPU is used instead so you should be fine.
> Can you tell me which file/line gives you the second error exactly?

ok, thanks a lot, the terminal tell me the full information is that:
INFO: Making new env: CartPole-v0
[INFO] This environment does not support configuration. 'CartPoleEnv' object has no attribute 'configure' 
[ERROR] Preferred device cuda:best unavailable, switching to default cpu 
Traceback (most recent call last):
  File "experiments.py", line 148, in <module>
    main()
  File "experiments.py", line 43, in main
    evaluate(opts['<environment>'], opts['<agent>'], opts)
  File "experiments.py", line 75, in evaluate
    display_rewards=not options['--no-display'])
  File "/home/zxc/.local/lib/python3.5/site-packages/rl_agents/trainer/evaluation.py", line 76, in __init__
    video_callable=(None if self.display_env else False))
  File "/home/zxc/.local/lib/python3.5/site-packages/rl_agents/trainer/monitor.py", line 28, in __init__
    super(MonitorV2, self).__init__(env, directory, video_callable, force, resume, write_upon_reset, uid, mode)
  File "/usr/local/lib/python3.5/dist-packages/gym/wrappers/monitor.py", line 27, in __init__
    write_upon_reset, uid, mode)
  File "/home/zxc/.local/lib/python3.5/site-packages/rl_agents/trainer/monitor.py", line 32, in _start
    super(MonitorV2, self)._start(directory, video_callable, force, resume, write_upon_reset, uid, mode)
  File "/usr/local/lib/python3.5/dist-packages/gym/wrappers/monitor.py", line 67, in _start
    if not os.path.exists(directory):
  File "/usr/lib/python3.5/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: argument should be string, bytes or integer, not PosixPath
How can i solve this problem? thanks for you help ! !

**Comment by eleurent** [comment]
Ah, I see, this is because I use the `Path` library of Python 3 and gym uses the old Python 2 `os.path`. Moreover, `os.path.exists` [only supports path-like objects since Python 3.6](https://python.readthedocs.io/en/stable/library/os.path.html#os.path.exists).
I did not get the error since I am using Python 3.7, but you did because you use Python 3.5.

Can you try with a more recent version of Python? I will probably add a fix anyway.

**Comment by zhangxinchen123** [comment]
> Ah, I see, this is because I use the `Path` library of Python 3 and gym uses the old Python 2 `os.path`. Moreover, `os.path.exists` [only supports path-like objects since Python 3.6](https://python.readthedocs.io/en/stable/library/os.path.html#os.path.exists).
> I did not get the error since I am using Python 3.7, but you did because you use Python 3.5.
> 
> Can you try with a more recent version of Python? I will probably add a fix anyway.

oh,when i revise the code in the monitor.py, the error is the same to the behind, however, thanks for your help !

**Comment by zhangxinchen123** [comment]
> Ah, I see, this is because I use the `Path` library of Python 3 and gym uses the old Python 2 `os.path`. Moreover, `os.path.exists` [only supports path-like objects since Python 3.6](https://python.readthedocs.io/en/stable/library/os.path.html#os.path.exists).
> I did not get the error since I am using Python 3.7, but you did because you use Python 3.5.
> 
> Can you try with a more recent version of Python? I will probably add a fix anyway.

sorry, i met a new error,when i run the command "python3 experiments.py evaluate configs/CartPoleEnv/env.json configs/CartPoleEnv/DQNAgent.json  --train --episodes=200",the terminal tell me:
INFO: Making new env: CartPole-v0
[INFO] This environment does not support configuration. 'CartPoleEnv' object has no attribute 'configure' 
[ERROR] Preferred device cuda:best unavailable, switching to default cpu 
INFO: Creating monitor directory out/CartPoleEnv/DQNAgent/run_20200319-102250_5354
profiler execution failed
Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/config.py", line 558, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/lib/python3.5/logging/config.py", line 731, in configure_handler
    result = factory(**kwargs)
  File "/usr/lib/python3.5/logging/__init__.py", line 998, in __init__
    self.baseFilename = os.path.abspath(filename)
  File "/usr/lib/python3.5/posixpath.py", line 357, in abspath
    if not isabs(path):
  File "/usr/lib/python3.5/posixpath.py", line 64, in isabs
    return s.startswith(sep)
AttributeError: 'PosixPath' object has no attribute 'startswith'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "experiments.py", line 148, in <module>
    main()
  File "experiments.py", line 43, in main
    evaluate(opts['<environment>'], opts['<agent>'], opts)
  File "experiments.py", line 75, in evaluate
    display_rewards=not options['--no-display'])
  File "/home/zxc/rl-agents-master/rl_agents/trainer/evaluation.py", line 79, in __init__
    self.write_logging()
  File "/home/zxc/rl-agents-master/rl_agents/trainer/evaluation.py", line 347, in write_logging
    rl_agents.trainer.logger.add_file_handler(self.run_directory / self.LOGGING_FILE.format(file_infix))
  File "/home/zxc/rl-agents-master/rl_agents/trainer/logger.py", line 77, in add_file_handler
    *logging_config["handlers"]
  File "/home/zxc/rl-agents-master/rl_agents/trainer/logger.py", line 53, in configure
    logging.config.dictConfig(logging_config)
  File "/usr/lib/python3.5/logging/config.py", line 795, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python3.5/logging/config.py", line 566, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'logging.0.5354.log': 'PosixPath' object has no attribute 'startswith'
INFO: Finished writing results. You can upload them to the scoreboard via gym.upload('/home/zxc/rl-agents-master/scripts/out/CartPoleEnv/DQNAgent/run_20200319-102250_5354')
Is this the python version problem? thanks for you help ! !

**Comment by zhangxinchen123** [comment]
> Ah, I see, this is because I use the `Path` library of Python 3 and gym uses the old Python 2 `os.path`. Moreover, `os.path.exists` [only supports path-like objects since Python 3.6](https://python.readthedocs.io/en/stable/library/os.path.html#os.path.exists).
> I did not get the error since I am using Python 3.7, but you did because you use Python 3.5.
> 
> Can you try with a more recent version of Python? I will probably add a fix anyway.

Thanks，now i can run this command，Thanks for you help！！
