### ISSUE TITLE
Disabling video recorder because environment was not initialized with any compatible video mode between `rgb_array` and `rgb_array_list`

### ISSUE THREAD

**Issue by ydcttt** [eleurent/highway-env#393]
Hi, I am running `intersection_social_dqn.ipynb`, I have train the dqn model, but when I want to test, I cannot get the mp4 video. I add the command `img = env.render(mode='rgb_array')` as in the picture, but I still cannot get the video. Need some help.
![image](https://user-images.githubusercontent.com/18325529/205862454-05fa01db-e7bb-49fa-a216-1c6433912c6a.png)

**Comment by ydcttt** [comment]
I use `gym 0.26.2` and `highway-env 1.7`
![image](https://user-images.githubusercontent.com/18325529/205864101-72d6616d-9a01-4e52-8b55-ecb2ebd06954.png)

**Comment by eleurent** [comment]
I fixed the render_mode init and updated the colab, can you confirm that this now works (with the development version)?

**Comment by ydcttt** [comment]
Thanks so much @eleurent, I confirm it works now. I will close this issue.
