### ISSUE TITLE
Vehicle not rendering properly in training

### ISSUE THREAD

**Issue by TheMrguiller** [eleurent/highway-env#395]
Hi,

I am new to RL and I am doing my masters project with this environment. I am trying to render the image using the env.render() funtion, but my car get static and after some instances the image crash. Does it exist a way to render while training, in order to see the progress of the training?

Thank you so much

**Comment by eleurent** [comment]
Hi, please see https://github.com/eleurent/highway-env/issues/393 which seems related.
You should be able to use gym's recordvideo to record a subset of episodes while you are training, see e.g.

```
import gym
from gym.wrappers import RecordVideo

env = gym.make('highway-fast-v0', render_mode='rgb_array')
env = RecordVideo(env,
                  'videos',
                  episode_trigger=lambda e: e == int(e**0.5)**2)  # recording episodes indices which are squares: 1,4,9,16,...

for episode in range(30):
    print(f'Starting episode {episode}')
    env.reset()
    done = False
    while not done:
        action = env.action_space.sample()
        obs, reward, done, truncated, info = env.step(action)
```

**Comment by TheMrguiller** [comment]
Thank you for your quick response. I thought it could be possible to see it in real time while training, but this solution is also quite good. Can i ask you another question? As I am a newbie, i would love to be able to insert vehicles in the parking env. I have seen a issue related to that but i don't quite get why the basic configuration for KinematicsGoal would not be able to include the new vehicles in the observation.

Thank you so much

**Comment by eleurent** [comment]
> I thought it could be possible to see it in real time while training, but this solution is also quite good. 

If you run it on a local machine with a monitor, you should be able to see it in real time (a rendering window should open).

>  As I am a newbie, i would love to be able to insert vehicles in the parking env. I have seen a issue related to that but i don't quite get why the basic configuration for KinematicsGoal would not be able to include the new vehicles in the observation.

Its just that this observation was originally written to support a single vehicle.  It's certainly possible to extend it to support multiple vehicles in the scene, but this has to be implemented. Something like obs = [features of vehicle 1, features of vehicle 2, ... features of vehicle n] and goal = [goal features for vehicle 1, features of vehicle 2, ... features of vehicle n] should do the trick (where vehicle 1 is the controlled vehicle).

**Comment by TheMrguiller** [comment]
The popup screen get frozen after the initial testing of the environment. When the training starts it freezes. Maybe I need to add something else in the config apart from using env.render().

Thank you for your quick answer

**Comment by eleurent** [comment]
Hmmm I'm not sure what is going on...
Does the small code snippet (without training) I posted above work correctly? Or does the popup screen also freeze in that case?

**Comment by TheMrguiller** [comment]
I am working with a previous version of the environment(1.5), due to some problems with the new sb3 updates. I have come with a solution thanks to your code. I had made a wrapper that in every step it renders the image.

Thank you so much
