### ISSUE TITLE
Data Collection from the Highway Simulator, 

### ISSUE THREAD

**Issue by ajam74001** [eleurent/highway-env#397]

**Comment by eleurent** [comment]
Hi, that is because you never set the `done` variable.
Simply do: `obs, reward, done, truncated, info = env.step(action)`

**Comment by eleurent** [comment]
Oh, looks like you figured it out yourself :)

**Comment by ajam74001** [comment]
yeah, thank you a lot :)
so sorry for the inconvenience.

**Comment by eleurent** [comment]
No worries at all!
