### ISSUE TITLE
Code in envs/common/observation.py

### ISSUE THREAD

**Issue by cclvr** [eleurent/highway-env#40]
Thank you for your efforts for this great environment ! 

I found a small problem in envs/common/observation.py line 244 and 245, the" x ", "y" should be "vx","vy"?

Looking forward to your reply.

**Comment by eleurent** [comment]
Hi @cclvr, thanks!

The [observed features](https://github.com/eleurent/highway-env/blob/master/highway_env/envs/common/observation.py#L184) are vx and vy (or can be chosen with the `features `parameter), but these feature values are stored in a grid indexed by x and y. This indexing is done [here](https://github.com/eleurent/highway-env/blob/master/highway_env/envs/common/observation.py#L244), where we get the cell corresponding to an `x, y` position.

I may be mistaken, but for now it seems alright to me. Why do you think it should be `vx `and `vy`?

**Comment by cclvr** [comment]
Hi @eleurent , thanks for your reply. When I ran the code, there existed key errors in "self.features_range["x"] "and "self.features_range["y"] " in line 244 and 245. Then I changed them into "self.features_range["vx"]" and " self.features_range["vy"] ", no errors showed up any more, but the obs output was zero matrix which is meaningless  Then I also changed "vehicle["x"]"  and "vehicle["y"]" in these two lines into "vehicle["vx"]"  and "vehicle["vy"]" , then the output seems meaningful. So I wonder is there something wrong here?

**Comment by eleurent** [comment]
Hi, I could reproduce the issue, thanks a lot for the feedback! I'll push a fix.

**Comment by eleurent** [comment]
I could not see this bug previously because I included `"x"` and `"y"` in the `"feature_range"` field in my own configuration.
Remember that you can play with the `"grid_size"` and `"grid_step"` configs to set the size and accuracy of the grid.
