### ISSUE TITLE
Some angles of the arc road cannot be drawn

### ISSUE THREAD

**Issue by lostboy233333** [eleurent/highway-env#402]
Dear Author,
Thank you very much for your wonderful work!   I got some problems when I was customizing the environment, hope to get some advice from you~ I found that in some cases the arc road could not be drawn. For example, in the following picture, the arc segment with an Angle of 180 to 90 could not be drawn, so my road could not be closed. I wonder if you have any good solutions? Thank you very much for taking the time to answer my questions.
![image_4](https://user-images.githubusercontent.com/108974623/209663733-647e2386-4148-4323-821f-e2c72742dd9f.png)

**Comment by eleurent** [comment]
Hi, 
Not sure what's going on, could you please share your code so I can take a look?

**Comment by lostboy233333** [comment]
Hi,
 Thanks for replying. This is my code. I drew a picture so that you can understand it better.  Thanks again~


| |
lostboy_peterpan
|
|
***@***.***
|
---- Replied Message ----
| From | Edouard ***@***.***> |
| Date | 12/27/2022 23:36 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [eleurent/highway-env] Some angles of the arc road cannot be drawn (Issue #402) |

Hi,
Not sure what's going on, could you please share your code so I can take a look?

**Comment by lostboy233333** [comment]
Dear Author：
Maybe I should make the problem with my code a little bit clearer. When I drew the arc from h to a, 180 to 90 degrees is not going to work. But I can draw -180 to -90, and that's what happens in that picture. My environment is based on racetrack. Thank you so much for reading my code and giving me some suggestions.

**Comment by lostboy233333** [comment]
> Hi, Not sure what's going on, could you please share your code so I can take a look?

**Comment by lostboy233333** [comment]
> Hi, Not sure what's going on, could you please share your code so I can take a look?

Dear Author：
Maybe I should make the problem with my code a little bit clearer. When I drew the arc from h to a, 180 to 90 degrees is not going to work. But I can draw -180 to -90, and that's what happens in that picture. My environment is based on racetrack.  I sent the code to you by email. Thank you so much for reading my code and giving me some suggestions.

**Comment by lostboy233333** [comment]
Strangely enough, I put a 180 to 90 degree command from another environment into this environment and no bugs appear, even though their code is the same. Thank you again for the excellent environment！

**Comment by eleurent** [comment]
Hi, sorry for the late reply.
I did not receive your code unfortunately
I think what could have gone wrong is that the `start_phase` and `end_phase` arguments but be increasing/decreasing depending on the `clockwise` argument. So you could try to either flip the `clockwise` boolean, or add +/-360 to one of these phases to satisfy the monotony constraint, e.g. replace `180->90 `by `-180 -> 90` or `180 -> 450`.
