### ISSUE TITLE
Save manual control actions

### ISSUE THREAD

**Issue by tingtingLiuLiu** [eleurent/highway-env#403]
Hello, author! I have a question. when i set the manual control is true, i would like to record discrete actions. How can I do this please? I look forward to your reply!

**Comment by eleurent** [comment]
Hi! This is not supported at the moment, but here is where the discrete actions are handled with manual control:

https://github.com/eleurent/highway-env/blob/3f569cfa766b454d545fcf048be3f7fb46f8a11a/highway_env/envs/common/graphics.py#L179

You can edit this code to save the actions, e.g. in some global variable.
