### ISSUE TITLE
Manual Control

### ISSUE THREAD

**Issue by liuqi1998** [eleurent/highway-env#405]
How to accelerate in manual mode?

**Comment by eleurent** [comment]
This depends on the selected action type, but generally you can find the controls here:

https://github.com/eleurent/highway-env/blob/d33b57ae73c233e59c86180f1d1d460964b026a6/highway_env/envs/common/graphics.py#L165

TLDR: right key for discrete actions, and up key for continuous actions (not consistent, I know...)
