### ISSUE TITLE
Question about intersection env-DQN

### ISSUE THREAD

**Issue by HodaHo** [eleurent/highway-env#408]
First of all, thanks for your great work
I want to run the code (Training a DQN with social attention on `intersection-v0)  in Jupiter notebook Anaconda (not in Google Colab), but I get an error message. How can I do this? Is there a file with the format (.py) like (sb3_highway_dqn.py) for intersection training? If the answer is no, how do I modify the Google Colab code?

**Comment by eleurent** [comment]
Hi!

> I want to run the code (Training a DQN with social attention on `intersection-v0) in Jupiter notebook Anaconda (not in Google Colab), but I get an error message. How can I do this

Yes this should be possible. What is the error message that you get?

> Is there a file with the format (.py) like (sb3_highway_dqn.py) for intersection training? If the answer is no, how do I modify the Google Colab code?

No, but you can just copy all the code from the colab to a .py python script and it should do the trick :)

**Comment by HodaHo** [comment]
Thanks for your reply,
I want to change the intersection env as follows(Please see the attached image):
1- I would like to convert each lane to multiple lanes (ie increase the number of lanes per direction), despite explaining how to do this in a highway environment, it is not possible in an intersection environment. How can I do this?

2- I want to specify the points of origin and destination of ego vehicle, that is, to move from any desired lane to any specified desired lane. In other words, the left turn itself includes several destinations, of which I want to specify one (For example, training once to start from s1 to o1 and another time training to start from s1 to o2 and ...). How can this feature be added to the codes?
![photo3253842319](https://user-images.githubusercontent.com/122694155/217079554-08d8179c-db1d-4ae2-93b8-a2897c44c397.jpg)

Best regards

**Comment by eleurent** [comment]
Hi, sorry for the late reply.

1. you would have to manually edit this function:

https://github.com/eleurent/highway-env/blob/ffb35eacdfb2671623dc12d99b2ed5b6cb76e531/highway_env/envs/intersection_env.py#L128

to include more parallel lanes segments, by setting their start/end positions. Note that you can give the same start/end node identifier (things like "ir0" in [my convention](https://github.com/eleurent/highway-env/blob/master/highway_env/envs/intersection_env.py#L139)) to several parallel lanes that belong to the same 'road segment' to allow vehicles to perform lane changes between them (while following a given route = path in the graph).

2. Yes this feature is already present in the code, you can set the ego-vehicle's destination as part of the config: 
https://github.com/eleurent/highway-env/blob/ffb35eacdfb2671623dc12d99b2ed5b6cb76e531/highway_env/envs/intersection_env.py#L48
and its route will be computed automatically as the shortest path in the topological graph

**Comment by HodaHo** [comment]
thank you for your reply,
With previous checks, I had realized that I should edit the following function
def _make_road(self) -> None:,
but Given that I am a beginner in Python, how should I edit the function clearly? Would it be possible for you to post the modified code? As you mentioned, I want each side of the intersection to have multiple parallel lanes, the surrounding cars will randomly change lanes between these lanes or go straight, before arriving at the intersection. moreover, they turn right/left or go straight, at the intersection. With these conditions, the ego car must be able to make a decision and turn. This means that, for example, the ego car may face two incoming cars at the same time and can perform the appropriate maneuver in this situation. If possible, send the code of this request. 
Thanks

**Comment by eleurent** [comment]
> but Given that I am a beginner in Python, how should I edit the function clearly? Would it be possible for you to post the modified code? 

Sorry, I'm happy to provide advice and guidance but I'm maintaining this repo on my free time, I can't do it for you.

> 2- How can I define and add some new destinations such as o2 and o3 like o1?

You can follow the examples in make_road: you need to first define the geometry of a lane segment (straight, circle etc), and then the topology of this lane segment in the road network: i.e. what are the start/end abstract nodes that this lane connects (this is used by vehicles to select which lane to track next at intersections, plan routes, etc)
These nodes are only defined by their identifier (string) when you add a lane to the network, with `net.add_lane(start_node_id, end_node_id, lane_geometry)`
