### ISSUE TITLE
problem of combining multiple observations

### ISSUE THREAD

**Issue by Mingjie-He** [eleurent/highway-env#410]
Hi dear @eleurent. First of all, thanks for your great work.
I've read a paper 'Highway Lane Change Decision-Making via AttentionBased Deep Reinforcement Learning' in which the obervation type use both the ' Kinematics' and the 'Grayscale Image'. Does this mean that the idea of combining multiple inputs is feasible？And how do you think the way to realise the multiple inputs idea.
Thank you for reading and look forward to your reply

**Comment by eleurent** [comment]
> I've read a paper 'Highway Lane Change Decision-Making via AttentionBased Deep Reinforcement Learning' in which the obervation type use both the ' Kinematics' and the 'Grayscale Image'. Does this mean that the idea of combining multiple inputs is feasible？

In that paper we only used either the Kinematics OR the grayscale image, not both at the same time.

However, it is indeed certainty feasible to use both: it is even already supported by the TupleObservation:

https://github.com/eleurent/highway-env/blob/d33b57ae73c233e59c86180f1d1d460964b026a6/highway_env/envs/common/observation.py#L492

You just need to set up your network architecture accordingly, e.g. you could use a CNN on the image and attention/mlp on the kinematics array, concatenate the two embeddings, and have a prediction head on top.

**Comment by wodnmd** [comment]
ok! Thanks for your help. @eleurent
