### ISSUE TITLE
Time limit should be on truncated, not on terminated

### ISSUE THREAD

**Issue by LucasAlegre** [eleurent/highway-env#415]
From my understanding, the methods is_terminated and is_truncated of Highway env should be:

```
def _is_terminated(self) -> bool:
    """The episode is over if the ego vehicle crashed or the time is out."""
    return (self.vehicle.crashed or
            self.config["offroad_terminal"] and not self.vehicle.on_road)
            

def _is_truncated(self) -> bool:
    return self.time >= self.config["duration"])
```

The reason is that we should not consider the state in which the time limit is reached as a terminal state.

**Comment by eleurent** [comment]
Hi Lucas,
I kind of agree, and that is what I initially implemented when I transitioned to gym 0.26 API.
But there is one issue: from gym's description of the semantics (this was discussed in some issue that I need to find again) termination ought to be used when an env reset is required, and truncation when no reset is required and the simulation could continue.
Yet, in highway-env after some time (e.g. the default duration), the agent will have passed all other vehicles in the scene, and will be alone on the road. So this situation requires either an env reset (the current situation), or alternatively implementing a mechanism to spawn vehicle in the vicinity (front) of the agent, and clear vehicles to far away. But this is not there at the moment.

**Comment by LucasAlegre** [comment]
According to the documentation: https://gymnasium.farama.org/api/env/

terminated (bool) – Whether the agent reaches the terminal state (as defined under the MDP of the task) which can be positive or negative. An example is reaching the goal state or moving into the lava from the Sutton and Barton, Gridworld. If true, the user needs to call [reset()](https://gymnasium.farama.org/api/env/#gymnasium.Env.reset).

truncated (bool) – Whether the truncation condition outside the scope of the MDP is satisfied. Typically, this is a timelimit, but could also be used to indicate an agent physically going out of bounds. Can be used to end the episode prematurely before a terminal state is reached. If true, the user needs to call [reset()](https://gymnasium.farama.org/api/env/#gymnasium.Env.reset).

In that case, reset should be called if `terminated or truncated`

**Comment by eleurent** [comment]
Hi Lucas, 
Sorry for the late reply. I could not find the discussion/issue I was referring to above, but you're right, the current gymnasium documentation is very clear and highway-env should be aligned with that.
