### ISSUE TITLE
How to increase the speed of IDM vehicle

### ISSUE THREAD

**Issue by phil695** [eleurent/highway-env#417]
Hello, thanks for your great work!  I set the initial speed of IDM vehicle to range 28~32。But the speed of IDM vehicle  seems not so fast  after the initial state. How to set the parameters to get higher speed for IDM vehicle 

thanks!

**Comment by eleurent** [comment]
Hi, 
Depending on how you create the vehicles, their `target_speed` could be lower that their initial speed, possibly.
You could try to set this `target_speed` attribute directly (or just print its value to confirm that this is the cause of issue).
