### ISSUE TITLE
How to implement driving from indexA -> indexB -> indexC -> ........

### ISSUE THREAD

**Issue by haolilili** [eleurent/highway-env#420]
Hi @eleurent, 

I'm trying to give the ego-vehicle a planned route, and make it follow the route,

- start at the south entry (se) of the right roundabout
- leave the right roundabout via the west exit (wx) (enter the left roundabout via "wx")
- leave the left rounabout via east exit (ee) (enter the right roundabout via "ee")
- loop this cycle
![2023-02-27 00-35-22 的屏幕截图](https://user-images.githubusercontent.com/115365057/221447552-672531c5-fb6e-467a-959e-15c66c243d44.png)

I see, in road.py, you've defined several functions, 

`def next_lane (self, current_index: LaneIndex, route: Route = None, position: np.ndarray = None,
                  np_random: np.random.RandomState = np.random)`
`def next_lane_given_next_road (self, _from: str, _to: str, _id: int,
                                  next_to: str, next_id: int, position:`

Few points i got stuck,

-If i use function `next_lane`, how to define the parameter "Route",  is it an index used to describe a tuple[start, end, route_number] which is equavilent to the current_index ? 

-If i use function `next_lane_given_next_road`, how can i define the parameter "Position"

-After the definations of them, where to send them. 

This video shows my other planned trajectory, which goes from the south entry of left roundabout to the right handside highway. As you see, it takes the minimum path between start and end point automatically. BUT, if i wish it travelling a different path, how can i achieve it?
https://user-images.githubusercontent.com/115365057/221671052-00979ff5-1e79-4483-aac7-9e2665ce8a91.mp4

Thank you for your reply!

**Comment by eleurent** [comment]
Hi,
> how to define the parameter "Route", is it an index used to describe a tuple[start, end, route_number] which is equavilent to the current_index ?

the route is a list of LaneIndex, where LaneIndex is the tuple (start node, end node, lane number)

> If i use function next_lane [...], -If i use function next_lane_given_next_road...

You are not really supposed to use them directly.
Usually, after creating the road network and ego-vehicle, you can just define its route (sequence of LaneIndex) automatically by calling `plan_route_to(node_destination)`. See e.g.:

https://github.com/eleurent/highway-env/blob/abcef8da79dedf0dfdbe2db5b176d6f203366489/highway_env/envs/roundabout_env.py#L150

This simply select the shortest path in the road network. But if you want, you can also edit the vehicle.route manually to choose another path: you have to provide a sequence of LaneIndex (start, end, number) such that the next start matches the previous end. See e.g. the implemetation of `plan_route_to`:

https://github.com/eleurent/highway-env/blob/abcef8da79dedf0dfdbe2db5b176d6f203366489/highway_env/vehicle/controller.py#L62

If you want an infinite loop between the two roundabouts, you can just create a very long list, or update it whenever it is empty.

**Comment by haolilili** [comment]
Appreciate !

Besides, when I make env "intersection-V0", I got TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'
I've tried numpy version 1.10--1.24, but they don't work. 
May i know your numpy version?

thanks

**Comment by eleurent** [comment]
Mmmmh, that's weird, the translation_axis should never be None (this is not a problem related to numpy).

I don't see how that can happen: this line is called after the two for-loops which should initialise the min_distance and translation_axis to non-None values at least once (unless will_intersect is false, but then the line is not called).

I have not managed to reproduce the issue, can you share more information about the error. For instance, can you add a `print(a, b, displacement_a, displacement_b)` at the beginning of `are_polygons_intersecting`, so I can reproduce the issue with the same inputs and investigate?

**Comment by haolilili** [comment]
Thank you for replying me, I just solved this, after I copied the newest version of "intersection-v0"
