### ISSUE TITLE
Fix rendering position

### ISSUE THREAD

**Issue by OscarBastardo** [eleurent/highway-env#422]
Hello,

Is it possible to configure a scenario like `intersection-v0` with a "fixed" view of the intersection? I am working on the multi-agent setting, so it does not make sense in my case for the rendered area to be centred on a single ego vehicle.

Thanks.

**Comment by eleurent** [comment]
There is no available configuration for that, but you can edit this function:

https://github.com/eleurent/highway-env/blob/abcef8da79dedf0dfdbe2db5b176d6f203366489/highway_env/envs/common/graphics.py#L149

to just `return np.array([0, 0])` (or any other position)

**Comment by OscarBastardo** [comment]
Hi @eleurent thank you for your reply. 

I came up with a similar solution by passing `np.array([0, 0])` to `move_display_window_to()` in

https://github.com/eleurent/highway-env/blob/abcef8da79dedf0dfdbe2db5b176d6f203366489/highway_env/envs/common/graphics.py#L98
