### ISSUE TITLE
WARN: Unable to save last video! Did you call close()?

### ISSUE THREAD

**Issue by git0929** [eleurent/highway-env#432]
Hello, I want to ask, what is the matter of running the code can not come out of the video, I hope you can answer, thank you！

**Comment by git0929** [comment]
![W3@2_3`Z{~(U9PBF%LWKT$U](https://user-images.githubusercontent.com/116412671/226104617-6635e170-9b33-40c2-8f27-5a9eb49bdd1f.png)

**Comment by eleurent** [comment]
Hi @git0929 , thanks for the feedback I was able to reproduce the issue, it should be fixed now. Let me know
