### ISSUE TITLE
Google Colab examples not working

### ISSUE THREAD

**Issue by super-pirata** [eleurent/highway-env#44]
Hi!
I was checking your project and decided to start by running the [given examples](https://github.com/eleurent/highway-env/tree/master/scripts). Unfortunately, I stumbled upon issues in all of them...

In the first two (parking_model_based.ipynb; highway_planning.ipynb), the problem was that the module `xdpyinfo!` was missing/not found. The output was an error message asking to:  `Please install xdpyinfo!`. I tried `pip install` and `apt-get` it but with no success...

The third one (parking_her.ipynb), returns a message stating `ModuleNotFoundError: No module named 'tensorflow.contrib'`. After reading about it at Tensorflow website, I found out that the module `'tensorflow.contrib'` is [deprecated ](https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md) and the module that your script is trying to access has either migrated or been deleted.

**Comment by eleurent** [comment]
Hi @super-pirata 
Yes, I also noticed that recently. It seems Google Colab stopped supporting virtual display, which was used for rendering the environment in a notebook. I will try to find a way to circumvent that.

I had not seen the tensorflow.contrib issue however, thanks for the feedback I'll investigate.

**Comment by EnormousAdversity** [comment]
HI，I also encountered the same problem, the project cannot run normally, is there a better solution strategy?

**Comment by eleurent** [comment]
Hi @EnormousAdversity, I think that:
- If you want to run the project normally, try to use python scripts (rather than Jupyter notebooks / Google Colab) and everything should be fine.
- If you do not require rendering, then the Jupyter Notebooks / Colab should work as well by simply disabling the rendering (install of xvfb, etc).
- The HER notebook issue with tensorflow.contrib comes from stable_baselines. The original openai baselines implementation could be used instead, try this script: https://github.com/eleurent/highway-env/blob/master/scripts/baselines.py

**Comment by eleurent** [comment]
It seems that Google has fixed the xvfb issues, so the two first notebooks now run smoothly again.

Regarding the notebook for parking with `stable_baselines`, it seems related to the fact that [they do not support tensorflow 2.x yet](https://github.com/hill-a/stable-baselines#installation). Yet, adding a `%tensorflow_version 1.x` line at the beginning does not seem to fix the issue. @araffin any idea?

**Comment by eleurent** [comment]
Nevermind, I forgot to restart the execution environment. Using tensorflow 1.x did the trick.

**Comment by araffin** [comment]
Yes, I had to update the notebooks recently too...
We keep them up to date on the dedicated repo ;)
https://github.com/Stable-Baselines-Team/rl-colab-notebooks
