### ISSUE TITLE
Changes needed for README.md

### ISSUE THREAD

**Issue by mhtb32** [eleurent/highway-env#45]
In `vehicle/dynamics.py` file, the kinematic model is implanted like this:
```Python
v = self.velocity * np.array([np.cos(self.heading), np.sin(self.heading)])
self.position += v * dt
self.heading += self.velocity * np.tan(self.action['steering']) / self.LENGTH * dt
self.velocity += self.action['acceleration'] * dt
```
This is for the model which is based on _rear wheel position_, not _center of gravity position_ mentioned in the README file. Maybe that file needs some corrections.

You can find further explanation [here](https://www.coursera.org/lecture/intro-self-driving-cars/lesson-2-the-kinematic-bicycle-model-Bi8yE).

**Comment by eleurent** [comment]
@mhtb32 you are absolutely right, I originally implemented the rear-wheel convention and (wrongly) wrote center of gravity, and it should be fixed.
But then I changed the rendering to rotate the car around its center of gravity for simplicity, which is inconsistent. Thus, I am actually switching to the center of gravity convention on a development branch, and this will be merged soon to master.
