### ISSUE TITLE
Behaviour is unpredictable when setting Longitudinal = True, for various env's

### ISSUE THREAD

**Issue by Yuvraj-Dhepe** [eleurent/highway-env#496]
Hello @eleurent,
I hope you are doing awesome, from the last time, we took some break in the work of env creation. However, me n my team did few experiments with the environment with the goal to train multiple ego-vehicles, each based on different algorithm and each racing against the other ego-vehicle and dodging the obstacles. 

1) We haven't been able to do that yet, however if you have any suggestions in that directions it will be really great.
---
Rest I was working with the speed component of the ego vehicle and have the following queries:
2) Why the ego vehicle starts moving backward when ```longitudinal=True``` which controls (as much as I understood) speed of ego vehicle in the env, I thought it's a small bug or so, but am not sure, cause in the documentation most of the env's created use ```longitudinal = False``` except the parking env.
- I have the following video that depicts, when I train my model with ```longitudinal = True``` inside the race-track-v0 env, 
![250K DQN mlp policy Train results](https://github.com/Farama-Foundation/HighwayEnv/assets/67863397/27b11839-655f-4f5e-bc5c-c0ee7ba1859a) as you see it's going backwards.

- Following is the (tensorboard log)
![image](https://github.com/Farama-Foundation/HighwayEnv/assets/67863397/0b86f626-5fb6-4cfc-a648-8de349b3b248)
 and it's [env_code](https://gist.github.com/Yuvraj-Dhepe/1b5fdf1b7c7167238ab8375c3a6371f1) from race-track-v0, I haven't edited anything else apart from config

3) Also am not sure why the manual control behaves weirdly with discrete action as you can see in the following gif:
![ezgif com-optimize](https://github.com/Farama-Foundation/HighwayEnv/assets/67863397/aa093ab8-3682-4c9b-b416-0c6a7c09e36e)

**Comment by Yuvraj-Dhepe** [comment]
So basically with manual = True, the car won't move in any other direction except moving only straight...

**Comment by eleurent** [comment]
> My team did few experiments with the environment with the goal to train multiple ego-vehicles, each based on different algorithm and each racing against the other ego-vehicle and dodging the obstacles.  We haven't been able to do that yet, however if you have any suggestions in that directions it will be really great.

One important thing is to ensure that the agents have information about both the tracks and the obstacles/other vehicles. I would maybe try the ImageObseravtion, GridObservation, or a variant of the LidarObservation (which right now only detects obstacles, you'd need to edit it to also detect lane boundaries. You could also just combine it with an observation that contains the lanes information, like Grid/Image).

Then you can probably just train a policy with some fixed / moving obstacles but in a single agent setting (the other cars behaviours are fixed). And see if this generalises to a good multi-agent policy (with OOD behaviours).
Alternatively, you can jointly train a multi-agent policy, a simple baseline is implemented in eleurent/rl-agents (all agents share the same policy, but they observe the effect of jointly changing their behaviour).

>  2) Why the ego vehicle starts moving backward when longitudinal=True which controls (as much as I understood) speed of ego vehicle in the env, I thought it's a small bug or so, but am not sure, cause in the documentation most of the env's created use longitudinal = False except the parking env.

That's not a bug, by default the vehicle can have a negative acceleration, as the action is in [-1, 1] which is mapped to an acceleration range of [-5, 5] m/s2. If the vehicle is motionless and takes a negative acceleration, it will drive backwards. You can disable this by setting the vehicle.MIN_SPEED=0

> Also am not sure why the manual control behaves weirdly with discrete action as you can see in the following gif:

Why do you say that this behaves weirdly exactly? Each discrete action will be mapped to a (acc, steering) command in the range [acc_min, acc_max] x [steering_min, steering_max], so this looks like expected results to me. In particular, repeating the same action multiple times will result in a constant acceleration, and speed buildup (except for the action which have acc=steering=0, but that's a single action in the entire space.

**Comment by Yuvraj-Dhepe** [comment]
Thanks @eleurent me n my team are working as per your suggestions:



> One important thing is to ensure that the agents have information about both the tracks and the obstacles/other vehicles. I would maybe try the ImageObseravtion, GridObservation, or a variant of the LidarObservation (which right now only detects obstacles, you'd need to edit it to also detect lane boundaries. You could also just combine it with an observation that contains the lanes information, like Grid/Image).
> 
> Then you can probably just train a policy with some fixed / moving obstacles but in a single agent setting (the other cars behaviours are fixed). And see if this generalises to a good multi-agent policy (with OOD behaviours). Alternatively, you can jointly train a multi-agent policy, a simple baseline is implemented in eleurent/rl-agents (all agents share the same policy, but they observe the effect of jointly changing their behaviour).
> 
a) That's a really good point to start with, will try that if the deadline time permits us!!

> That's not a bug, by default the vehicle can have a negative acceleration, as the action is in [-1, 1] which is mapped to an acceleration range of [-5, 5] m/s2. If the vehicle is motionless and takes a negative acceleration, it will drive backwards. You can disable this by setting the vehicle.MIN_SPEED=0
>

b) for me modifying the rewards, helped me regarding the -ve speed or the reverse speed of the agent.
 
> Why do you say that this behaves weirdly exactly? Each discrete action will be mapped to a (acc, steering) command in the range [acc_min, acc_max] x [steering_min, steering_max], so this looks like expected results to me. In particular, repeating the same action multiple times will result in a constant acceleration, and speed buildup (except for the action which have acc=steering=0, but that's a single action in the entire space.
>
c) Yup it makes sense why the car just wanted to go in a single straight line
