### ISSUE TITLE
Does it supposed to support Python 2.7? Maybe time to dump it...

### ISSUE THREAD

**Issue by mhtb32** [eleurent/highway-env#51]
Among the code, there are many `__future__` imports for python 2.7 compatibility and in `setup.py`, it is listed as a supported version, but there are many lines that use features from python 3.x, among [this line](https://github.com/eleurent/highway-env/blob/master/highway_env/envs/highway_env.py#L28) in `envs/highway_env.py`:
```Python
config = super().default_config()
```
Which uses kind of `super` call python 2.7 doesn't support.

As python 2.7 [has passed its end of life](https://www.python.org/doc/sunset-python-2/), I suggest dumping all unnecessary future imports and make the code working and clean for just python 3.x(preferably 3.6) and above.

p.s: Pycharm IDE helps find many of python 2.7 incompatibilities as warnings.

**Comment by eleurent** [comment]
You're right, I initially wanted Python 2.7 support  but have since gradually shifted my coding habits to Python 3 syntax at the expense of consistency...
Time to drop it!

**Comment by mhtb32** [comment]
Thank you. Much better now :clap:
