### ISSUE TITLE
Possibility of adding pedestrians

### ISSUE THREAD

**Issue by ndeshp2s** [eleurent/highway-env#53]
Hello,

I there a possibility to add pedestrians in this simulator?

Or is there a possibility to provide support for pedestrians in the near future?

Thank you.

**Comment by ll7** [comment]
The AutomotiveSimulator.jl package might include an inspiration for a pedestrian model.

<https://github.com/sisl/AutomotiveSimulator.jl/blob/master/src/behaviors/sidewalk_pedestrian_model.jl>

**Comment by engyasin** [comment]
Hi @eleurent ,

I'm considered to work on this enhancement, the  behavior model might be social force model.
I'm not sure how to change IDM to avoid pedestrians, but I will look in the literature. 

So basically, the pedestrians (or cyclists) should go basically as another attribute of `Road` object, just like vehicles and controlled_vehicles.

Bests,
