### ISSUE TITLE
Improvement suggestion - Adding action type to config dictionary

### ISSUE THREAD

**Issue by mhtb32** [eleurent/highway-env#54]
The `AbstractEnv` class' default is **discrete** action space and actions. Thus, in continuous action environments such as `parking-env`, a bit of extra work is needed for API user:
```Python
    def define_spaces(self):
        super().define_spaces()
        self.action_space = spaces.Box(-1., 1., shape=(2,), dtype=np.float32)
```
Here, the user should override `action_space` after it is assigned once before in `super().define_spaces()`.

Again in `step()` method, the action is passed to `_simulate()` which expects discrete actions, so one should override `step()` method to manually pass the action to `vehicle.act()` and do rest of steps needed in `step()`, as it is done in `ParkingEnv`.

Although it is not a big deal with the current size of the project, I think this can decrease code reusability in future, and it may be better to add a config keyword like:
```Python
"action": {
    "type": "Continuous"  # or "Discrete"
}
```
And then do some groundwork in `AbstractEnv` class.

**Comment by eleurent** [comment]
Good idea!
And do not hesitate to use Pull Requests to propose new features.
