### ISSUE TITLE
Feature suggestion - Common interface for road objects

### ISSUE THREAD

**Issue by mhtb32** [eleurent/highway-env#56]
As we agree, using objects of type `Obstacle` isn't meaningful and convenient for goals. Also, the `Obstacle` class inherits from `Vehicle` and contains a massive amount of unnecessary overload.

Here is my suggestion for the new interface:

**Common properties:**
- position
- shape (we can stick with rectangular for now)
- heading_angle (for rotation ability)
- dimensions (length and width for rectangle, radius for circle)
- lane
- road

**Common methods:**
- make_on_lane()

Some inherited classes can be `Obstacle` and `Landmark`(or `Goal`).

I suggest refactoring `check_collision()` method the way that it checks intersections with `Landmark` instances regardless of the `COLLISION_ENABLED` property.

Please feel free to add your thoughts to complete the idea.

**Comment by mhtb32** [comment]
**Additional properties for** `Obstacle` **class:**
- hit: bool  (indicating whether the obstacle is hit by any vehicle).

**Comment by mhtb32** [comment]
I can make a draft pull request if you agree. Let me know if you think you should make the changes.

**Comment by eleurent** [comment]
Please do, I'll review the pull request and make changes if necessary.

**Comment by mhtb32** [comment]
Suggestion for future development: [here](https://github.com/eleurent/highway-env/pull/60#issuecomment-622431003)

**Comment by mhtb32** [comment]
In environments with an ego vehicle, some adversary vehicles, and a landmark, one can not use the `hit` property to know if the ego vehicle reached the landmark or not. Instead, she should use `_is_colliding(landmark)`—also, the color of the landmark changes with any other vehicle colliding with it. This is because the landmark's `hit` property is toggled by colliding with any vehicle, not just the ego vehicle.

Implementing this needs changes to the `check_collision()` method. I don't already have an idea for it, but it would be good if we have this problem in mind for future work on this issue.

**Comment by eleurent** [comment]
Yes, good point thank you!
