### ISSUE TITLE
Add proper documentation

### ISSUE THREAD

**Issue by eleurent** [eleurent/highway-env#62]
Currently, only docstring-generated documentation is available.
The _framework_ section of the readme should be moved to ReadTheDocs and illustrated with examples.

Documentation should also be added about:
- Environment configurations
- Observation and action spaces

**Comment by mhtb32** [comment]
Also, I suggest updating animations of episodes of each environment and adding that for all environments that don't have already.

**Comment by mhtb32** [comment]
Is it possible to add more information about the MOBIL model just as you've added for the IDM model?

**Comment by eleurent** [comment]
> 
> 
> Is it possible to add more information about the MOBIL model just as you've added for the IDM model?

Alright!
