### ISSUE TITLE
Regression in IDMVehicle: accelerations are not applied

### ISSUE THREAD

**Issue by eleurent** [eleurent/highway-env#65]
IDMVehicle inherits from ControlledVehicle, so calling super().act() overrides its actions.

Regression introduced in 60f6bca7045ba1305adab89a2efecdecc21ff41b for #51

**Comment by eleurent** [comment]
@mhtb32 you may want to see this (and get the fix).

**Comment by mhtb32** [comment]
Thanks for notice :pray:
