### ISSUE TITLE
New vehicle graphics

### ISSUE THREAD

**Issue by mhtb32** [eleurent/highway-env#70]
I like the minimalistic graphics of the vehicle right now, but tires are not visible enough(if they're meant to be seen at all), So I suggest changing them to something like gym's [racing car](https://gym.openai.com/envs/CarRacing-v0/) graphics.

**Comment by eleurent** [comment]
I'm afraid racing cars do not really fit most environments, which look more like urban/sub-urban scenes.
Tires are only shown for continuous control tasks, they're made more visible by zooming a little bit.
Most of all, I would like to keep it simple. But something could be done to distinguish the front from the rear.
