### ISSUE TITLE
About parking env's  SAC + HER script

### ISSUE THREAD

**Issue by mhtb32** [eleurent/highway-env#72]
Hi, Edouard!

I have a few questions about the script provided for parking env:

- Since the rewards are dense, did you tried algorithms like vanilla DDPG or TD3? If you did, was it successful? I'll be glad if you explain more about the model selection.
- Again with dense rewards, what was the motivation to use HER with SAC? Until the point I know, HER usually does not improve the success rate in environments with dense rewards much. Did it have a significant effect here?

And the last question which I'm not sure here is the best place to ask, and I apologize for it beforehand:

- Are you aware of any work done in multi-goal environments? For example, assume if the vehicle had to reach one point at first and another one later.

Thanks

**Comment by eleurent** [comment]
The original intent was to provide two versions of the parking-env: one with dense rewards for vanilla deep RL algorithms, and one with sparse rewards (goal completion) where these algorithms would fail, to motivate HER.
But eventually, I ended up having other priorities and never took the time to implement everything as I initially wanted.

No, I am not aware of any multi-goal work, at least not in the model-free paradigm.
