### ISSUE TITLE
Unable to achieve "arrived" in intersection_env

### ISSUE THREAD

**Issue by jkewang** [eleurent/highway-env#75]
Hi @eleurent , I trained the intersection_env with ppo with the default config and I was surprised to find that the agent didn't arrive target even once. So I print out the info and check the code about the judgment of arrival. The code in highway-env/highway_env/envs/intersection_env.py is written as follows：
`    def has_arrived(self) -> bool:
        return "il" in self.vehicle.lane_index[0] \
               and "o" in self.vehicle.lane_index[1] \
               and self.vehicle.lane.local_coordinates(self.vehicle.position)[0] >= \
               self.vehicle.lane.length - 3 * self.vehicle.LENGTH`

I found the "self.vehicle.lane.length - 3 * self.vehicle.LENGTH" is 85.0 in this case, however even the action is always "2"(acc) for fourteen steps, the agent can only reach 58.57 m, which means that the has_arrived function will never return True in this env with default config. I changed the arrival judgment in myself code and just let you know that it might be a bug during RL training.

**Comment by eleurent** [comment]
You're right, the lanes were initially much shorter (when has_arrived() was written) and have been lengthened since, for visual appearance. Thanks for the notice!
