### ISSUE TITLE
Bug - using obstacle or landmark alongside IDMVehicle

### ISSUE THREAD

**Issue by mhtb32** [eleurent/highway-env#77]
I was trying to use vehicles of type `IDMVehicle` in a custom environment, which I faced an error.

In [this line](https://github.com/eleurent/highway-env/blob/b94c2d058e9ff6a1764d7e16b72bc0822fd1fe15/highway_env/vehicle/behavior.py#L129), the `lane_distance_to()` method is called on an object of type `Landmark`, which clearly doesn't have this method. I traced the code to see how `ego_vehicle` can become of type `Landmark` and it turned out that `road.neighbor_vehicles` has set `ego_vehicle` to a `Landmark` object in [this line](https://github.com/eleurent/highway-env/blob/b94c2d058e9ff6a1764d7e16b72bc0822fd1fe15/highway_env/vehicle/behavior.py#L228).

It seems that changes in the commit 9815d9012204058e85bba2def180e2bc7983a922 cause this.

I suggest adding a check like `not isinstance(ego_vehicle, RoadObject)` before executing the code on line 129 of behavior.py mentioned above since road objects can not accelerate at all

**Comment by mhtb32** [comment]
Is this commit enough? Or you've planned more fundamental changes?

**Comment by eleurent** [comment]
No, it seems alright to me. I'll cherry-pick it.
