### ISSUE TITLE
Using type checkers in the build workflow?

### ISSUE THREAD

**Issue by mhtb32** [eleurent/highway-env#90]
For maintaining code quality along the development way and minimize runtime errors that are not caught with unit tests, one can use type checkers.

Some type checkers can just analyze type annotated code(which is not a big concern since #57), like [mypy](https://github.com/python/mypy)  and some can infer types when confronting with not type annotated code, like [pytype](https://github.com/google/pytype). I prefer the latter, which allows us to have non-typed code along with typed code, which may be a case in the future for some reason, and again benefit from a type checker's benefits.

What's your opinion? Do you think adding type checkers might help, or it's just an overkill?

**Comment by eleurent** [comment]
I initially thought that including static code analysis tools in the build status was a bit too constraining, and preferred simply having them monitored so as to keep track of issues in a non-blocking way. So I turned to [Codacy](https://app.codacy.com/manual/eleurent/highway-env) which includes several tools:
* Bandit 1.6.2
* Prospector 1.2.0
* PyLint (Python 3) 2.5.2
* RemarkLint 7.0.0 

But they do not seem to include type checking. It would be great to add pytype/mypy, but they do not seem to be supported by Codacy. Adding them to the build workflow is a possibility, however. I may give it a try.
