### ISSUE TITLE
Road to v1.0 stable?

### ISSUE THREAD

**Issue by mhtb32** [eleurent/highway-env#93]
I want to ask if you have any roadmap in mind for first stable version? It can help other repositories using highway-env, by not having to change their code frequently because of changes in the highway-env.

**Comment by narutoten520** [comment]
Hello, @mhtb32 , is that possible to add the DDPG et al. for the continuous space in Highway-env? I have tried to use DDPG+HER to realize this, but failed. Thanks in advance.

**Comment by mhtb32** [comment]
@narutoten520 highway-env package is a collection of gym environments itself and has nothing to do with the RL models you want to train. The DDPG model needs continuous action environments, and any highway-env environment with continuous actions can be used for training a DDPG agent, like `parking-v0`. There is a python notebook that trains exactly the DDPG + HER on the `parking-v0` environment using the `stable-baselines` package, which you can check [here](https://colab.research.google.com/github/eleurent/highway-env/blob/master/scripts/parking_her.ipynb).

You can check the [docs](https://highway-env.readthedocs.io/en/latest/) for further information about highway-env, and I suggest you comment on related issues(or make a new one) in the future to ask about highway-env functionalities.

Thanks.

**Comment by narutoten520** [comment]
@mhtb32 Thanks for your response and suggestion. I will use the new comment for my next issue, Thanks.

**Comment by eleurent** [comment]
Hi @mhtb32, thank you for answering narutoten.
Regarding your original question, I do not have anything planned in particular, so now is as good a time as any for a first stable version. I may just finish the few missing sections in the documentation before settling.

**Comment by eleurent** [comment]
v1.0 has been released (before merging the multi-agent feature).
