### ISSUE TITLE
Change the acceleration of ego car

### ISSUE THREAD

**Issue by Pei-w** [eleurent/highway-env#95]
I want to write a program that changes the acceleration of the ego-car, but I tried it and it didn't work, how do I get the acceleration that I need to pass to the Ego-car.

**Comment by Pei-w** [comment]
I did it !!!!!

**Comment by eleurent** [comment]
For future reference (in case someone else needs it): environments can be configured to accept continuous actions (acceleration, steering) as input, [see the documentation](https://highway-env.readthedocs.io/en/latest/actions/index.html).
