### ISSUE TITLE
ContinuousAction type env.reset() problem

### ISSUE THREAD

**Issue by Guo-Youtian** [eleurent/highway-env#96]
my code is as fellow,but it crashed at the 2nd reset() interation process with this problem :**Python37\site-packages\highway_env\envs\highway_env.py", line 82, in _reward
    else MDPVehicle.speed_to_index(self.vehicle.speed)
TypeError: speed_to_index() missing 1 required positional argument: 'speed'**

however, when i change the action type to DiscreteMetaAction , the code can work well, it's a weird problem

env = gym.make('highway-v0')

env_configure = {

        "id": "highway-v0",
        "import_module": "highway_env",
        "lanes_count": 3,
        "vehicles_count": 50,
        "duration": 30,
        "other_vehicles_type": "highway_env.vehicle.behavior.IDMVehicle",
        "observation": {
            "type": "Kinematics",
            "vehicles_count": 15,
            "features": ["presence", "x", "y", "vx", "vy", "cos_h", "sin_h"]
        },
        "action": {
        "type": "ContinuousAction"
        }
    }
env.unwrapped.configure(env_configure)

for _ in range(10):
    env.reset()
    for t in range(100):
        env.render()
        action = env.action_space.sample()
        env.step(action)

        if env.vehicle.crashed:
            break

**Comment by eleurent** [comment]
Hi @Guo-Youtian, thanks a lot for the feedback!
There was indeed a bug, which I have fixed.
Please update your highway-env installation and you should be alright.
